// Code generated by ent, DO NOT EDIT.

package ranking3v3

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ranking3v3 type in the database.
	Label = "ranking3v3"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRank holds the string denoting the rank field in the database.
	FieldRank = "rank"
	// FieldGames holds the string denoting the games field in the database.
	FieldGames = "games"
	// FieldWins holds the string denoting the wins field in the database.
	FieldWins = "wins"
	// FieldLosses holds the string denoting the losses field in the database.
	FieldLosses = "losses"
	// FieldDraws holds the string denoting the draws field in the database.
	FieldDraws = "draws"
	// FieldWinRate holds the string denoting the win_rate field in the database.
	FieldWinRate = "win_rate"
	// FieldAvgApm holds the string denoting the avg_apm field in the database.
	FieldAvgApm = "avg_apm"
	// FieldAvgEapm holds the string denoting the avg_eapm field in the database.
	FieldAvgEapm = "avg_eapm"
	// FieldMinGames holds the string denoting the min_games field in the database.
	FieldMinGames = "min_games"
	// FieldComputedAt holds the string denoting the computed_at field in the database.
	FieldComputedAt = "computed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the ranking3v3 in the database.
	Table = "ranking_3v3"
)

// Columns holds all SQL columns for ranking3v3 fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRank,
	FieldGames,
	FieldWins,
	FieldLosses,
	FieldDraws,
	FieldWinRate,
	FieldAvgApm,
	FieldAvgEapm,
	FieldMinGames,
	FieldComputedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultRank holds the default value on creation for the "rank" field.
	DefaultRank int
	// DefaultGames holds the default value on creation for the "games" field.
	DefaultGames int
	// DefaultWins holds the default value on creation for the "wins" field.
	DefaultWins int
	// DefaultLosses holds the default value on creation for the "losses" field.
	DefaultLosses int
	// DefaultDraws holds the default value on creation for the "draws" field.
	DefaultDraws int
	// DefaultWinRate holds the default value on creation for the "win_rate" field.
	DefaultWinRate float64
	// DefaultAvgApm holds the default value on creation for the "avg_apm" field.
	DefaultAvgApm float64
	// DefaultAvgEapm holds the default value on creation for the "avg_eapm" field.
	DefaultAvgEapm float64
	// DefaultMinGames holds the default value on creation for the "min_games" field.
	DefaultMinGames int
	// DefaultComputedAt holds the default value on creation for the "computed_at" field.
	DefaultComputedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Ranking3v3 queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRank orders the results by the rank field.
func ByRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRank, opts...).ToFunc()
}

// ByGames orders the results by the games field.
func ByGames(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGames, opts...).ToFunc()
}

// ByWins orders the results by the wins field.
func ByWins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWins, opts...).ToFunc()
}

// ByLosses orders the results by the losses field.
func ByLosses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLosses, opts...).ToFunc()
}

// ByDraws orders the results by the draws field.
func ByDraws(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraws, opts...).ToFunc()
}

// ByWinRate orders the results by the win_rate field.
func ByWinRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWinRate, opts...).ToFunc()
}

// ByAvgApm orders the results by the avg_apm field.
func ByAvgApm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgApm, opts...).ToFunc()
}

// ByAvgEapm orders the results by the avg_eapm field.
func ByAvgEapm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgEapm, opts...).ToFunc()
}

// ByMinGames orders the results by the min_games field.
func ByMinGames(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinGames, opts...).ToFunc()
}

// ByComputedAt orders the results by the computed_at field.
func ByComputedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
