// Code generated by ent, DO NOT EDIT.

package gamedetail

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the gamedetail type in the database.
	Label = "game_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApmTimeline holds the string denoting the apm_timeline field in the database.
	FieldApmTimeline = "apm_timeline"
	// FieldBuildOrders holds the string denoting the build_orders field in the database.
	FieldBuildOrders = "build_orders"
	// FieldCompressedBuildOrders holds the string denoting the compressed_build_orders field in the database.
	FieldCompressedBuildOrders = "compressed_build_orders"
	// FieldChatMessages holds the string denoting the chat_messages field in the database.
	FieldChatMessages = "chat_messages"
	// EdgeGame holds the string denoting the game edge name in mutations.
	EdgeGame = "game"
	// Table holds the table name of the gamedetail in the database.
	Table = "game_details"
	// GameTable is the table that holds the game relation/edge.
	GameTable = "game_details"
	// GameInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GameInverseTable = "games"
	// GameColumn is the table column denoting the game relation/edge.
	GameColumn = "game_game_detail"
)

// Columns holds all SQL columns for gamedetail fields.
var Columns = []string{
	FieldID,
	FieldApmTimeline,
	FieldBuildOrders,
	FieldCompressedBuildOrders,
	FieldChatMessages,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "game_details"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"game_game_detail",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the GameDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGameField orders the results by game field.
func ByGameField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGameStep(), sql.OrderByField(field, opts...))
	}
}
func newGameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, GameTable, GameColumn),
	)
}
