// Code generated by ent, DO NOT EDIT.

package analyzerracematchup

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the analyzerracematchup type in the database.
	Label = "analyzer_race_matchup"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTeamSize holds the string denoting the team_size field in the database.
	FieldTeamSize = "team_size"
	// FieldTeamA holds the string denoting the team_a field in the database.
	FieldTeamA = "team_a"
	// FieldTeamB holds the string denoting the team_b field in the database.
	FieldTeamB = "team_b"
	// FieldMatchupKey holds the string denoting the matchup_key field in the database.
	FieldMatchupKey = "matchup_key"
	// FieldGames holds the string denoting the games field in the database.
	FieldGames = "games"
	// FieldTeamAWins holds the string denoting the team_a_wins field in the database.
	FieldTeamAWins = "team_a_wins"
	// FieldTeamBWins holds the string denoting the team_b_wins field in the database.
	FieldTeamBWins = "team_b_wins"
	// FieldTeamAWinRate holds the string denoting the team_a_win_rate field in the database.
	FieldTeamAWinRate = "team_a_win_rate"
	// FieldTeamBWinRate holds the string denoting the team_b_win_rate field in the database.
	FieldTeamBWinRate = "team_b_win_rate"
	// FieldComputedAt holds the string denoting the computed_at field in the database.
	FieldComputedAt = "computed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the analyzerracematchup in the database.
	Table = "analyzer_race_matchups"
)

// Columns holds all SQL columns for analyzerracematchup fields.
var Columns = []string{
	FieldID,
	FieldTeamSize,
	FieldTeamA,
	FieldTeamB,
	FieldMatchupKey,
	FieldGames,
	FieldTeamAWins,
	FieldTeamBWins,
	FieldTeamAWinRate,
	FieldTeamBWinRate,
	FieldComputedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTeamSize holds the default value on creation for the "team_size" field.
	DefaultTeamSize int
	// TeamAValidator is a validator for the "team_a" field. It is called by the builders before save.
	TeamAValidator func(string) error
	// TeamBValidator is a validator for the "team_b" field. It is called by the builders before save.
	TeamBValidator func(string) error
	// MatchupKeyValidator is a validator for the "matchup_key" field. It is called by the builders before save.
	MatchupKeyValidator func(string) error
	// DefaultGames holds the default value on creation for the "games" field.
	DefaultGames int
	// DefaultTeamAWins holds the default value on creation for the "team_a_wins" field.
	DefaultTeamAWins int
	// DefaultTeamBWins holds the default value on creation for the "team_b_wins" field.
	DefaultTeamBWins int
	// DefaultTeamAWinRate holds the default value on creation for the "team_a_win_rate" field.
	DefaultTeamAWinRate float64
	// DefaultTeamBWinRate holds the default value on creation for the "team_b_win_rate" field.
	DefaultTeamBWinRate float64
	// DefaultComputedAt holds the default value on creation for the "computed_at" field.
	DefaultComputedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AnalyzerRaceMatchup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTeamSize orders the results by the team_size field.
func ByTeamSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamSize, opts...).ToFunc()
}

// ByTeamA orders the results by the team_a field.
func ByTeamA(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamA, opts...).ToFunc()
}

// ByTeamB orders the results by the team_b field.
func ByTeamB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamB, opts...).ToFunc()
}

// ByMatchupKey orders the results by the matchup_key field.
func ByMatchupKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchupKey, opts...).ToFunc()
}

// ByGames orders the results by the games field.
func ByGames(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGames, opts...).ToFunc()
}

// ByTeamAWins orders the results by the team_a_wins field.
func ByTeamAWins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamAWins, opts...).ToFunc()
}

// ByTeamBWins orders the results by the team_b_wins field.
func ByTeamBWins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamBWins, opts...).ToFunc()
}

// ByTeamAWinRate orders the results by the team_a_win_rate field.
func ByTeamAWinRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamAWinRate, opts...).ToFunc()
}

// ByTeamBWinRate orders the results by the team_b_win_rate field.
func ByTeamBWinRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamBWinRate, opts...).ToFunc()
}

// ByComputedAt orders the results by the computed_at field.
func ByComputedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
