// Code generated by ent, DO NOT EDIT.

package analyzerracematchup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/xungwoo/stareplays/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldID, id))
}

// TeamSize applies equality check predicate on the "team_size" field. It's identical to TeamSizeEQ.
func TeamSize(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamSize, v))
}

// TeamA applies equality check predicate on the "team_a" field. It's identical to TeamAEQ.
func TeamA(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamA, v))
}

// TeamB applies equality check predicate on the "team_b" field. It's identical to TeamBEQ.
func TeamB(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamB, v))
}

// MatchupKey applies equality check predicate on the "matchup_key" field. It's identical to MatchupKeyEQ.
func MatchupKey(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldMatchupKey, v))
}

// Games applies equality check predicate on the "games" field. It's identical to GamesEQ.
func Games(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldGames, v))
}

// TeamAWins applies equality check predicate on the "team_a_wins" field. It's identical to TeamAWinsEQ.
func TeamAWins(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamAWins, v))
}

// TeamBWins applies equality check predicate on the "team_b_wins" field. It's identical to TeamBWinsEQ.
func TeamBWins(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamBWins, v))
}

// TeamAWinRate applies equality check predicate on the "team_a_win_rate" field. It's identical to TeamAWinRateEQ.
func TeamAWinRate(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamAWinRate, v))
}

// TeamBWinRate applies equality check predicate on the "team_b_win_rate" field. It's identical to TeamBWinRateEQ.
func TeamBWinRate(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamBWinRate, v))
}

// ComputedAt applies equality check predicate on the "computed_at" field. It's identical to ComputedAtEQ.
func ComputedAt(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldComputedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamSizeEQ applies the EQ predicate on the "team_size" field.
func TeamSizeEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamSize, v))
}

// TeamSizeNEQ applies the NEQ predicate on the "team_size" field.
func TeamSizeNEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamSize, v))
}

// TeamSizeIn applies the In predicate on the "team_size" field.
func TeamSizeIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamSize, vs...))
}

// TeamSizeNotIn applies the NotIn predicate on the "team_size" field.
func TeamSizeNotIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamSize, vs...))
}

// TeamSizeGT applies the GT predicate on the "team_size" field.
func TeamSizeGT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamSize, v))
}

// TeamSizeGTE applies the GTE predicate on the "team_size" field.
func TeamSizeGTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamSize, v))
}

// TeamSizeLT applies the LT predicate on the "team_size" field.
func TeamSizeLT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamSize, v))
}

// TeamSizeLTE applies the LTE predicate on the "team_size" field.
func TeamSizeLTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamSize, v))
}

// TeamAEQ applies the EQ predicate on the "team_a" field.
func TeamAEQ(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamA, v))
}

// TeamANEQ applies the NEQ predicate on the "team_a" field.
func TeamANEQ(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamA, v))
}

// TeamAIn applies the In predicate on the "team_a" field.
func TeamAIn(vs ...string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamA, vs...))
}

// TeamANotIn applies the NotIn predicate on the "team_a" field.
func TeamANotIn(vs ...string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamA, vs...))
}

// TeamAGT applies the GT predicate on the "team_a" field.
func TeamAGT(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamA, v))
}

// TeamAGTE applies the GTE predicate on the "team_a" field.
func TeamAGTE(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamA, v))
}

// TeamALT applies the LT predicate on the "team_a" field.
func TeamALT(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamA, v))
}

// TeamALTE applies the LTE predicate on the "team_a" field.
func TeamALTE(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamA, v))
}

// TeamAContains applies the Contains predicate on the "team_a" field.
func TeamAContains(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldContains(FieldTeamA, v))
}

// TeamAHasPrefix applies the HasPrefix predicate on the "team_a" field.
func TeamAHasPrefix(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldHasPrefix(FieldTeamA, v))
}

// TeamAHasSuffix applies the HasSuffix predicate on the "team_a" field.
func TeamAHasSuffix(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldHasSuffix(FieldTeamA, v))
}

// TeamAEqualFold applies the EqualFold predicate on the "team_a" field.
func TeamAEqualFold(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEqualFold(FieldTeamA, v))
}

// TeamAContainsFold applies the ContainsFold predicate on the "team_a" field.
func TeamAContainsFold(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldContainsFold(FieldTeamA, v))
}

// TeamBEQ applies the EQ predicate on the "team_b" field.
func TeamBEQ(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamB, v))
}

// TeamBNEQ applies the NEQ predicate on the "team_b" field.
func TeamBNEQ(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamB, v))
}

// TeamBIn applies the In predicate on the "team_b" field.
func TeamBIn(vs ...string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamB, vs...))
}

// TeamBNotIn applies the NotIn predicate on the "team_b" field.
func TeamBNotIn(vs ...string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamB, vs...))
}

// TeamBGT applies the GT predicate on the "team_b" field.
func TeamBGT(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamB, v))
}

// TeamBGTE applies the GTE predicate on the "team_b" field.
func TeamBGTE(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamB, v))
}

// TeamBLT applies the LT predicate on the "team_b" field.
func TeamBLT(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamB, v))
}

// TeamBLTE applies the LTE predicate on the "team_b" field.
func TeamBLTE(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamB, v))
}

// TeamBContains applies the Contains predicate on the "team_b" field.
func TeamBContains(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldContains(FieldTeamB, v))
}

// TeamBHasPrefix applies the HasPrefix predicate on the "team_b" field.
func TeamBHasPrefix(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldHasPrefix(FieldTeamB, v))
}

// TeamBHasSuffix applies the HasSuffix predicate on the "team_b" field.
func TeamBHasSuffix(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldHasSuffix(FieldTeamB, v))
}

// TeamBEqualFold applies the EqualFold predicate on the "team_b" field.
func TeamBEqualFold(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEqualFold(FieldTeamB, v))
}

// TeamBContainsFold applies the ContainsFold predicate on the "team_b" field.
func TeamBContainsFold(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldContainsFold(FieldTeamB, v))
}

// MatchupKeyEQ applies the EQ predicate on the "matchup_key" field.
func MatchupKeyEQ(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldMatchupKey, v))
}

// MatchupKeyNEQ applies the NEQ predicate on the "matchup_key" field.
func MatchupKeyNEQ(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldMatchupKey, v))
}

// MatchupKeyIn applies the In predicate on the "matchup_key" field.
func MatchupKeyIn(vs ...string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldMatchupKey, vs...))
}

// MatchupKeyNotIn applies the NotIn predicate on the "matchup_key" field.
func MatchupKeyNotIn(vs ...string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldMatchupKey, vs...))
}

// MatchupKeyGT applies the GT predicate on the "matchup_key" field.
func MatchupKeyGT(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldMatchupKey, v))
}

// MatchupKeyGTE applies the GTE predicate on the "matchup_key" field.
func MatchupKeyGTE(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldMatchupKey, v))
}

// MatchupKeyLT applies the LT predicate on the "matchup_key" field.
func MatchupKeyLT(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldMatchupKey, v))
}

// MatchupKeyLTE applies the LTE predicate on the "matchup_key" field.
func MatchupKeyLTE(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldMatchupKey, v))
}

// MatchupKeyContains applies the Contains predicate on the "matchup_key" field.
func MatchupKeyContains(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldContains(FieldMatchupKey, v))
}

// MatchupKeyHasPrefix applies the HasPrefix predicate on the "matchup_key" field.
func MatchupKeyHasPrefix(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldHasPrefix(FieldMatchupKey, v))
}

// MatchupKeyHasSuffix applies the HasSuffix predicate on the "matchup_key" field.
func MatchupKeyHasSuffix(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldHasSuffix(FieldMatchupKey, v))
}

// MatchupKeyEqualFold applies the EqualFold predicate on the "matchup_key" field.
func MatchupKeyEqualFold(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEqualFold(FieldMatchupKey, v))
}

// MatchupKeyContainsFold applies the ContainsFold predicate on the "matchup_key" field.
func MatchupKeyContainsFold(v string) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldContainsFold(FieldMatchupKey, v))
}

// GamesEQ applies the EQ predicate on the "games" field.
func GamesEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldGames, v))
}

// GamesNEQ applies the NEQ predicate on the "games" field.
func GamesNEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldGames, v))
}

// GamesIn applies the In predicate on the "games" field.
func GamesIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldGames, vs...))
}

// GamesNotIn applies the NotIn predicate on the "games" field.
func GamesNotIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldGames, vs...))
}

// GamesGT applies the GT predicate on the "games" field.
func GamesGT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldGames, v))
}

// GamesGTE applies the GTE predicate on the "games" field.
func GamesGTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldGames, v))
}

// GamesLT applies the LT predicate on the "games" field.
func GamesLT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldGames, v))
}

// GamesLTE applies the LTE predicate on the "games" field.
func GamesLTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldGames, v))
}

// TeamAWinsEQ applies the EQ predicate on the "team_a_wins" field.
func TeamAWinsEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamAWins, v))
}

// TeamAWinsNEQ applies the NEQ predicate on the "team_a_wins" field.
func TeamAWinsNEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamAWins, v))
}

// TeamAWinsIn applies the In predicate on the "team_a_wins" field.
func TeamAWinsIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamAWins, vs...))
}

// TeamAWinsNotIn applies the NotIn predicate on the "team_a_wins" field.
func TeamAWinsNotIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamAWins, vs...))
}

// TeamAWinsGT applies the GT predicate on the "team_a_wins" field.
func TeamAWinsGT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamAWins, v))
}

// TeamAWinsGTE applies the GTE predicate on the "team_a_wins" field.
func TeamAWinsGTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamAWins, v))
}

// TeamAWinsLT applies the LT predicate on the "team_a_wins" field.
func TeamAWinsLT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamAWins, v))
}

// TeamAWinsLTE applies the LTE predicate on the "team_a_wins" field.
func TeamAWinsLTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamAWins, v))
}

// TeamBWinsEQ applies the EQ predicate on the "team_b_wins" field.
func TeamBWinsEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamBWins, v))
}

// TeamBWinsNEQ applies the NEQ predicate on the "team_b_wins" field.
func TeamBWinsNEQ(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamBWins, v))
}

// TeamBWinsIn applies the In predicate on the "team_b_wins" field.
func TeamBWinsIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamBWins, vs...))
}

// TeamBWinsNotIn applies the NotIn predicate on the "team_b_wins" field.
func TeamBWinsNotIn(vs ...int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamBWins, vs...))
}

// TeamBWinsGT applies the GT predicate on the "team_b_wins" field.
func TeamBWinsGT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamBWins, v))
}

// TeamBWinsGTE applies the GTE predicate on the "team_b_wins" field.
func TeamBWinsGTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamBWins, v))
}

// TeamBWinsLT applies the LT predicate on the "team_b_wins" field.
func TeamBWinsLT(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamBWins, v))
}

// TeamBWinsLTE applies the LTE predicate on the "team_b_wins" field.
func TeamBWinsLTE(v int) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamBWins, v))
}

// TeamAWinRateEQ applies the EQ predicate on the "team_a_win_rate" field.
func TeamAWinRateEQ(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamAWinRate, v))
}

// TeamAWinRateNEQ applies the NEQ predicate on the "team_a_win_rate" field.
func TeamAWinRateNEQ(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamAWinRate, v))
}

// TeamAWinRateIn applies the In predicate on the "team_a_win_rate" field.
func TeamAWinRateIn(vs ...float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamAWinRate, vs...))
}

// TeamAWinRateNotIn applies the NotIn predicate on the "team_a_win_rate" field.
func TeamAWinRateNotIn(vs ...float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamAWinRate, vs...))
}

// TeamAWinRateGT applies the GT predicate on the "team_a_win_rate" field.
func TeamAWinRateGT(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamAWinRate, v))
}

// TeamAWinRateGTE applies the GTE predicate on the "team_a_win_rate" field.
func TeamAWinRateGTE(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamAWinRate, v))
}

// TeamAWinRateLT applies the LT predicate on the "team_a_win_rate" field.
func TeamAWinRateLT(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamAWinRate, v))
}

// TeamAWinRateLTE applies the LTE predicate on the "team_a_win_rate" field.
func TeamAWinRateLTE(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamAWinRate, v))
}

// TeamBWinRateEQ applies the EQ predicate on the "team_b_win_rate" field.
func TeamBWinRateEQ(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldTeamBWinRate, v))
}

// TeamBWinRateNEQ applies the NEQ predicate on the "team_b_win_rate" field.
func TeamBWinRateNEQ(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldTeamBWinRate, v))
}

// TeamBWinRateIn applies the In predicate on the "team_b_win_rate" field.
func TeamBWinRateIn(vs ...float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldTeamBWinRate, vs...))
}

// TeamBWinRateNotIn applies the NotIn predicate on the "team_b_win_rate" field.
func TeamBWinRateNotIn(vs ...float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldTeamBWinRate, vs...))
}

// TeamBWinRateGT applies the GT predicate on the "team_b_win_rate" field.
func TeamBWinRateGT(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldTeamBWinRate, v))
}

// TeamBWinRateGTE applies the GTE predicate on the "team_b_win_rate" field.
func TeamBWinRateGTE(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldTeamBWinRate, v))
}

// TeamBWinRateLT applies the LT predicate on the "team_b_win_rate" field.
func TeamBWinRateLT(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldTeamBWinRate, v))
}

// TeamBWinRateLTE applies the LTE predicate on the "team_b_win_rate" field.
func TeamBWinRateLTE(v float64) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldTeamBWinRate, v))
}

// ComputedAtEQ applies the EQ predicate on the "computed_at" field.
func ComputedAtEQ(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldComputedAt, v))
}

// ComputedAtNEQ applies the NEQ predicate on the "computed_at" field.
func ComputedAtNEQ(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldComputedAt, v))
}

// ComputedAtIn applies the In predicate on the "computed_at" field.
func ComputedAtIn(vs ...time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldComputedAt, vs...))
}

// ComputedAtNotIn applies the NotIn predicate on the "computed_at" field.
func ComputedAtNotIn(vs ...time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldComputedAt, vs...))
}

// ComputedAtGT applies the GT predicate on the "computed_at" field.
func ComputedAtGT(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldComputedAt, v))
}

// ComputedAtGTE applies the GTE predicate on the "computed_at" field.
func ComputedAtGTE(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldComputedAt, v))
}

// ComputedAtLT applies the LT predicate on the "computed_at" field.
func ComputedAtLT(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldComputedAt, v))
}

// ComputedAtLTE applies the LTE predicate on the "computed_at" field.
func ComputedAtLTE(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldComputedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnalyzerRaceMatchup) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnalyzerRaceMatchup) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnalyzerRaceMatchup) predicate.AnalyzerRaceMatchup {
	return predicate.AnalyzerRaceMatchup(sql.NotPredicates(p))
}
