[build]
builder = "NIXPACKS"
buildCommand = "if [ -f go.mod ]; then go mod download && go build -o bin/analyzer-job ./cmd/analyzer-job/main.go; else cd backend && go mod download && go build -o bin/analyzer-job ./cmd/analyzer-job/main.go; fi"

[deploy]
startCommand = "if [ -f ./bin/analyzer-job ]; then ./bin/analyzer-job; else cd backend && ./bin/analyzer-job; fi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
