[build]
builder = "NIXPACKS"
buildCommand = "go mod download && go build -o /backend/bin/analyzer-job /backend//cmd/analyzer-job/main.go"

[deploy]
startCommand = "/backend/bin/analyzer-job"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
