[build]
builder = "NIXPACKS"
buildCommand = "go mod download && go build -o bin/ranking-job ./cmd/ranking-job/main.go"

[deploy]
startCommand = "./bin/ranking-job"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
