// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/xungwoo/stareplays/ent/analyzerracematchup"
)

// AnalyzerRaceMatchup is the model entity for the AnalyzerRaceMatchup schema.
type AnalyzerRaceMatchup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TeamSize holds the value of the "team_size" field.
	TeamSize int `json:"team_size,omitempty"`
	// TeamA holds the value of the "team_a" field.
	TeamA string `json:"team_a,omitempty"`
	// TeamB holds the value of the "team_b" field.
	TeamB string `json:"team_b,omitempty"`
	// MatchupKey holds the value of the "matchup_key" field.
	MatchupKey string `json:"matchup_key,omitempty"`
	// Games holds the value of the "games" field.
	Games int `json:"games,omitempty"`
	// TeamAWins holds the value of the "team_a_wins" field.
	TeamAWins int `json:"team_a_wins,omitempty"`
	// TeamBWins holds the value of the "team_b_wins" field.
	TeamBWins int `json:"team_b_wins,omitempty"`
	// TeamAWinRate holds the value of the "team_a_win_rate" field.
	TeamAWinRate float64 `json:"team_a_win_rate,omitempty"`
	// TeamBWinRate holds the value of the "team_b_win_rate" field.
	TeamBWinRate float64 `json:"team_b_win_rate,omitempty"`
	// ComputedAt holds the value of the "computed_at" field.
	ComputedAt time.Time `json:"computed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnalyzerRaceMatchup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case analyzerracematchup.FieldTeamAWinRate, analyzerracematchup.FieldTeamBWinRate:
			values[i] = new(sql.NullFloat64)
		case analyzerracematchup.FieldID, analyzerracematchup.FieldTeamSize, analyzerracematchup.FieldGames, analyzerracematchup.FieldTeamAWins, analyzerracematchup.FieldTeamBWins:
			values[i] = new(sql.NullInt64)
		case analyzerracematchup.FieldTeamA, analyzerracematchup.FieldTeamB, analyzerracematchup.FieldMatchupKey:
			values[i] = new(sql.NullString)
		case analyzerracematchup.FieldComputedAt, analyzerracematchup.FieldCreatedAt, analyzerracematchup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnalyzerRaceMatchup fields.
func (_m *AnalyzerRaceMatchup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case analyzerracematchup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case analyzerracematchup.FieldTeamSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_size", values[i])
			} else if value.Valid {
				_m.TeamSize = int(value.Int64)
			}
		case analyzerracematchup.FieldTeamA:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_a", values[i])
			} else if value.Valid {
				_m.TeamA = value.String
			}
		case analyzerracematchup.FieldTeamB:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_b", values[i])
			} else if value.Valid {
				_m.TeamB = value.String
			}
		case analyzerracematchup.FieldMatchupKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field matchup_key", values[i])
			} else if value.Valid {
				_m.MatchupKey = value.String
			}
		case analyzerracematchup.FieldGames:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field games", values[i])
			} else if value.Valid {
				_m.Games = int(value.Int64)
			}
		case analyzerracematchup.FieldTeamAWins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_a_wins", values[i])
			} else if value.Valid {
				_m.TeamAWins = int(value.Int64)
			}
		case analyzerracematchup.FieldTeamBWins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_b_wins", values[i])
			} else if value.Valid {
				_m.TeamBWins = int(value.Int64)
			}
		case analyzerracematchup.FieldTeamAWinRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field team_a_win_rate", values[i])
			} else if value.Valid {
				_m.TeamAWinRate = value.Float64
			}
		case analyzerracematchup.FieldTeamBWinRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field team_b_win_rate", values[i])
			} else if value.Valid {
				_m.TeamBWinRate = value.Float64
			}
		case analyzerracematchup.FieldComputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field computed_at", values[i])
			} else if value.Valid {
				_m.ComputedAt = value.Time
			}
		case analyzerracematchup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case analyzerracematchup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnalyzerRaceMatchup.
// This includes values selected through modifiers, order, etc.
func (_m *AnalyzerRaceMatchup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AnalyzerRaceMatchup.
// Note that you need to call AnalyzerRaceMatchup.Unwrap() before calling this method if this AnalyzerRaceMatchup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnalyzerRaceMatchup) Update() *AnalyzerRaceMatchupUpdateOne {
	return NewAnalyzerRaceMatchupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnalyzerRaceMatchup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnalyzerRaceMatchup) Unwrap() *AnalyzerRaceMatchup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnalyzerRaceMatchup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnalyzerRaceMatchup) String() string {
	var builder strings.Builder
	builder.WriteString("AnalyzerRaceMatchup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamSize))
	builder.WriteString(", ")
	builder.WriteString("team_a=")
	builder.WriteString(_m.TeamA)
	builder.WriteString(", ")
	builder.WriteString("team_b=")
	builder.WriteString(_m.TeamB)
	builder.WriteString(", ")
	builder.WriteString("matchup_key=")
	builder.WriteString(_m.MatchupKey)
	builder.WriteString(", ")
	builder.WriteString("games=")
	builder.WriteString(fmt.Sprintf("%v", _m.Games))
	builder.WriteString(", ")
	builder.WriteString("team_a_wins=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamAWins))
	builder.WriteString(", ")
	builder.WriteString("team_b_wins=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamBWins))
	builder.WriteString(", ")
	builder.WriteString("team_a_win_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamAWinRate))
	builder.WriteString(", ")
	builder.WriteString("team_b_win_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamBWinRate))
	builder.WriteString(", ")
	builder.WriteString("computed_at=")
	builder.WriteString(_m.ComputedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AnalyzerRaceMatchups is a parsable slice of AnalyzerRaceMatchup.
type AnalyzerRaceMatchups []*AnalyzerRaceMatchup
