// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareplays/ent/analyzerracematchup"
	"github.com/xungwoo/stareplays/ent/predicate"
)

// AnalyzerRaceMatchupDelete is the builder for deleting a AnalyzerRaceMatchup entity.
type AnalyzerRaceMatchupDelete struct {
	config
	hooks    []Hook
	mutation *AnalyzerRaceMatchupMutation
}

// Where appends a list predicates to the AnalyzerRaceMatchupDelete builder.
func (_d *AnalyzerRaceMatchupDelete) Where(ps ...predicate.AnalyzerRaceMatchup) *AnalyzerRaceMatchupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnalyzerRaceMatchupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnalyzerRaceMatchupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnalyzerRaceMatchupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(analyzerracematchup.Table, sqlgraph.NewFieldSpec(analyzerracematchup.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnalyzerRaceMatchupDeleteOne is the builder for deleting a single AnalyzerRaceMatchup entity.
type AnalyzerRaceMatchupDeleteOne struct {
	_d *AnalyzerRaceMatchupDelete
}

// Where appends a list predicates to the AnalyzerRaceMatchupDelete builder.
func (_d *AnalyzerRaceMatchupDeleteOne) Where(ps ...predicate.AnalyzerRaceMatchup) *AnalyzerRaceMatchupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnalyzerRaceMatchupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{analyzerracematchup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnalyzerRaceMatchupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
