// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/xungwoo/stareplays/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/xungwoo/stareplays/ent/analyzerracematchup"
	"github.com/xungwoo/stareplays/ent/game"
	"github.com/xungwoo/stareplays/ent/gamedetail"
	"github.com/xungwoo/stareplays/ent/player"
	"github.com/xungwoo/stareplays/ent/ranking3v3"
	"github.com/xungwoo/stareplays/ent/replayfile"
	"github.com/xungwoo/stareplays/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AnalyzerRaceMatchup is the client for interacting with the AnalyzerRaceMatchup builders.
	AnalyzerRaceMatchup *AnalyzerRaceMatchupClient
	// Game is the client for interacting with the Game builders.
	Game *GameClient
	// GameDetail is the client for interacting with the GameDetail builders.
	GameDetail *GameDetailClient
	// Player is the client for interacting with the Player builders.
	Player *PlayerClient
	// Ranking3v3 is the client for interacting with the Ranking3v3 builders.
	Ranking3v3 *Ranking3v3Client
	// ReplayFile is the client for interacting with the ReplayFile builders.
	ReplayFile *ReplayFileClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AnalyzerRaceMatchup = NewAnalyzerRaceMatchupClient(c.config)
	c.Game = NewGameClient(c.config)
	c.GameDetail = NewGameDetailClient(c.config)
	c.Player = NewPlayerClient(c.config)
	c.Ranking3v3 = NewRanking3v3Client(c.config)
	c.ReplayFile = NewReplayFileClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		AnalyzerRaceMatchup: NewAnalyzerRaceMatchupClient(cfg),
		Game:                NewGameClient(cfg),
		GameDetail:          NewGameDetailClient(cfg),
		Player:              NewPlayerClient(cfg),
		Ranking3v3:          NewRanking3v3Client(cfg),
		ReplayFile:          NewReplayFileClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		AnalyzerRaceMatchup: NewAnalyzerRaceMatchupClient(cfg),
		Game:                NewGameClient(cfg),
		GameDetail:          NewGameDetailClient(cfg),
		Player:              NewPlayerClient(cfg),
		Ranking3v3:          NewRanking3v3Client(cfg),
		ReplayFile:          NewReplayFileClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AnalyzerRaceMatchup.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AnalyzerRaceMatchup, c.Game, c.GameDetail, c.Player, c.Ranking3v3,
		c.ReplayFile, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AnalyzerRaceMatchup, c.Game, c.GameDetail, c.Player, c.Ranking3v3,
		c.ReplayFile, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AnalyzerRaceMatchupMutation:
		return c.AnalyzerRaceMatchup.mutate(ctx, m)
	case *GameMutation:
		return c.Game.mutate(ctx, m)
	case *GameDetailMutation:
		return c.GameDetail.mutate(ctx, m)
	case *PlayerMutation:
		return c.Player.mutate(ctx, m)
	case *Ranking3v3Mutation:
		return c.Ranking3v3.mutate(ctx, m)
	case *ReplayFileMutation:
		return c.ReplayFile.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AnalyzerRaceMatchupClient is a client for the AnalyzerRaceMatchup schema.
type AnalyzerRaceMatchupClient struct {
	config
}

// NewAnalyzerRaceMatchupClient returns a client for the AnalyzerRaceMatchup from the given config.
func NewAnalyzerRaceMatchupClient(c config) *AnalyzerRaceMatchupClient {
	return &AnalyzerRaceMatchupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `analyzerracematchup.Hooks(f(g(h())))`.
func (c *AnalyzerRaceMatchupClient) Use(hooks ...Hook) {
	c.hooks.AnalyzerRaceMatchup = append(c.hooks.AnalyzerRaceMatchup, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `analyzerracematchup.Intercept(f(g(h())))`.
func (c *AnalyzerRaceMatchupClient) Intercept(interceptors ...Interceptor) {
	c.inters.AnalyzerRaceMatchup = append(c.inters.AnalyzerRaceMatchup, interceptors...)
}

// Create returns a builder for creating a AnalyzerRaceMatchup entity.
func (c *AnalyzerRaceMatchupClient) Create() *AnalyzerRaceMatchupCreate {
	mutation := newAnalyzerRaceMatchupMutation(c.config, OpCreate)
	return &AnalyzerRaceMatchupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AnalyzerRaceMatchup entities.
func (c *AnalyzerRaceMatchupClient) CreateBulk(builders ...*AnalyzerRaceMatchupCreate) *AnalyzerRaceMatchupCreateBulk {
	return &AnalyzerRaceMatchupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AnalyzerRaceMatchupClient) MapCreateBulk(slice any, setFunc func(*AnalyzerRaceMatchupCreate, int)) *AnalyzerRaceMatchupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AnalyzerRaceMatchupCreateBulk{err: fmt.Errorf("calling to AnalyzerRaceMatchupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AnalyzerRaceMatchupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AnalyzerRaceMatchupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AnalyzerRaceMatchup.
func (c *AnalyzerRaceMatchupClient) Update() *AnalyzerRaceMatchupUpdate {
	mutation := newAnalyzerRaceMatchupMutation(c.config, OpUpdate)
	return &AnalyzerRaceMatchupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AnalyzerRaceMatchupClient) UpdateOne(_m *AnalyzerRaceMatchup) *AnalyzerRaceMatchupUpdateOne {
	mutation := newAnalyzerRaceMatchupMutation(c.config, OpUpdateOne, withAnalyzerRaceMatchup(_m))
	return &AnalyzerRaceMatchupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AnalyzerRaceMatchupClient) UpdateOneID(id int) *AnalyzerRaceMatchupUpdateOne {
	mutation := newAnalyzerRaceMatchupMutation(c.config, OpUpdateOne, withAnalyzerRaceMatchupID(id))
	return &AnalyzerRaceMatchupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AnalyzerRaceMatchup.
func (c *AnalyzerRaceMatchupClient) Delete() *AnalyzerRaceMatchupDelete {
	mutation := newAnalyzerRaceMatchupMutation(c.config, OpDelete)
	return &AnalyzerRaceMatchupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AnalyzerRaceMatchupClient) DeleteOne(_m *AnalyzerRaceMatchup) *AnalyzerRaceMatchupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AnalyzerRaceMatchupClient) DeleteOneID(id int) *AnalyzerRaceMatchupDeleteOne {
	builder := c.Delete().Where(analyzerracematchup.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AnalyzerRaceMatchupDeleteOne{builder}
}

// Query returns a query builder for AnalyzerRaceMatchup.
func (c *AnalyzerRaceMatchupClient) Query() *AnalyzerRaceMatchupQuery {
	return &AnalyzerRaceMatchupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAnalyzerRaceMatchup},
		inters: c.Interceptors(),
	}
}

// Get returns a AnalyzerRaceMatchup entity by its id.
func (c *AnalyzerRaceMatchupClient) Get(ctx context.Context, id int) (*AnalyzerRaceMatchup, error) {
	return c.Query().Where(analyzerracematchup.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AnalyzerRaceMatchupClient) GetX(ctx context.Context, id int) *AnalyzerRaceMatchup {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AnalyzerRaceMatchupClient) Hooks() []Hook {
	return c.hooks.AnalyzerRaceMatchup
}

// Interceptors returns the client interceptors.
func (c *AnalyzerRaceMatchupClient) Interceptors() []Interceptor {
	return c.inters.AnalyzerRaceMatchup
}

func (c *AnalyzerRaceMatchupClient) mutate(ctx context.Context, m *AnalyzerRaceMatchupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AnalyzerRaceMatchupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AnalyzerRaceMatchupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AnalyzerRaceMatchupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AnalyzerRaceMatchupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AnalyzerRaceMatchup mutation op: %q", m.Op())
	}
}

// GameClient is a client for the Game schema.
type GameClient struct {
	config
}

// NewGameClient returns a client for the Game from the given config.
func NewGameClient(c config) *GameClient {
	return &GameClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `game.Hooks(f(g(h())))`.
func (c *GameClient) Use(hooks ...Hook) {
	c.hooks.Game = append(c.hooks.Game, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `game.Intercept(f(g(h())))`.
func (c *GameClient) Intercept(interceptors ...Interceptor) {
	c.inters.Game = append(c.inters.Game, interceptors...)
}

// Create returns a builder for creating a Game entity.
func (c *GameClient) Create() *GameCreate {
	mutation := newGameMutation(c.config, OpCreate)
	return &GameCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Game entities.
func (c *GameClient) CreateBulk(builders ...*GameCreate) *GameCreateBulk {
	return &GameCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GameClient) MapCreateBulk(slice any, setFunc func(*GameCreate, int)) *GameCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GameCreateBulk{err: fmt.Errorf("calling to GameClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GameCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GameCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Game.
func (c *GameClient) Update() *GameUpdate {
	mutation := newGameMutation(c.config, OpUpdate)
	return &GameUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GameClient) UpdateOne(_m *Game) *GameUpdateOne {
	mutation := newGameMutation(c.config, OpUpdateOne, withGame(_m))
	return &GameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GameClient) UpdateOneID(id int) *GameUpdateOne {
	mutation := newGameMutation(c.config, OpUpdateOne, withGameID(id))
	return &GameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Game.
func (c *GameClient) Delete() *GameDelete {
	mutation := newGameMutation(c.config, OpDelete)
	return &GameDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GameClient) DeleteOne(_m *Game) *GameDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GameClient) DeleteOneID(id int) *GameDeleteOne {
	builder := c.Delete().Where(game.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GameDeleteOne{builder}
}

// Query returns a query builder for Game.
func (c *GameClient) Query() *GameQuery {
	return &GameQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGame},
		inters: c.Interceptors(),
	}
}

// Get returns a Game entity by its id.
func (c *GameClient) Get(ctx context.Context, id int) (*Game, error) {
	return c.Query().Where(game.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GameClient) GetX(ctx context.Context, id int) *Game {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPlayers queries the players edge of a Game.
func (c *GameClient) QueryPlayers(_m *Game) *PlayerQuery {
	query := (&PlayerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, id),
			sqlgraph.To(player.Table, player.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, game.PlayersTable, game.PlayersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReplayFiles queries the replay_files edge of a Game.
func (c *GameClient) QueryReplayFiles(_m *Game) *ReplayFileQuery {
	query := (&ReplayFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, id),
			sqlgraph.To(replayfile.Table, replayfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, game.ReplayFilesTable, game.ReplayFilesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGameDetail queries the game_detail edge of a Game.
func (c *GameClient) QueryGameDetail(_m *Game) *GameDetailQuery {
	query := (&GameDetailClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, id),
			sqlgraph.To(gamedetail.Table, gamedetail.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, game.GameDetailTable, game.GameDetailColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GameClient) Hooks() []Hook {
	return c.hooks.Game
}

// Interceptors returns the client interceptors.
func (c *GameClient) Interceptors() []Interceptor {
	return c.inters.Game
}

func (c *GameClient) mutate(ctx context.Context, m *GameMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GameCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GameUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GameUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GameDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Game mutation op: %q", m.Op())
	}
}

// GameDetailClient is a client for the GameDetail schema.
type GameDetailClient struct {
	config
}

// NewGameDetailClient returns a client for the GameDetail from the given config.
func NewGameDetailClient(c config) *GameDetailClient {
	return &GameDetailClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gamedetail.Hooks(f(g(h())))`.
func (c *GameDetailClient) Use(hooks ...Hook) {
	c.hooks.GameDetail = append(c.hooks.GameDetail, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `gamedetail.Intercept(f(g(h())))`.
func (c *GameDetailClient) Intercept(interceptors ...Interceptor) {
	c.inters.GameDetail = append(c.inters.GameDetail, interceptors...)
}

// Create returns a builder for creating a GameDetail entity.
func (c *GameDetailClient) Create() *GameDetailCreate {
	mutation := newGameDetailMutation(c.config, OpCreate)
	return &GameDetailCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GameDetail entities.
func (c *GameDetailClient) CreateBulk(builders ...*GameDetailCreate) *GameDetailCreateBulk {
	return &GameDetailCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GameDetailClient) MapCreateBulk(slice any, setFunc func(*GameDetailCreate, int)) *GameDetailCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GameDetailCreateBulk{err: fmt.Errorf("calling to GameDetailClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GameDetailCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GameDetailCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GameDetail.
func (c *GameDetailClient) Update() *GameDetailUpdate {
	mutation := newGameDetailMutation(c.config, OpUpdate)
	return &GameDetailUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GameDetailClient) UpdateOne(_m *GameDetail) *GameDetailUpdateOne {
	mutation := newGameDetailMutation(c.config, OpUpdateOne, withGameDetail(_m))
	return &GameDetailUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GameDetailClient) UpdateOneID(id int) *GameDetailUpdateOne {
	mutation := newGameDetailMutation(c.config, OpUpdateOne, withGameDetailID(id))
	return &GameDetailUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GameDetail.
func (c *GameDetailClient) Delete() *GameDetailDelete {
	mutation := newGameDetailMutation(c.config, OpDelete)
	return &GameDetailDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GameDetailClient) DeleteOne(_m *GameDetail) *GameDetailDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GameDetailClient) DeleteOneID(id int) *GameDetailDeleteOne {
	builder := c.Delete().Where(gamedetail.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GameDetailDeleteOne{builder}
}

// Query returns a query builder for GameDetail.
func (c *GameDetailClient) Query() *GameDetailQuery {
	return &GameDetailQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGameDetail},
		inters: c.Interceptors(),
	}
}

// Get returns a GameDetail entity by its id.
func (c *GameDetailClient) Get(ctx context.Context, id int) (*GameDetail, error) {
	return c.Query().Where(gamedetail.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GameDetailClient) GetX(ctx context.Context, id int) *GameDetail {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGame queries the game edge of a GameDetail.
func (c *GameDetailClient) QueryGame(_m *GameDetail) *GameQuery {
	query := (&GameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(gamedetail.Table, gamedetail.FieldID, id),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, gamedetail.GameTable, gamedetail.GameColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GameDetailClient) Hooks() []Hook {
	return c.hooks.GameDetail
}

// Interceptors returns the client interceptors.
func (c *GameDetailClient) Interceptors() []Interceptor {
	return c.inters.GameDetail
}

func (c *GameDetailClient) mutate(ctx context.Context, m *GameDetailMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GameDetailCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GameDetailUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GameDetailUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GameDetailDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GameDetail mutation op: %q", m.Op())
	}
}

// PlayerClient is a client for the Player schema.
type PlayerClient struct {
	config
}

// NewPlayerClient returns a client for the Player from the given config.
func NewPlayerClient(c config) *PlayerClient {
	return &PlayerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `player.Hooks(f(g(h())))`.
func (c *PlayerClient) Use(hooks ...Hook) {
	c.hooks.Player = append(c.hooks.Player, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `player.Intercept(f(g(h())))`.
func (c *PlayerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Player = append(c.inters.Player, interceptors...)
}

// Create returns a builder for creating a Player entity.
func (c *PlayerClient) Create() *PlayerCreate {
	mutation := newPlayerMutation(c.config, OpCreate)
	return &PlayerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Player entities.
func (c *PlayerClient) CreateBulk(builders ...*PlayerCreate) *PlayerCreateBulk {
	return &PlayerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PlayerClient) MapCreateBulk(slice any, setFunc func(*PlayerCreate, int)) *PlayerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PlayerCreateBulk{err: fmt.Errorf("calling to PlayerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PlayerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PlayerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Player.
func (c *PlayerClient) Update() *PlayerUpdate {
	mutation := newPlayerMutation(c.config, OpUpdate)
	return &PlayerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PlayerClient) UpdateOne(_m *Player) *PlayerUpdateOne {
	mutation := newPlayerMutation(c.config, OpUpdateOne, withPlayer(_m))
	return &PlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PlayerClient) UpdateOneID(id int) *PlayerUpdateOne {
	mutation := newPlayerMutation(c.config, OpUpdateOne, withPlayerID(id))
	return &PlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Player.
func (c *PlayerClient) Delete() *PlayerDelete {
	mutation := newPlayerMutation(c.config, OpDelete)
	return &PlayerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PlayerClient) DeleteOne(_m *Player) *PlayerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PlayerClient) DeleteOneID(id int) *PlayerDeleteOne {
	builder := c.Delete().Where(player.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PlayerDeleteOne{builder}
}

// Query returns a query builder for Player.
func (c *PlayerClient) Query() *PlayerQuery {
	return &PlayerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePlayer},
		inters: c.Interceptors(),
	}
}

// Get returns a Player entity by its id.
func (c *PlayerClient) Get(ctx context.Context, id int) (*Player, error) {
	return c.Query().Where(player.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PlayerClient) GetX(ctx context.Context, id int) *Player {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGame queries the game edge of a Player.
func (c *PlayerClient) QueryGame(_m *Player) *GameQuery {
	query := (&GameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(player.Table, player.FieldID, id),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, player.GameTable, player.GameColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PlayerClient) Hooks() []Hook {
	return c.hooks.Player
}

// Interceptors returns the client interceptors.
func (c *PlayerClient) Interceptors() []Interceptor {
	return c.inters.Player
}

func (c *PlayerClient) mutate(ctx context.Context, m *PlayerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PlayerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PlayerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PlayerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Player mutation op: %q", m.Op())
	}
}

// Ranking3v3Client is a client for the Ranking3v3 schema.
type Ranking3v3Client struct {
	config
}

// NewRanking3v3Client returns a client for the Ranking3v3 from the given config.
func NewRanking3v3Client(c config) *Ranking3v3Client {
	return &Ranking3v3Client{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ranking3v3.Hooks(f(g(h())))`.
func (c *Ranking3v3Client) Use(hooks ...Hook) {
	c.hooks.Ranking3v3 = append(c.hooks.Ranking3v3, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ranking3v3.Intercept(f(g(h())))`.
func (c *Ranking3v3Client) Intercept(interceptors ...Interceptor) {
	c.inters.Ranking3v3 = append(c.inters.Ranking3v3, interceptors...)
}

// Create returns a builder for creating a Ranking3v3 entity.
func (c *Ranking3v3Client) Create() *Ranking3v3Create {
	mutation := newRanking3v3Mutation(c.config, OpCreate)
	return &Ranking3v3Create{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Ranking3v3 entities.
func (c *Ranking3v3Client) CreateBulk(builders ...*Ranking3v3Create) *Ranking3v3CreateBulk {
	return &Ranking3v3CreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *Ranking3v3Client) MapCreateBulk(slice any, setFunc func(*Ranking3v3Create, int)) *Ranking3v3CreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &Ranking3v3CreateBulk{err: fmt.Errorf("calling to Ranking3v3Client.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*Ranking3v3Create, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &Ranking3v3CreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Ranking3v3.
func (c *Ranking3v3Client) Update() *Ranking3v3Update {
	mutation := newRanking3v3Mutation(c.config, OpUpdate)
	return &Ranking3v3Update{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *Ranking3v3Client) UpdateOne(_m *Ranking3v3) *Ranking3v3UpdateOne {
	mutation := newRanking3v3Mutation(c.config, OpUpdateOne, withRanking3v3(_m))
	return &Ranking3v3UpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *Ranking3v3Client) UpdateOneID(id int) *Ranking3v3UpdateOne {
	mutation := newRanking3v3Mutation(c.config, OpUpdateOne, withRanking3v3ID(id))
	return &Ranking3v3UpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Ranking3v3.
func (c *Ranking3v3Client) Delete() *Ranking3v3Delete {
	mutation := newRanking3v3Mutation(c.config, OpDelete)
	return &Ranking3v3Delete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *Ranking3v3Client) DeleteOne(_m *Ranking3v3) *Ranking3v3DeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *Ranking3v3Client) DeleteOneID(id int) *Ranking3v3DeleteOne {
	builder := c.Delete().Where(ranking3v3.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &Ranking3v3DeleteOne{builder}
}

// Query returns a query builder for Ranking3v3.
func (c *Ranking3v3Client) Query() *Ranking3v3Query {
	return &Ranking3v3Query{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRanking3v3},
		inters: c.Interceptors(),
	}
}

// Get returns a Ranking3v3 entity by its id.
func (c *Ranking3v3Client) Get(ctx context.Context, id int) (*Ranking3v3, error) {
	return c.Query().Where(ranking3v3.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *Ranking3v3Client) GetX(ctx context.Context, id int) *Ranking3v3 {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *Ranking3v3Client) Hooks() []Hook {
	return c.hooks.Ranking3v3
}

// Interceptors returns the client interceptors.
func (c *Ranking3v3Client) Interceptors() []Interceptor {
	return c.inters.Ranking3v3
}

func (c *Ranking3v3Client) mutate(ctx context.Context, m *Ranking3v3Mutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&Ranking3v3Create{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&Ranking3v3Update{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&Ranking3v3UpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&Ranking3v3Delete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Ranking3v3 mutation op: %q", m.Op())
	}
}

// ReplayFileClient is a client for the ReplayFile schema.
type ReplayFileClient struct {
	config
}

// NewReplayFileClient returns a client for the ReplayFile from the given config.
func NewReplayFileClient(c config) *ReplayFileClient {
	return &ReplayFileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `replayfile.Hooks(f(g(h())))`.
func (c *ReplayFileClient) Use(hooks ...Hook) {
	c.hooks.ReplayFile = append(c.hooks.ReplayFile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `replayfile.Intercept(f(g(h())))`.
func (c *ReplayFileClient) Intercept(interceptors ...Interceptor) {
	c.inters.ReplayFile = append(c.inters.ReplayFile, interceptors...)
}

// Create returns a builder for creating a ReplayFile entity.
func (c *ReplayFileClient) Create() *ReplayFileCreate {
	mutation := newReplayFileMutation(c.config, OpCreate)
	return &ReplayFileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ReplayFile entities.
func (c *ReplayFileClient) CreateBulk(builders ...*ReplayFileCreate) *ReplayFileCreateBulk {
	return &ReplayFileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ReplayFileClient) MapCreateBulk(slice any, setFunc func(*ReplayFileCreate, int)) *ReplayFileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ReplayFileCreateBulk{err: fmt.Errorf("calling to ReplayFileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ReplayFileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ReplayFileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ReplayFile.
func (c *ReplayFileClient) Update() *ReplayFileUpdate {
	mutation := newReplayFileMutation(c.config, OpUpdate)
	return &ReplayFileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReplayFileClient) UpdateOne(_m *ReplayFile) *ReplayFileUpdateOne {
	mutation := newReplayFileMutation(c.config, OpUpdateOne, withReplayFile(_m))
	return &ReplayFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReplayFileClient) UpdateOneID(id int) *ReplayFileUpdateOne {
	mutation := newReplayFileMutation(c.config, OpUpdateOne, withReplayFileID(id))
	return &ReplayFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ReplayFile.
func (c *ReplayFileClient) Delete() *ReplayFileDelete {
	mutation := newReplayFileMutation(c.config, OpDelete)
	return &ReplayFileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ReplayFileClient) DeleteOne(_m *ReplayFile) *ReplayFileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ReplayFileClient) DeleteOneID(id int) *ReplayFileDeleteOne {
	builder := c.Delete().Where(replayfile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReplayFileDeleteOne{builder}
}

// Query returns a query builder for ReplayFile.
func (c *ReplayFileClient) Query() *ReplayFileQuery {
	return &ReplayFileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeReplayFile},
		inters: c.Interceptors(),
	}
}

// Get returns a ReplayFile entity by its id.
func (c *ReplayFileClient) Get(ctx context.Context, id int) (*ReplayFile, error) {
	return c.Query().Where(replayfile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReplayFileClient) GetX(ctx context.Context, id int) *ReplayFile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGame queries the game edge of a ReplayFile.
func (c *ReplayFileClient) QueryGame(_m *ReplayFile) *GameQuery {
	query := (&GameClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(replayfile.Table, replayfile.FieldID, id),
			sqlgraph.To(game.Table, game.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, replayfile.GameTable, replayfile.GameColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUploader queries the uploader edge of a ReplayFile.
func (c *ReplayFileClient) QueryUploader(_m *ReplayFile) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(replayfile.Table, replayfile.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, replayfile.UploaderTable, replayfile.UploaderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReplayFileClient) Hooks() []Hook {
	return c.hooks.ReplayFile
}

// Interceptors returns the client interceptors.
func (c *ReplayFileClient) Interceptors() []Interceptor {
	return c.inters.ReplayFile
}

func (c *ReplayFileClient) mutate(ctx context.Context, m *ReplayFileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ReplayFileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ReplayFileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ReplayFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ReplayFileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ReplayFile mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUploadedReplayFiles queries the uploaded_replay_files edge of a User.
func (c *UserClient) QueryUploadedReplayFiles(_m *User) *ReplayFileQuery {
	query := (&ReplayFileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(replayfile.Table, replayfile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.UploadedReplayFilesTable, user.UploadedReplayFilesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AnalyzerRaceMatchup, Game, GameDetail, Player, Ranking3v3, ReplayFile,
		User []ent.Hook
	}
	inters struct {
		AnalyzerRaceMatchup, Game, GameDetail, Player, Ranking3v3, ReplayFile,
		User []ent.Interceptor
	}
)
