// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareplays/ent/game"
	"github.com/xungwoo/stareplays/ent/gameanalysis"
	"github.com/xungwoo/stareplays/ent/gamedetail"
	"github.com/xungwoo/stareplays/ent/player"
	"github.com/xungwoo/stareplays/ent/predicate"
	"github.com/xungwoo/stareplays/ent/replayfile"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHost sets the "host" field.
func (_u *GameUpdate) SetHost(v string) *GameUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *GameUpdate) SetNillableHost(v *string) *GameUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *GameUpdate) SetStartTime(v time.Time) *GameUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *GameUpdate) SetNillableStartTime(v *time.Time) *GameUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetMapName sets the "map_name" field.
func (_u *GameUpdate) SetMapName(v string) *GameUpdate {
	_u.mutation.SetMapName(v)
	return _u
}

// SetNillableMapName sets the "map_name" field if the given value is not nil.
func (_u *GameUpdate) SetNillableMapName(v *string) *GameUpdate {
	if v != nil {
		_u.SetMapName(*v)
	}
	return _u
}

// ClearMapName clears the value of the "map_name" field.
func (_u *GameUpdate) ClearMapName() *GameUpdate {
	_u.mutation.ClearMapName()
	return _u
}

// SetMapWidth sets the "map_width" field.
func (_u *GameUpdate) SetMapWidth(v uint16) *GameUpdate {
	_u.mutation.ResetMapWidth()
	_u.mutation.SetMapWidth(v)
	return _u
}

// SetNillableMapWidth sets the "map_width" field if the given value is not nil.
func (_u *GameUpdate) SetNillableMapWidth(v *uint16) *GameUpdate {
	if v != nil {
		_u.SetMapWidth(*v)
	}
	return _u
}

// AddMapWidth adds value to the "map_width" field.
func (_u *GameUpdate) AddMapWidth(v int16) *GameUpdate {
	_u.mutation.AddMapWidth(v)
	return _u
}

// ClearMapWidth clears the value of the "map_width" field.
func (_u *GameUpdate) ClearMapWidth() *GameUpdate {
	_u.mutation.ClearMapWidth()
	return _u
}

// SetMapHeight sets the "map_height" field.
func (_u *GameUpdate) SetMapHeight(v uint16) *GameUpdate {
	_u.mutation.ResetMapHeight()
	_u.mutation.SetMapHeight(v)
	return _u
}

// SetNillableMapHeight sets the "map_height" field if the given value is not nil.
func (_u *GameUpdate) SetNillableMapHeight(v *uint16) *GameUpdate {
	if v != nil {
		_u.SetMapHeight(*v)
	}
	return _u
}

// AddMapHeight adds value to the "map_height" field.
func (_u *GameUpdate) AddMapHeight(v int16) *GameUpdate {
	_u.mutation.AddMapHeight(v)
	return _u
}

// ClearMapHeight clears the value of the "map_height" field.
func (_u *GameUpdate) ClearMapHeight() *GameUpdate {
	_u.mutation.ClearMapHeight()
	return _u
}

// SetGameLength sets the "game_length" field.
func (_u *GameUpdate) SetGameLength(v int) *GameUpdate {
	_u.mutation.ResetGameLength()
	_u.mutation.SetGameLength(v)
	return _u
}

// SetNillableGameLength sets the "game_length" field if the given value is not nil.
func (_u *GameUpdate) SetNillableGameLength(v *int) *GameUpdate {
	if v != nil {
		_u.SetGameLength(*v)
	}
	return _u
}

// AddGameLength adds value to the "game_length" field.
func (_u *GameUpdate) AddGameLength(v int) *GameUpdate {
	_u.mutation.AddGameLength(v)
	return _u
}

// ClearGameLength clears the value of the "game_length" field.
func (_u *GameUpdate) ClearGameLength() *GameUpdate {
	_u.mutation.ClearGameLength()
	return _u
}

// SetGameType sets the "game_type" field.
func (_u *GameUpdate) SetGameType(v string) *GameUpdate {
	_u.mutation.SetGameType(v)
	return _u
}

// SetNillableGameType sets the "game_type" field if the given value is not nil.
func (_u *GameUpdate) SetNillableGameType(v *string) *GameUpdate {
	if v != nil {
		_u.SetGameType(*v)
	}
	return _u
}

// ClearGameType clears the value of the "game_type" field.
func (_u *GameUpdate) ClearGameType() *GameUpdate {
	_u.mutation.ClearGameType()
	return _u
}

// SetGameSpeed sets the "game_speed" field.
func (_u *GameUpdate) SetGameSpeed(v string) *GameUpdate {
	_u.mutation.SetGameSpeed(v)
	return _u
}

// SetNillableGameSpeed sets the "game_speed" field if the given value is not nil.
func (_u *GameUpdate) SetNillableGameSpeed(v *string) *GameUpdate {
	if v != nil {
		_u.SetGameSpeed(*v)
	}
	return _u
}

// ClearGameSpeed clears the value of the "game_speed" field.
func (_u *GameUpdate) ClearGameSpeed() *GameUpdate {
	_u.mutation.ClearGameSpeed()
	return _u
}

// SetTitle sets the "title" field.
func (_u *GameUpdate) SetTitle(v string) *GameUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GameUpdate) SetNillableTitle(v *string) *GameUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *GameUpdate) ClearTitle() *GameUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetPlayerCount sets the "player_count" field.
func (_u *GameUpdate) SetPlayerCount(v int) *GameUpdate {
	_u.mutation.ResetPlayerCount()
	_u.mutation.SetPlayerCount(v)
	return _u
}

// SetNillablePlayerCount sets the "player_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePlayerCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetPlayerCount(*v)
	}
	return _u
}

// AddPlayerCount adds value to the "player_count" field.
func (_u *GameUpdate) AddPlayerCount(v int) *GameUpdate {
	_u.mutation.AddPlayerCount(v)
	return _u
}

// SetUploadCount sets the "upload_count" field.
func (_u *GameUpdate) SetUploadCount(v int) *GameUpdate {
	_u.mutation.ResetUploadCount()
	_u.mutation.SetUploadCount(v)
	return _u
}

// SetNillableUploadCount sets the "upload_count" field if the given value is not nil.
func (_u *GameUpdate) SetNillableUploadCount(v *int) *GameUpdate {
	if v != nil {
		_u.SetUploadCount(*v)
	}
	return _u
}

// AddUploadCount adds value to the "upload_count" field.
func (_u *GameUpdate) AddUploadCount(v int) *GameUpdate {
	_u.mutation.AddUploadCount(v)
	return _u
}

// SetWinnerTeam sets the "winner_team" field.
func (_u *GameUpdate) SetWinnerTeam(v uint8) *GameUpdate {
	_u.mutation.ResetWinnerTeam()
	_u.mutation.SetWinnerTeam(v)
	return _u
}

// SetNillableWinnerTeam sets the "winner_team" field if the given value is not nil.
func (_u *GameUpdate) SetNillableWinnerTeam(v *uint8) *GameUpdate {
	if v != nil {
		_u.SetWinnerTeam(*v)
	}
	return _u
}

// AddWinnerTeam adds value to the "winner_team" field.
func (_u *GameUpdate) AddWinnerTeam(v int8) *GameUpdate {
	_u.mutation.AddWinnerTeam(v)
	return _u
}

// SetSeasonLabel sets the "season_label" field.
func (_u *GameUpdate) SetSeasonLabel(v string) *GameUpdate {
	_u.mutation.SetSeasonLabel(v)
	return _u
}

// SetNillableSeasonLabel sets the "season_label" field if the given value is not nil.
func (_u *GameUpdate) SetNillableSeasonLabel(v *string) *GameUpdate {
	if v != nil {
		_u.SetSeasonLabel(*v)
	}
	return _u
}

// ClearSeasonLabel clears the value of the "season_label" field.
func (_u *GameUpdate) ClearSeasonLabel() *GameUpdate {
	_u.mutation.ClearSeasonLabel()
	return _u
}

// SetSeasonNo sets the "season_no" field.
func (_u *GameUpdate) SetSeasonNo(v int) *GameUpdate {
	_u.mutation.ResetSeasonNo()
	_u.mutation.SetSeasonNo(v)
	return _u
}

// SetNillableSeasonNo sets the "season_no" field if the given value is not nil.
func (_u *GameUpdate) SetNillableSeasonNo(v *int) *GameUpdate {
	if v != nil {
		_u.SetSeasonNo(*v)
	}
	return _u
}

// AddSeasonNo adds value to the "season_no" field.
func (_u *GameUpdate) AddSeasonNo(v int) *GameUpdate {
	_u.mutation.AddSeasonNo(v)
	return _u
}

// ClearSeasonNo clears the value of the "season_no" field.
func (_u *GameUpdate) ClearSeasonNo() *GameUpdate {
	_u.mutation.ClearSeasonNo()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdate) SetUpdatedAt(v time.Time) *GameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPlayerIDs adds the "players" edge to the Player entity by IDs.
func (_u *GameUpdate) AddPlayerIDs(ids ...int) *GameUpdate {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the Player entity.
func (_u *GameUpdate) AddPlayers(v ...*Player) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// AddReplayFileIDs adds the "replay_files" edge to the ReplayFile entity by IDs.
func (_u *GameUpdate) AddReplayFileIDs(ids ...int) *GameUpdate {
	_u.mutation.AddReplayFileIDs(ids...)
	return _u
}

// AddReplayFiles adds the "replay_files" edges to the ReplayFile entity.
func (_u *GameUpdate) AddReplayFiles(v ...*ReplayFile) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplayFileIDs(ids...)
}

// SetGameDetailID sets the "game_detail" edge to the GameDetail entity by ID.
func (_u *GameUpdate) SetGameDetailID(id int) *GameUpdate {
	_u.mutation.SetGameDetailID(id)
	return _u
}

// SetNillableGameDetailID sets the "game_detail" edge to the GameDetail entity by ID if the given value is not nil.
func (_u *GameUpdate) SetNillableGameDetailID(id *int) *GameUpdate {
	if id != nil {
		_u = _u.SetGameDetailID(*id)
	}
	return _u
}

// SetGameDetail sets the "game_detail" edge to the GameDetail entity.
func (_u *GameUpdate) SetGameDetail(v *GameDetail) *GameUpdate {
	return _u.SetGameDetailID(v.ID)
}

// SetAnalysisID sets the "analysis" edge to the GameAnalysis entity by ID.
func (_u *GameUpdate) SetAnalysisID(id int) *GameUpdate {
	_u.mutation.SetAnalysisID(id)
	return _u
}

// SetNillableAnalysisID sets the "analysis" edge to the GameAnalysis entity by ID if the given value is not nil.
func (_u *GameUpdate) SetNillableAnalysisID(id *int) *GameUpdate {
	if id != nil {
		_u = _u.SetAnalysisID(*id)
	}
	return _u
}

// SetAnalysis sets the "analysis" edge to the GameAnalysis entity.
func (_u *GameUpdate) SetAnalysis(v *GameAnalysis) *GameUpdate {
	return _u.SetAnalysisID(v.ID)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the Player entity.
func (_u *GameUpdate) ClearPlayers() *GameUpdate {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to Player entities by IDs.
func (_u *GameUpdate) RemovePlayerIDs(ids ...int) *GameUpdate {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to Player entities.
func (_u *GameUpdate) RemovePlayers(v ...*Player) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearReplayFiles clears all "replay_files" edges to the ReplayFile entity.
func (_u *GameUpdate) ClearReplayFiles() *GameUpdate {
	_u.mutation.ClearReplayFiles()
	return _u
}

// RemoveReplayFileIDs removes the "replay_files" edge to ReplayFile entities by IDs.
func (_u *GameUpdate) RemoveReplayFileIDs(ids ...int) *GameUpdate {
	_u.mutation.RemoveReplayFileIDs(ids...)
	return _u
}

// RemoveReplayFiles removes "replay_files" edges to ReplayFile entities.
func (_u *GameUpdate) RemoveReplayFiles(v ...*ReplayFile) *GameUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplayFileIDs(ids...)
}

// ClearGameDetail clears the "game_detail" edge to the GameDetail entity.
func (_u *GameUpdate) ClearGameDetail() *GameUpdate {
	_u.mutation.ClearGameDetail()
	return _u
}

// ClearAnalysis clears the "analysis" edge to the GameAnalysis entity.
func (_u *GameUpdate) ClearAnalysis() *GameUpdate {
	_u.mutation.ClearAnalysis()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.Host(); ok {
		if err := game.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Game.host": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(game.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(game.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MapName(); ok {
		_spec.SetField(game.FieldMapName, field.TypeString, value)
	}
	if _u.mutation.MapNameCleared() {
		_spec.ClearField(game.FieldMapName, field.TypeString)
	}
	if value, ok := _u.mutation.MapWidth(); ok {
		_spec.SetField(game.FieldMapWidth, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedMapWidth(); ok {
		_spec.AddField(game.FieldMapWidth, field.TypeUint16, value)
	}
	if _u.mutation.MapWidthCleared() {
		_spec.ClearField(game.FieldMapWidth, field.TypeUint16)
	}
	if value, ok := _u.mutation.MapHeight(); ok {
		_spec.SetField(game.FieldMapHeight, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedMapHeight(); ok {
		_spec.AddField(game.FieldMapHeight, field.TypeUint16, value)
	}
	if _u.mutation.MapHeightCleared() {
		_spec.ClearField(game.FieldMapHeight, field.TypeUint16)
	}
	if value, ok := _u.mutation.GameLength(); ok {
		_spec.SetField(game.FieldGameLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGameLength(); ok {
		_spec.AddField(game.FieldGameLength, field.TypeInt, value)
	}
	if _u.mutation.GameLengthCleared() {
		_spec.ClearField(game.FieldGameLength, field.TypeInt)
	}
	if value, ok := _u.mutation.GameType(); ok {
		_spec.SetField(game.FieldGameType, field.TypeString, value)
	}
	if _u.mutation.GameTypeCleared() {
		_spec.ClearField(game.FieldGameType, field.TypeString)
	}
	if value, ok := _u.mutation.GameSpeed(); ok {
		_spec.SetField(game.FieldGameSpeed, field.TypeString, value)
	}
	if _u.mutation.GameSpeedCleared() {
		_spec.ClearField(game.FieldGameSpeed, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(game.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(game.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.PlayerCount(); ok {
		_spec.SetField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerCount(); ok {
		_spec.AddField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadCount(); ok {
		_spec.SetField(game.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadCount(); ok {
		_spec.AddField(game.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WinnerTeam(); ok {
		_spec.SetField(game.FieldWinnerTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedWinnerTeam(); ok {
		_spec.AddField(game.FieldWinnerTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.SeasonLabel(); ok {
		_spec.SetField(game.FieldSeasonLabel, field.TypeString, value)
	}
	if _u.mutation.SeasonLabelCleared() {
		_spec.ClearField(game.FieldSeasonLabel, field.TypeString)
	}
	if value, ok := _u.mutation.SeasonNo(); ok {
		_spec.SetField(game.FieldSeasonNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeasonNo(); ok {
		_spec.AddField(game.FieldSeasonNo, field.TypeInt, value)
	}
	if _u.mutation.SeasonNoCleared() {
		_spec.ClearField(game.FieldSeasonNo, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ReplayFilesTable,
			Columns: []string{game.ReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReplayFilesIDs(); len(nodes) > 0 && !_u.mutation.ReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ReplayFilesTable,
			Columns: []string{game.ReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReplayFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ReplayFilesTable,
			Columns: []string{game.ReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GameDetailCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.GameDetailTable,
			Columns: []string{game.GameDetailColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamedetail.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameDetailIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.GameDetailTable,
			Columns: []string{game.GameDetailColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamedetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnalysisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.AnalysisTable,
			Columns: []string{game.AnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameanalysis.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnalysisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.AnalysisTable,
			Columns: []string{game.AnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameanalysis.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetHost sets the "host" field.
func (_u *GameUpdateOne) SetHost(v string) *GameUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableHost(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *GameUpdateOne) SetStartTime(v time.Time) *GameUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableStartTime(v *time.Time) *GameUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetMapName sets the "map_name" field.
func (_u *GameUpdateOne) SetMapName(v string) *GameUpdateOne {
	_u.mutation.SetMapName(v)
	return _u
}

// SetNillableMapName sets the "map_name" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableMapName(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetMapName(*v)
	}
	return _u
}

// ClearMapName clears the value of the "map_name" field.
func (_u *GameUpdateOne) ClearMapName() *GameUpdateOne {
	_u.mutation.ClearMapName()
	return _u
}

// SetMapWidth sets the "map_width" field.
func (_u *GameUpdateOne) SetMapWidth(v uint16) *GameUpdateOne {
	_u.mutation.ResetMapWidth()
	_u.mutation.SetMapWidth(v)
	return _u
}

// SetNillableMapWidth sets the "map_width" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableMapWidth(v *uint16) *GameUpdateOne {
	if v != nil {
		_u.SetMapWidth(*v)
	}
	return _u
}

// AddMapWidth adds value to the "map_width" field.
func (_u *GameUpdateOne) AddMapWidth(v int16) *GameUpdateOne {
	_u.mutation.AddMapWidth(v)
	return _u
}

// ClearMapWidth clears the value of the "map_width" field.
func (_u *GameUpdateOne) ClearMapWidth() *GameUpdateOne {
	_u.mutation.ClearMapWidth()
	return _u
}

// SetMapHeight sets the "map_height" field.
func (_u *GameUpdateOne) SetMapHeight(v uint16) *GameUpdateOne {
	_u.mutation.ResetMapHeight()
	_u.mutation.SetMapHeight(v)
	return _u
}

// SetNillableMapHeight sets the "map_height" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableMapHeight(v *uint16) *GameUpdateOne {
	if v != nil {
		_u.SetMapHeight(*v)
	}
	return _u
}

// AddMapHeight adds value to the "map_height" field.
func (_u *GameUpdateOne) AddMapHeight(v int16) *GameUpdateOne {
	_u.mutation.AddMapHeight(v)
	return _u
}

// ClearMapHeight clears the value of the "map_height" field.
func (_u *GameUpdateOne) ClearMapHeight() *GameUpdateOne {
	_u.mutation.ClearMapHeight()
	return _u
}

// SetGameLength sets the "game_length" field.
func (_u *GameUpdateOne) SetGameLength(v int) *GameUpdateOne {
	_u.mutation.ResetGameLength()
	_u.mutation.SetGameLength(v)
	return _u
}

// SetNillableGameLength sets the "game_length" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableGameLength(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetGameLength(*v)
	}
	return _u
}

// AddGameLength adds value to the "game_length" field.
func (_u *GameUpdateOne) AddGameLength(v int) *GameUpdateOne {
	_u.mutation.AddGameLength(v)
	return _u
}

// ClearGameLength clears the value of the "game_length" field.
func (_u *GameUpdateOne) ClearGameLength() *GameUpdateOne {
	_u.mutation.ClearGameLength()
	return _u
}

// SetGameType sets the "game_type" field.
func (_u *GameUpdateOne) SetGameType(v string) *GameUpdateOne {
	_u.mutation.SetGameType(v)
	return _u
}

// SetNillableGameType sets the "game_type" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableGameType(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetGameType(*v)
	}
	return _u
}

// ClearGameType clears the value of the "game_type" field.
func (_u *GameUpdateOne) ClearGameType() *GameUpdateOne {
	_u.mutation.ClearGameType()
	return _u
}

// SetGameSpeed sets the "game_speed" field.
func (_u *GameUpdateOne) SetGameSpeed(v string) *GameUpdateOne {
	_u.mutation.SetGameSpeed(v)
	return _u
}

// SetNillableGameSpeed sets the "game_speed" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableGameSpeed(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetGameSpeed(*v)
	}
	return _u
}

// ClearGameSpeed clears the value of the "game_speed" field.
func (_u *GameUpdateOne) ClearGameSpeed() *GameUpdateOne {
	_u.mutation.ClearGameSpeed()
	return _u
}

// SetTitle sets the "title" field.
func (_u *GameUpdateOne) SetTitle(v string) *GameUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableTitle(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *GameUpdateOne) ClearTitle() *GameUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetPlayerCount sets the "player_count" field.
func (_u *GameUpdateOne) SetPlayerCount(v int) *GameUpdateOne {
	_u.mutation.ResetPlayerCount()
	_u.mutation.SetPlayerCount(v)
	return _u
}

// SetNillablePlayerCount sets the "player_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePlayerCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetPlayerCount(*v)
	}
	return _u
}

// AddPlayerCount adds value to the "player_count" field.
func (_u *GameUpdateOne) AddPlayerCount(v int) *GameUpdateOne {
	_u.mutation.AddPlayerCount(v)
	return _u
}

// SetUploadCount sets the "upload_count" field.
func (_u *GameUpdateOne) SetUploadCount(v int) *GameUpdateOne {
	_u.mutation.ResetUploadCount()
	_u.mutation.SetUploadCount(v)
	return _u
}

// SetNillableUploadCount sets the "upload_count" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableUploadCount(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetUploadCount(*v)
	}
	return _u
}

// AddUploadCount adds value to the "upload_count" field.
func (_u *GameUpdateOne) AddUploadCount(v int) *GameUpdateOne {
	_u.mutation.AddUploadCount(v)
	return _u
}

// SetWinnerTeam sets the "winner_team" field.
func (_u *GameUpdateOne) SetWinnerTeam(v uint8) *GameUpdateOne {
	_u.mutation.ResetWinnerTeam()
	_u.mutation.SetWinnerTeam(v)
	return _u
}

// SetNillableWinnerTeam sets the "winner_team" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableWinnerTeam(v *uint8) *GameUpdateOne {
	if v != nil {
		_u.SetWinnerTeam(*v)
	}
	return _u
}

// AddWinnerTeam adds value to the "winner_team" field.
func (_u *GameUpdateOne) AddWinnerTeam(v int8) *GameUpdateOne {
	_u.mutation.AddWinnerTeam(v)
	return _u
}

// SetSeasonLabel sets the "season_label" field.
func (_u *GameUpdateOne) SetSeasonLabel(v string) *GameUpdateOne {
	_u.mutation.SetSeasonLabel(v)
	return _u
}

// SetNillableSeasonLabel sets the "season_label" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableSeasonLabel(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetSeasonLabel(*v)
	}
	return _u
}

// ClearSeasonLabel clears the value of the "season_label" field.
func (_u *GameUpdateOne) ClearSeasonLabel() *GameUpdateOne {
	_u.mutation.ClearSeasonLabel()
	return _u
}

// SetSeasonNo sets the "season_no" field.
func (_u *GameUpdateOne) SetSeasonNo(v int) *GameUpdateOne {
	_u.mutation.ResetSeasonNo()
	_u.mutation.SetSeasonNo(v)
	return _u
}

// SetNillableSeasonNo sets the "season_no" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableSeasonNo(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetSeasonNo(*v)
	}
	return _u
}

// AddSeasonNo adds value to the "season_no" field.
func (_u *GameUpdateOne) AddSeasonNo(v int) *GameUpdateOne {
	_u.mutation.AddSeasonNo(v)
	return _u
}

// ClearSeasonNo clears the value of the "season_no" field.
func (_u *GameUpdateOne) ClearSeasonNo() *GameUpdateOne {
	_u.mutation.ClearSeasonNo()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameUpdateOne) SetUpdatedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddPlayerIDs adds the "players" edge to the Player entity by IDs.
func (_u *GameUpdateOne) AddPlayerIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddPlayerIDs(ids...)
	return _u
}

// AddPlayers adds the "players" edges to the Player entity.
func (_u *GameUpdateOne) AddPlayers(v ...*Player) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerIDs(ids...)
}

// AddReplayFileIDs adds the "replay_files" edge to the ReplayFile entity by IDs.
func (_u *GameUpdateOne) AddReplayFileIDs(ids ...int) *GameUpdateOne {
	_u.mutation.AddReplayFileIDs(ids...)
	return _u
}

// AddReplayFiles adds the "replay_files" edges to the ReplayFile entity.
func (_u *GameUpdateOne) AddReplayFiles(v ...*ReplayFile) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplayFileIDs(ids...)
}

// SetGameDetailID sets the "game_detail" edge to the GameDetail entity by ID.
func (_u *GameUpdateOne) SetGameDetailID(id int) *GameUpdateOne {
	_u.mutation.SetGameDetailID(id)
	return _u
}

// SetNillableGameDetailID sets the "game_detail" edge to the GameDetail entity by ID if the given value is not nil.
func (_u *GameUpdateOne) SetNillableGameDetailID(id *int) *GameUpdateOne {
	if id != nil {
		_u = _u.SetGameDetailID(*id)
	}
	return _u
}

// SetGameDetail sets the "game_detail" edge to the GameDetail entity.
func (_u *GameUpdateOne) SetGameDetail(v *GameDetail) *GameUpdateOne {
	return _u.SetGameDetailID(v.ID)
}

// SetAnalysisID sets the "analysis" edge to the GameAnalysis entity by ID.
func (_u *GameUpdateOne) SetAnalysisID(id int) *GameUpdateOne {
	_u.mutation.SetAnalysisID(id)
	return _u
}

// SetNillableAnalysisID sets the "analysis" edge to the GameAnalysis entity by ID if the given value is not nil.
func (_u *GameUpdateOne) SetNillableAnalysisID(id *int) *GameUpdateOne {
	if id != nil {
		_u = _u.SetAnalysisID(*id)
	}
	return _u
}

// SetAnalysis sets the "analysis" edge to the GameAnalysis entity.
func (_u *GameUpdateOne) SetAnalysis(v *GameAnalysis) *GameUpdateOne {
	return _u.SetAnalysisID(v.ID)
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// ClearPlayers clears all "players" edges to the Player entity.
func (_u *GameUpdateOne) ClearPlayers() *GameUpdateOne {
	_u.mutation.ClearPlayers()
	return _u
}

// RemovePlayerIDs removes the "players" edge to Player entities by IDs.
func (_u *GameUpdateOne) RemovePlayerIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemovePlayerIDs(ids...)
	return _u
}

// RemovePlayers removes "players" edges to Player entities.
func (_u *GameUpdateOne) RemovePlayers(v ...*Player) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerIDs(ids...)
}

// ClearReplayFiles clears all "replay_files" edges to the ReplayFile entity.
func (_u *GameUpdateOne) ClearReplayFiles() *GameUpdateOne {
	_u.mutation.ClearReplayFiles()
	return _u
}

// RemoveReplayFileIDs removes the "replay_files" edge to ReplayFile entities by IDs.
func (_u *GameUpdateOne) RemoveReplayFileIDs(ids ...int) *GameUpdateOne {
	_u.mutation.RemoveReplayFileIDs(ids...)
	return _u
}

// RemoveReplayFiles removes "replay_files" edges to ReplayFile entities.
func (_u *GameUpdateOne) RemoveReplayFiles(v ...*ReplayFile) *GameUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplayFileIDs(ids...)
}

// ClearGameDetail clears the "game_detail" edge to the GameDetail entity.
func (_u *GameUpdateOne) ClearGameDetail() *GameUpdateOne {
	_u.mutation.ClearGameDetail()
	return _u
}

// ClearAnalysis clears the "analysis" edge to the GameAnalysis entity.
func (_u *GameUpdateOne) ClearAnalysis() *GameUpdateOne {
	_u.mutation.ClearAnalysis()
	return _u
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.Host(); ok {
		if err := game.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Game.host": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(game.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(game.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MapName(); ok {
		_spec.SetField(game.FieldMapName, field.TypeString, value)
	}
	if _u.mutation.MapNameCleared() {
		_spec.ClearField(game.FieldMapName, field.TypeString)
	}
	if value, ok := _u.mutation.MapWidth(); ok {
		_spec.SetField(game.FieldMapWidth, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedMapWidth(); ok {
		_spec.AddField(game.FieldMapWidth, field.TypeUint16, value)
	}
	if _u.mutation.MapWidthCleared() {
		_spec.ClearField(game.FieldMapWidth, field.TypeUint16)
	}
	if value, ok := _u.mutation.MapHeight(); ok {
		_spec.SetField(game.FieldMapHeight, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedMapHeight(); ok {
		_spec.AddField(game.FieldMapHeight, field.TypeUint16, value)
	}
	if _u.mutation.MapHeightCleared() {
		_spec.ClearField(game.FieldMapHeight, field.TypeUint16)
	}
	if value, ok := _u.mutation.GameLength(); ok {
		_spec.SetField(game.FieldGameLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGameLength(); ok {
		_spec.AddField(game.FieldGameLength, field.TypeInt, value)
	}
	if _u.mutation.GameLengthCleared() {
		_spec.ClearField(game.FieldGameLength, field.TypeInt)
	}
	if value, ok := _u.mutation.GameType(); ok {
		_spec.SetField(game.FieldGameType, field.TypeString, value)
	}
	if _u.mutation.GameTypeCleared() {
		_spec.ClearField(game.FieldGameType, field.TypeString)
	}
	if value, ok := _u.mutation.GameSpeed(); ok {
		_spec.SetField(game.FieldGameSpeed, field.TypeString, value)
	}
	if _u.mutation.GameSpeedCleared() {
		_spec.ClearField(game.FieldGameSpeed, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(game.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(game.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.PlayerCount(); ok {
		_spec.SetField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlayerCount(); ok {
		_spec.AddField(game.FieldPlayerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UploadCount(); ok {
		_spec.SetField(game.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadCount(); ok {
		_spec.AddField(game.FieldUploadCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WinnerTeam(); ok {
		_spec.SetField(game.FieldWinnerTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedWinnerTeam(); ok {
		_spec.AddField(game.FieldWinnerTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.SeasonLabel(); ok {
		_spec.SetField(game.FieldSeasonLabel, field.TypeString, value)
	}
	if _u.mutation.SeasonLabelCleared() {
		_spec.ClearField(game.FieldSeasonLabel, field.TypeString)
	}
	if value, ok := _u.mutation.SeasonNo(); ok {
		_spec.SetField(game.FieldSeasonNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeasonNo(); ok {
		_spec.AddField(game.FieldSeasonNo, field.TypeInt, value)
	}
	if _u.mutation.SeasonNoCleared() {
		_spec.ClearField(game.FieldSeasonNo, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayersIDs(); len(nodes) > 0 && !_u.mutation.PlayersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.PlayersTable,
			Columns: []string{game.PlayersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ReplayFilesTable,
			Columns: []string{game.ReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReplayFilesIDs(); len(nodes) > 0 && !_u.mutation.ReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ReplayFilesTable,
			Columns: []string{game.ReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReplayFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   game.ReplayFilesTable,
			Columns: []string{game.ReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GameDetailCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.GameDetailTable,
			Columns: []string{game.GameDetailColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamedetail.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameDetailIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.GameDetailTable,
			Columns: []string{game.GameDetailColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gamedetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnalysisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.AnalysisTable,
			Columns: []string{game.AnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameanalysis.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnalysisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   game.AnalysisTable,
			Columns: []string{game.AnalysisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gameanalysis.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
