// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/xungwoo/stareplays/ent/game"
	"github.com/xungwoo/stareplays/ent/gamedetail"
	"github.com/xungwoo/stareplays/ent/schema"
)

// GameDetail is the model entity for the GameDetail schema.
type GameDetail struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Per-player APM timeline data
	ApmTimeline []schema.PlayerAPMTimeline `json:"apm_timeline,omitempty"`
	// Per-player raw command events
	BuildOrders []schema.PlayerBuildOrder `json:"build_orders,omitempty"`
	// Per-player compressed meaningful build orders
	CompressedBuildOrders []schema.PlayerBuildOrder `json:"compressed_build_orders,omitempty"`
	// In-game chat messages
	ChatMessages []schema.ChatMessage `json:"chat_messages,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameDetailQuery when eager-loading is set.
	Edges            GameDetailEdges `json:"edges"`
	game_game_detail *int
	selectValues     sql.SelectValues
}

// GameDetailEdges holds the relations/edges for other nodes in the graph.
type GameDetailEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameDetailEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GameDetail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gamedetail.FieldApmTimeline, gamedetail.FieldBuildOrders, gamedetail.FieldCompressedBuildOrders, gamedetail.FieldChatMessages:
			values[i] = new([]byte)
		case gamedetail.FieldID:
			values[i] = new(sql.NullInt64)
		case gamedetail.ForeignKeys[0]: // game_game_detail
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GameDetail fields.
func (_m *GameDetail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gamedetail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gamedetail.FieldApmTimeline:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field apm_timeline", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ApmTimeline); err != nil {
					return fmt.Errorf("unmarshal field apm_timeline: %w", err)
				}
			}
		case gamedetail.FieldBuildOrders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field build_orders", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BuildOrders); err != nil {
					return fmt.Errorf("unmarshal field build_orders: %w", err)
				}
			}
		case gamedetail.FieldCompressedBuildOrders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field compressed_build_orders", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CompressedBuildOrders); err != nil {
					return fmt.Errorf("unmarshal field compressed_build_orders: %w", err)
				}
			}
		case gamedetail.FieldChatMessages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field chat_messages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ChatMessages); err != nil {
					return fmt.Errorf("unmarshal field chat_messages: %w", err)
				}
			}
		case gamedetail.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field game_game_detail", value)
			} else if value.Valid {
				_m.game_game_detail = new(int)
				*_m.game_game_detail = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GameDetail.
// This includes values selected through modifiers, order, etc.
func (_m *GameDetail) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the GameDetail entity.
func (_m *GameDetail) QueryGame() *GameQuery {
	return NewGameDetailClient(_m.config).QueryGame(_m)
}

// Update returns a builder for updating this GameDetail.
// Note that you need to call GameDetail.Unwrap() before calling this method if this GameDetail
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GameDetail) Update() *GameDetailUpdateOne {
	return NewGameDetailClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GameDetail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GameDetail) Unwrap() *GameDetail {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GameDetail is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GameDetail) String() string {
	var builder strings.Builder
	builder.WriteString("GameDetail(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("apm_timeline=")
	builder.WriteString(fmt.Sprintf("%v", _m.ApmTimeline))
	builder.WriteString(", ")
	builder.WriteString("build_orders=")
	builder.WriteString(fmt.Sprintf("%v", _m.BuildOrders))
	builder.WriteString(", ")
	builder.WriteString("compressed_build_orders=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompressedBuildOrders))
	builder.WriteString(", ")
	builder.WriteString("chat_messages=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatMessages))
	builder.WriteByte(')')
	return builder.String()
}

// GameDetails is a parsable slice of GameDetail.
type GameDetails []*GameDetail
