// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareplays/ent/gameanalysis"
	"github.com/xungwoo/stareplays/ent/predicate"
)

// GameAnalysisDelete is the builder for deleting a GameAnalysis entity.
type GameAnalysisDelete struct {
	config
	hooks    []Hook
	mutation *GameAnalysisMutation
}

// Where appends a list predicates to the GameAnalysisDelete builder.
func (_d *GameAnalysisDelete) Where(ps ...predicate.GameAnalysis) *GameAnalysisDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GameAnalysisDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GameAnalysisDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GameAnalysisDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gameanalysis.Table, sqlgraph.NewFieldSpec(gameanalysis.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GameAnalysisDeleteOne is the builder for deleting a single GameAnalysis entity.
type GameAnalysisDeleteOne struct {
	_d *GameAnalysisDelete
}

// Where appends a list predicates to the GameAnalysisDelete builder.
func (_d *GameAnalysisDeleteOne) Where(ps ...predicate.GameAnalysis) *GameAnalysisDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GameAnalysisDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gameanalysis.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GameAnalysisDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
