// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareplays/ent/game"
	"github.com/xungwoo/stareplays/ent/player"
	"github.com/xungwoo/stareplays/ent/predicate"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PlayerUpdate) SetName(v string) *PlayerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableName(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRace sets the "race" field.
func (_u *PlayerUpdate) SetRace(v string) *PlayerUpdate {
	_u.mutation.SetRace(v)
	return _u
}

// SetNillableRace sets the "race" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableRace(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetRace(*v)
	}
	return _u
}

// SetTeam sets the "team" field.
func (_u *PlayerUpdate) SetTeam(v uint8) *PlayerUpdate {
	_u.mutation.ResetTeam()
	_u.mutation.SetTeam(v)
	return _u
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableTeam(v *uint8) *PlayerUpdate {
	if v != nil {
		_u.SetTeam(*v)
	}
	return _u
}

// AddTeam adds value to the "team" field.
func (_u *PlayerUpdate) AddTeam(v int8) *PlayerUpdate {
	_u.mutation.AddTeam(v)
	return _u
}

// SetColor sets the "color" field.
func (_u *PlayerUpdate) SetColor(v string) *PlayerUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableColor(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *PlayerUpdate) ClearColor() *PlayerUpdate {
	_u.mutation.ClearColor()
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *PlayerUpdate) SetPlayerID(v uint8) *PlayerUpdate {
	_u.mutation.ResetPlayerID()
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePlayerID(v *uint8) *PlayerUpdate {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// AddPlayerID adds value to the "player_id" field.
func (_u *PlayerUpdate) AddPlayerID(v int8) *PlayerUpdate {
	_u.mutation.AddPlayerID(v)
	return _u
}

// SetApm sets the "apm" field.
func (_u *PlayerUpdate) SetApm(v int32) *PlayerUpdate {
	_u.mutation.ResetApm()
	_u.mutation.SetApm(v)
	return _u
}

// SetNillableApm sets the "apm" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableApm(v *int32) *PlayerUpdate {
	if v != nil {
		_u.SetApm(*v)
	}
	return _u
}

// AddApm adds value to the "apm" field.
func (_u *PlayerUpdate) AddApm(v int32) *PlayerUpdate {
	_u.mutation.AddApm(v)
	return _u
}

// ClearApm clears the value of the "apm" field.
func (_u *PlayerUpdate) ClearApm() *PlayerUpdate {
	_u.mutation.ClearApm()
	return _u
}

// SetEapm sets the "eapm" field.
func (_u *PlayerUpdate) SetEapm(v int32) *PlayerUpdate {
	_u.mutation.ResetEapm()
	_u.mutation.SetEapm(v)
	return _u
}

// SetNillableEapm sets the "eapm" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableEapm(v *int32) *PlayerUpdate {
	if v != nil {
		_u.SetEapm(*v)
	}
	return _u
}

// AddEapm adds value to the "eapm" field.
func (_u *PlayerUpdate) AddEapm(v int32) *PlayerUpdate {
	_u.mutation.AddEapm(v)
	return _u
}

// ClearEapm clears the value of the "eapm" field.
func (_u *PlayerUpdate) ClearEapm() *PlayerUpdate {
	_u.mutation.ClearEapm()
	return _u
}

// SetCmdCount sets the "cmd_count" field.
func (_u *PlayerUpdate) SetCmdCount(v uint32) *PlayerUpdate {
	_u.mutation.ResetCmdCount()
	_u.mutation.SetCmdCount(v)
	return _u
}

// SetNillableCmdCount sets the "cmd_count" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableCmdCount(v *uint32) *PlayerUpdate {
	if v != nil {
		_u.SetCmdCount(*v)
	}
	return _u
}

// AddCmdCount adds value to the "cmd_count" field.
func (_u *PlayerUpdate) AddCmdCount(v int32) *PlayerUpdate {
	_u.mutation.AddCmdCount(v)
	return _u
}

// ClearCmdCount clears the value of the "cmd_count" field.
func (_u *PlayerUpdate) ClearCmdCount() *PlayerUpdate {
	_u.mutation.ClearCmdCount()
	return _u
}

// SetEffectiveCmdCount sets the "effective_cmd_count" field.
func (_u *PlayerUpdate) SetEffectiveCmdCount(v uint32) *PlayerUpdate {
	_u.mutation.ResetEffectiveCmdCount()
	_u.mutation.SetEffectiveCmdCount(v)
	return _u
}

// SetNillableEffectiveCmdCount sets the "effective_cmd_count" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableEffectiveCmdCount(v *uint32) *PlayerUpdate {
	if v != nil {
		_u.SetEffectiveCmdCount(*v)
	}
	return _u
}

// AddEffectiveCmdCount adds value to the "effective_cmd_count" field.
func (_u *PlayerUpdate) AddEffectiveCmdCount(v int32) *PlayerUpdate {
	_u.mutation.AddEffectiveCmdCount(v)
	return _u
}

// ClearEffectiveCmdCount clears the value of the "effective_cmd_count" field.
func (_u *PlayerUpdate) ClearEffectiveCmdCount() *PlayerUpdate {
	_u.mutation.ClearEffectiveCmdCount()
	return _u
}

// SetStartLocationX sets the "start_location_x" field.
func (_u *PlayerUpdate) SetStartLocationX(v uint16) *PlayerUpdate {
	_u.mutation.ResetStartLocationX()
	_u.mutation.SetStartLocationX(v)
	return _u
}

// SetNillableStartLocationX sets the "start_location_x" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableStartLocationX(v *uint16) *PlayerUpdate {
	if v != nil {
		_u.SetStartLocationX(*v)
	}
	return _u
}

// AddStartLocationX adds value to the "start_location_x" field.
func (_u *PlayerUpdate) AddStartLocationX(v int16) *PlayerUpdate {
	_u.mutation.AddStartLocationX(v)
	return _u
}

// ClearStartLocationX clears the value of the "start_location_x" field.
func (_u *PlayerUpdate) ClearStartLocationX() *PlayerUpdate {
	_u.mutation.ClearStartLocationX()
	return _u
}

// SetStartLocationY sets the "start_location_y" field.
func (_u *PlayerUpdate) SetStartLocationY(v uint16) *PlayerUpdate {
	_u.mutation.ResetStartLocationY()
	_u.mutation.SetStartLocationY(v)
	return _u
}

// SetNillableStartLocationY sets the "start_location_y" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableStartLocationY(v *uint16) *PlayerUpdate {
	if v != nil {
		_u.SetStartLocationY(*v)
	}
	return _u
}

// AddStartLocationY adds value to the "start_location_y" field.
func (_u *PlayerUpdate) AddStartLocationY(v int16) *PlayerUpdate {
	_u.mutation.AddStartLocationY(v)
	return _u
}

// ClearStartLocationY clears the value of the "start_location_y" field.
func (_u *PlayerUpdate) ClearStartLocationY() *PlayerUpdate {
	_u.mutation.ClearStartLocationY()
	return _u
}

// SetStartDirection sets the "start_direction" field.
func (_u *PlayerUpdate) SetStartDirection(v int32) *PlayerUpdate {
	_u.mutation.ResetStartDirection()
	_u.mutation.SetStartDirection(v)
	return _u
}

// SetNillableStartDirection sets the "start_direction" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableStartDirection(v *int32) *PlayerUpdate {
	if v != nil {
		_u.SetStartDirection(*v)
	}
	return _u
}

// AddStartDirection adds value to the "start_direction" field.
func (_u *PlayerUpdate) AddStartDirection(v int32) *PlayerUpdate {
	_u.mutation.AddStartDirection(v)
	return _u
}

// ClearStartDirection clears the value of the "start_direction" field.
func (_u *PlayerUpdate) ClearStartDirection() *PlayerUpdate {
	_u.mutation.ClearStartDirection()
	return _u
}

// SetRedundancy sets the "redundancy" field.
func (_u *PlayerUpdate) SetRedundancy(v int) *PlayerUpdate {
	_u.mutation.ResetRedundancy()
	_u.mutation.SetRedundancy(v)
	return _u
}

// SetNillableRedundancy sets the "redundancy" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableRedundancy(v *int) *PlayerUpdate {
	if v != nil {
		_u.SetRedundancy(*v)
	}
	return _u
}

// AddRedundancy adds value to the "redundancy" field.
func (_u *PlayerUpdate) AddRedundancy(v int) *PlayerUpdate {
	_u.mutation.AddRedundancy(v)
	return _u
}

// ClearRedundancy clears the value of the "redundancy" field.
func (_u *PlayerUpdate) ClearRedundancy() *PlayerUpdate {
	_u.mutation.ClearRedundancy()
	return _u
}

// SetIsWinner sets the "is_winner" field.
func (_u *PlayerUpdate) SetIsWinner(v bool) *PlayerUpdate {
	_u.mutation.SetIsWinner(v)
	return _u
}

// SetNillableIsWinner sets the "is_winner" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableIsWinner(v *bool) *PlayerUpdate {
	if v != nil {
		_u.SetIsWinner(*v)
	}
	return _u
}

// SetIsRandomSelected sets the "is_random_selected" field.
func (_u *PlayerUpdate) SetIsRandomSelected(v bool) *PlayerUpdate {
	_u.mutation.SetIsRandomSelected(v)
	return _u
}

// SetNillableIsRandomSelected sets the "is_random_selected" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableIsRandomSelected(v *bool) *PlayerUpdate {
	if v != nil {
		_u.SetIsRandomSelected(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *PlayerUpdate) SetResult(v string) *PlayerUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillableResult(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_u *PlayerUpdate) SetGameID(id int) *PlayerUpdate {
	_u.mutation.SetGameID(id)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *PlayerUpdate) SetGame(v *Game) *PlayerUpdate {
	return _u.SetGameID(v.ID)
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdate) Mutation() *PlayerMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *PlayerUpdate) ClearGame() *PlayerUpdate {
	_u.mutation.ClearGame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := player.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Player.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Race(); ok {
		if err := player.RaceValidator(v); err != nil {
			return &ValidationError{Name: "race", err: fmt.Errorf(`ent: validator failed for field "Player.race": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Player.game"`)
	}
	return nil
}

func (_u *PlayerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(player.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Race(); ok {
		_spec.SetField(player.FieldRace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Team(); ok {
		_spec.SetField(player.FieldTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedTeam(); ok {
		_spec.AddField(player.FieldTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(player.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(player.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedPlayerID(); ok {
		_spec.AddField(player.FieldPlayerID, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Apm(); ok {
		_spec.SetField(player.FieldApm, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedApm(); ok {
		_spec.AddField(player.FieldApm, field.TypeInt32, value)
	}
	if _u.mutation.ApmCleared() {
		_spec.ClearField(player.FieldApm, field.TypeInt32)
	}
	if value, ok := _u.mutation.Eapm(); ok {
		_spec.SetField(player.FieldEapm, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedEapm(); ok {
		_spec.AddField(player.FieldEapm, field.TypeInt32, value)
	}
	if _u.mutation.EapmCleared() {
		_spec.ClearField(player.FieldEapm, field.TypeInt32)
	}
	if value, ok := _u.mutation.CmdCount(); ok {
		_spec.SetField(player.FieldCmdCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCmdCount(); ok {
		_spec.AddField(player.FieldCmdCount, field.TypeUint32, value)
	}
	if _u.mutation.CmdCountCleared() {
		_spec.ClearField(player.FieldCmdCount, field.TypeUint32)
	}
	if value, ok := _u.mutation.EffectiveCmdCount(); ok {
		_spec.SetField(player.FieldEffectiveCmdCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedEffectiveCmdCount(); ok {
		_spec.AddField(player.FieldEffectiveCmdCount, field.TypeUint32, value)
	}
	if _u.mutation.EffectiveCmdCountCleared() {
		_spec.ClearField(player.FieldEffectiveCmdCount, field.TypeUint32)
	}
	if value, ok := _u.mutation.StartLocationX(); ok {
		_spec.SetField(player.FieldStartLocationX, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedStartLocationX(); ok {
		_spec.AddField(player.FieldStartLocationX, field.TypeUint16, value)
	}
	if _u.mutation.StartLocationXCleared() {
		_spec.ClearField(player.FieldStartLocationX, field.TypeUint16)
	}
	if value, ok := _u.mutation.StartLocationY(); ok {
		_spec.SetField(player.FieldStartLocationY, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedStartLocationY(); ok {
		_spec.AddField(player.FieldStartLocationY, field.TypeUint16, value)
	}
	if _u.mutation.StartLocationYCleared() {
		_spec.ClearField(player.FieldStartLocationY, field.TypeUint16)
	}
	if value, ok := _u.mutation.StartDirection(); ok {
		_spec.SetField(player.FieldStartDirection, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStartDirection(); ok {
		_spec.AddField(player.FieldStartDirection, field.TypeInt32, value)
	}
	if _u.mutation.StartDirectionCleared() {
		_spec.ClearField(player.FieldStartDirection, field.TypeInt32)
	}
	if value, ok := _u.mutation.Redundancy(); ok {
		_spec.SetField(player.FieldRedundancy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedundancy(); ok {
		_spec.AddField(player.FieldRedundancy, field.TypeInt, value)
	}
	if _u.mutation.RedundancyCleared() {
		_spec.ClearField(player.FieldRedundancy, field.TypeInt)
	}
	if value, ok := _u.mutation.IsWinner(); ok {
		_spec.SetField(player.FieldIsWinner, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsRandomSelected(); ok {
		_spec.SetField(player.FieldIsRandomSelected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(player.FieldResult, field.TypeString, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.GameTable,
			Columns: []string{player.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.GameTable,
			Columns: []string{player.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetName sets the "name" field.
func (_u *PlayerUpdateOne) SetName(v string) *PlayerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableName(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRace sets the "race" field.
func (_u *PlayerUpdateOne) SetRace(v string) *PlayerUpdateOne {
	_u.mutation.SetRace(v)
	return _u
}

// SetNillableRace sets the "race" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableRace(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetRace(*v)
	}
	return _u
}

// SetTeam sets the "team" field.
func (_u *PlayerUpdateOne) SetTeam(v uint8) *PlayerUpdateOne {
	_u.mutation.ResetTeam()
	_u.mutation.SetTeam(v)
	return _u
}

// SetNillableTeam sets the "team" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableTeam(v *uint8) *PlayerUpdateOne {
	if v != nil {
		_u.SetTeam(*v)
	}
	return _u
}

// AddTeam adds value to the "team" field.
func (_u *PlayerUpdateOne) AddTeam(v int8) *PlayerUpdateOne {
	_u.mutation.AddTeam(v)
	return _u
}

// SetColor sets the "color" field.
func (_u *PlayerUpdateOne) SetColor(v string) *PlayerUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableColor(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *PlayerUpdateOne) ClearColor() *PlayerUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *PlayerUpdateOne) SetPlayerID(v uint8) *PlayerUpdateOne {
	_u.mutation.ResetPlayerID()
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePlayerID(v *uint8) *PlayerUpdateOne {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// AddPlayerID adds value to the "player_id" field.
func (_u *PlayerUpdateOne) AddPlayerID(v int8) *PlayerUpdateOne {
	_u.mutation.AddPlayerID(v)
	return _u
}

// SetApm sets the "apm" field.
func (_u *PlayerUpdateOne) SetApm(v int32) *PlayerUpdateOne {
	_u.mutation.ResetApm()
	_u.mutation.SetApm(v)
	return _u
}

// SetNillableApm sets the "apm" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableApm(v *int32) *PlayerUpdateOne {
	if v != nil {
		_u.SetApm(*v)
	}
	return _u
}

// AddApm adds value to the "apm" field.
func (_u *PlayerUpdateOne) AddApm(v int32) *PlayerUpdateOne {
	_u.mutation.AddApm(v)
	return _u
}

// ClearApm clears the value of the "apm" field.
func (_u *PlayerUpdateOne) ClearApm() *PlayerUpdateOne {
	_u.mutation.ClearApm()
	return _u
}

// SetEapm sets the "eapm" field.
func (_u *PlayerUpdateOne) SetEapm(v int32) *PlayerUpdateOne {
	_u.mutation.ResetEapm()
	_u.mutation.SetEapm(v)
	return _u
}

// SetNillableEapm sets the "eapm" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableEapm(v *int32) *PlayerUpdateOne {
	if v != nil {
		_u.SetEapm(*v)
	}
	return _u
}

// AddEapm adds value to the "eapm" field.
func (_u *PlayerUpdateOne) AddEapm(v int32) *PlayerUpdateOne {
	_u.mutation.AddEapm(v)
	return _u
}

// ClearEapm clears the value of the "eapm" field.
func (_u *PlayerUpdateOne) ClearEapm() *PlayerUpdateOne {
	_u.mutation.ClearEapm()
	return _u
}

// SetCmdCount sets the "cmd_count" field.
func (_u *PlayerUpdateOne) SetCmdCount(v uint32) *PlayerUpdateOne {
	_u.mutation.ResetCmdCount()
	_u.mutation.SetCmdCount(v)
	return _u
}

// SetNillableCmdCount sets the "cmd_count" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableCmdCount(v *uint32) *PlayerUpdateOne {
	if v != nil {
		_u.SetCmdCount(*v)
	}
	return _u
}

// AddCmdCount adds value to the "cmd_count" field.
func (_u *PlayerUpdateOne) AddCmdCount(v int32) *PlayerUpdateOne {
	_u.mutation.AddCmdCount(v)
	return _u
}

// ClearCmdCount clears the value of the "cmd_count" field.
func (_u *PlayerUpdateOne) ClearCmdCount() *PlayerUpdateOne {
	_u.mutation.ClearCmdCount()
	return _u
}

// SetEffectiveCmdCount sets the "effective_cmd_count" field.
func (_u *PlayerUpdateOne) SetEffectiveCmdCount(v uint32) *PlayerUpdateOne {
	_u.mutation.ResetEffectiveCmdCount()
	_u.mutation.SetEffectiveCmdCount(v)
	return _u
}

// SetNillableEffectiveCmdCount sets the "effective_cmd_count" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableEffectiveCmdCount(v *uint32) *PlayerUpdateOne {
	if v != nil {
		_u.SetEffectiveCmdCount(*v)
	}
	return _u
}

// AddEffectiveCmdCount adds value to the "effective_cmd_count" field.
func (_u *PlayerUpdateOne) AddEffectiveCmdCount(v int32) *PlayerUpdateOne {
	_u.mutation.AddEffectiveCmdCount(v)
	return _u
}

// ClearEffectiveCmdCount clears the value of the "effective_cmd_count" field.
func (_u *PlayerUpdateOne) ClearEffectiveCmdCount() *PlayerUpdateOne {
	_u.mutation.ClearEffectiveCmdCount()
	return _u
}

// SetStartLocationX sets the "start_location_x" field.
func (_u *PlayerUpdateOne) SetStartLocationX(v uint16) *PlayerUpdateOne {
	_u.mutation.ResetStartLocationX()
	_u.mutation.SetStartLocationX(v)
	return _u
}

// SetNillableStartLocationX sets the "start_location_x" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableStartLocationX(v *uint16) *PlayerUpdateOne {
	if v != nil {
		_u.SetStartLocationX(*v)
	}
	return _u
}

// AddStartLocationX adds value to the "start_location_x" field.
func (_u *PlayerUpdateOne) AddStartLocationX(v int16) *PlayerUpdateOne {
	_u.mutation.AddStartLocationX(v)
	return _u
}

// ClearStartLocationX clears the value of the "start_location_x" field.
func (_u *PlayerUpdateOne) ClearStartLocationX() *PlayerUpdateOne {
	_u.mutation.ClearStartLocationX()
	return _u
}

// SetStartLocationY sets the "start_location_y" field.
func (_u *PlayerUpdateOne) SetStartLocationY(v uint16) *PlayerUpdateOne {
	_u.mutation.ResetStartLocationY()
	_u.mutation.SetStartLocationY(v)
	return _u
}

// SetNillableStartLocationY sets the "start_location_y" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableStartLocationY(v *uint16) *PlayerUpdateOne {
	if v != nil {
		_u.SetStartLocationY(*v)
	}
	return _u
}

// AddStartLocationY adds value to the "start_location_y" field.
func (_u *PlayerUpdateOne) AddStartLocationY(v int16) *PlayerUpdateOne {
	_u.mutation.AddStartLocationY(v)
	return _u
}

// ClearStartLocationY clears the value of the "start_location_y" field.
func (_u *PlayerUpdateOne) ClearStartLocationY() *PlayerUpdateOne {
	_u.mutation.ClearStartLocationY()
	return _u
}

// SetStartDirection sets the "start_direction" field.
func (_u *PlayerUpdateOne) SetStartDirection(v int32) *PlayerUpdateOne {
	_u.mutation.ResetStartDirection()
	_u.mutation.SetStartDirection(v)
	return _u
}

// SetNillableStartDirection sets the "start_direction" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableStartDirection(v *int32) *PlayerUpdateOne {
	if v != nil {
		_u.SetStartDirection(*v)
	}
	return _u
}

// AddStartDirection adds value to the "start_direction" field.
func (_u *PlayerUpdateOne) AddStartDirection(v int32) *PlayerUpdateOne {
	_u.mutation.AddStartDirection(v)
	return _u
}

// ClearStartDirection clears the value of the "start_direction" field.
func (_u *PlayerUpdateOne) ClearStartDirection() *PlayerUpdateOne {
	_u.mutation.ClearStartDirection()
	return _u
}

// SetRedundancy sets the "redundancy" field.
func (_u *PlayerUpdateOne) SetRedundancy(v int) *PlayerUpdateOne {
	_u.mutation.ResetRedundancy()
	_u.mutation.SetRedundancy(v)
	return _u
}

// SetNillableRedundancy sets the "redundancy" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableRedundancy(v *int) *PlayerUpdateOne {
	if v != nil {
		_u.SetRedundancy(*v)
	}
	return _u
}

// AddRedundancy adds value to the "redundancy" field.
func (_u *PlayerUpdateOne) AddRedundancy(v int) *PlayerUpdateOne {
	_u.mutation.AddRedundancy(v)
	return _u
}

// ClearRedundancy clears the value of the "redundancy" field.
func (_u *PlayerUpdateOne) ClearRedundancy() *PlayerUpdateOne {
	_u.mutation.ClearRedundancy()
	return _u
}

// SetIsWinner sets the "is_winner" field.
func (_u *PlayerUpdateOne) SetIsWinner(v bool) *PlayerUpdateOne {
	_u.mutation.SetIsWinner(v)
	return _u
}

// SetNillableIsWinner sets the "is_winner" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableIsWinner(v *bool) *PlayerUpdateOne {
	if v != nil {
		_u.SetIsWinner(*v)
	}
	return _u
}

// SetIsRandomSelected sets the "is_random_selected" field.
func (_u *PlayerUpdateOne) SetIsRandomSelected(v bool) *PlayerUpdateOne {
	_u.mutation.SetIsRandomSelected(v)
	return _u
}

// SetNillableIsRandomSelected sets the "is_random_selected" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableIsRandomSelected(v *bool) *PlayerUpdateOne {
	if v != nil {
		_u.SetIsRandomSelected(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *PlayerUpdateOne) SetResult(v string) *PlayerUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillableResult(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_u *PlayerUpdateOne) SetGameID(id int) *PlayerUpdateOne {
	_u.mutation.SetGameID(id)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *PlayerUpdateOne) SetGame(v *Game) *PlayerUpdateOne {
	return _u.SetGameID(v.ID)
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdateOne) Mutation() *PlayerMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *PlayerUpdateOne) ClearGame() *PlayerUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Player entity.
func (_u *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := player.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Player.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Race(); ok {
		if err := player.RaceValidator(v); err != nil {
			return &ValidationError{Name: "race", err: fmt.Errorf(`ent: validator failed for field "Player.race": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Player.game"`)
	}
	return nil
}

func (_u *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(player.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Race(); ok {
		_spec.SetField(player.FieldRace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Team(); ok {
		_spec.SetField(player.FieldTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedTeam(); ok {
		_spec.AddField(player.FieldTeam, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(player.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(player.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedPlayerID(); ok {
		_spec.AddField(player.FieldPlayerID, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Apm(); ok {
		_spec.SetField(player.FieldApm, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedApm(); ok {
		_spec.AddField(player.FieldApm, field.TypeInt32, value)
	}
	if _u.mutation.ApmCleared() {
		_spec.ClearField(player.FieldApm, field.TypeInt32)
	}
	if value, ok := _u.mutation.Eapm(); ok {
		_spec.SetField(player.FieldEapm, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedEapm(); ok {
		_spec.AddField(player.FieldEapm, field.TypeInt32, value)
	}
	if _u.mutation.EapmCleared() {
		_spec.ClearField(player.FieldEapm, field.TypeInt32)
	}
	if value, ok := _u.mutation.CmdCount(); ok {
		_spec.SetField(player.FieldCmdCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCmdCount(); ok {
		_spec.AddField(player.FieldCmdCount, field.TypeUint32, value)
	}
	if _u.mutation.CmdCountCleared() {
		_spec.ClearField(player.FieldCmdCount, field.TypeUint32)
	}
	if value, ok := _u.mutation.EffectiveCmdCount(); ok {
		_spec.SetField(player.FieldEffectiveCmdCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedEffectiveCmdCount(); ok {
		_spec.AddField(player.FieldEffectiveCmdCount, field.TypeUint32, value)
	}
	if _u.mutation.EffectiveCmdCountCleared() {
		_spec.ClearField(player.FieldEffectiveCmdCount, field.TypeUint32)
	}
	if value, ok := _u.mutation.StartLocationX(); ok {
		_spec.SetField(player.FieldStartLocationX, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedStartLocationX(); ok {
		_spec.AddField(player.FieldStartLocationX, field.TypeUint16, value)
	}
	if _u.mutation.StartLocationXCleared() {
		_spec.ClearField(player.FieldStartLocationX, field.TypeUint16)
	}
	if value, ok := _u.mutation.StartLocationY(); ok {
		_spec.SetField(player.FieldStartLocationY, field.TypeUint16, value)
	}
	if value, ok := _u.mutation.AddedStartLocationY(); ok {
		_spec.AddField(player.FieldStartLocationY, field.TypeUint16, value)
	}
	if _u.mutation.StartLocationYCleared() {
		_spec.ClearField(player.FieldStartLocationY, field.TypeUint16)
	}
	if value, ok := _u.mutation.StartDirection(); ok {
		_spec.SetField(player.FieldStartDirection, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStartDirection(); ok {
		_spec.AddField(player.FieldStartDirection, field.TypeInt32, value)
	}
	if _u.mutation.StartDirectionCleared() {
		_spec.ClearField(player.FieldStartDirection, field.TypeInt32)
	}
	if value, ok := _u.mutation.Redundancy(); ok {
		_spec.SetField(player.FieldRedundancy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedundancy(); ok {
		_spec.AddField(player.FieldRedundancy, field.TypeInt, value)
	}
	if _u.mutation.RedundancyCleared() {
		_spec.ClearField(player.FieldRedundancy, field.TypeInt)
	}
	if value, ok := _u.mutation.IsWinner(); ok {
		_spec.SetField(player.FieldIsWinner, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsRandomSelected(); ok {
		_spec.SetField(player.FieldIsRandomSelected, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(player.FieldResult, field.TypeString, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.GameTable,
			Columns: []string{player.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.GameTable,
			Columns: []string{player.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Player{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
