// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/xungwoo/stareplays/ent/game"
	"github.com/xungwoo/stareplays/ent/player"
)

// Player is the model entity for the Player schema.
type Player struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Zerg/Terran/Protoss
	Race string `json:"race,omitempty"`
	// Team holds the value of the "team" field.
	Team uint8 `json:"team,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// Player.ID from replay
	PlayerID uint8 `json:"player_id,omitempty"`
	// Apm holds the value of the "apm" field.
	Apm int32 `json:"apm,omitempty"`
	// Eapm holds the value of the "eapm" field.
	Eapm int32 `json:"eapm,omitempty"`
	// CmdCount holds the value of the "cmd_count" field.
	CmdCount uint32 `json:"cmd_count,omitempty"`
	// EffectiveCmdCount holds the value of the "effective_cmd_count" field.
	EffectiveCmdCount uint32 `json:"effective_cmd_count,omitempty"`
	// StartLocationX holds the value of the "start_location_x" field.
	StartLocationX uint16 `json:"start_location_x,omitempty"`
	// StartLocationY holds the value of the "start_location_y" field.
	StartLocationY uint16 `json:"start_location_y,omitempty"`
	// 1-12 clock direction
	StartDirection int32 `json:"start_direction,omitempty"`
	// Redundancy percentage
	Redundancy int `json:"redundancy,omitempty"`
	// IsWinner holds the value of the "is_winner" field.
	IsWinner bool `json:"is_winner,omitempty"`
	// win/loss/draw/unknown
	Result string `json:"result,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayerQuery when eager-loading is set.
	Edges        PlayerEdges `json:"edges"`
	game_players *int
	selectValues sql.SelectValues
}

// PlayerEdges holds the relations/edges for other nodes in the graph.
type PlayerEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Player) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case player.FieldIsWinner:
			values[i] = new(sql.NullBool)
		case player.FieldID, player.FieldTeam, player.FieldPlayerID, player.FieldApm, player.FieldEapm, player.FieldCmdCount, player.FieldEffectiveCmdCount, player.FieldStartLocationX, player.FieldStartLocationY, player.FieldStartDirection, player.FieldRedundancy:
			values[i] = new(sql.NullInt64)
		case player.FieldName, player.FieldRace, player.FieldColor, player.FieldResult:
			values[i] = new(sql.NullString)
		case player.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case player.ForeignKeys[0]: // game_players
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Player fields.
func (_m *Player) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case player.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case player.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case player.FieldRace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field race", values[i])
			} else if value.Valid {
				_m.Race = value.String
			}
		case player.FieldTeam:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team", values[i])
			} else if value.Valid {
				_m.Team = uint8(value.Int64)
			}
		case player.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case player.FieldPlayerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field player_id", values[i])
			} else if value.Valid {
				_m.PlayerID = uint8(value.Int64)
			}
		case player.FieldApm:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field apm", values[i])
			} else if value.Valid {
				_m.Apm = int32(value.Int64)
			}
		case player.FieldEapm:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field eapm", values[i])
			} else if value.Valid {
				_m.Eapm = int32(value.Int64)
			}
		case player.FieldCmdCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cmd_count", values[i])
			} else if value.Valid {
				_m.CmdCount = uint32(value.Int64)
			}
		case player.FieldEffectiveCmdCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field effective_cmd_count", values[i])
			} else if value.Valid {
				_m.EffectiveCmdCount = uint32(value.Int64)
			}
		case player.FieldStartLocationX:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_location_x", values[i])
			} else if value.Valid {
				_m.StartLocationX = uint16(value.Int64)
			}
		case player.FieldStartLocationY:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_location_y", values[i])
			} else if value.Valid {
				_m.StartLocationY = uint16(value.Int64)
			}
		case player.FieldStartDirection:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_direction", values[i])
			} else if value.Valid {
				_m.StartDirection = int32(value.Int64)
			}
		case player.FieldRedundancy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redundancy", values[i])
			} else if value.Valid {
				_m.Redundancy = int(value.Int64)
			}
		case player.FieldIsWinner:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_winner", values[i])
			} else if value.Valid {
				_m.IsWinner = value.Bool
			}
		case player.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = value.String
			}
		case player.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case player.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field game_players", value)
			} else if value.Valid {
				_m.game_players = new(int)
				*_m.game_players = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Player.
// This includes values selected through modifiers, order, etc.
func (_m *Player) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the Player entity.
func (_m *Player) QueryGame() *GameQuery {
	return NewPlayerClient(_m.config).QueryGame(_m)
}

// Update returns a builder for updating this Player.
// Note that you need to call Player.Unwrap() before calling this method if this Player
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Player) Update() *PlayerUpdateOne {
	return NewPlayerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Player entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Player) Unwrap() *Player {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Player is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Player) String() string {
	var builder strings.Builder
	builder.WriteString("Player(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("race=")
	builder.WriteString(_m.Race)
	builder.WriteString(", ")
	builder.WriteString("team=")
	builder.WriteString(fmt.Sprintf("%v", _m.Team))
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteString(", ")
	builder.WriteString("player_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlayerID))
	builder.WriteString(", ")
	builder.WriteString("apm=")
	builder.WriteString(fmt.Sprintf("%v", _m.Apm))
	builder.WriteString(", ")
	builder.WriteString("eapm=")
	builder.WriteString(fmt.Sprintf("%v", _m.Eapm))
	builder.WriteString(", ")
	builder.WriteString("cmd_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CmdCount))
	builder.WriteString(", ")
	builder.WriteString("effective_cmd_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.EffectiveCmdCount))
	builder.WriteString(", ")
	builder.WriteString("start_location_x=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartLocationX))
	builder.WriteString(", ")
	builder.WriteString("start_location_y=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartLocationY))
	builder.WriteString(", ")
	builder.WriteString("start_direction=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartDirection))
	builder.WriteString(", ")
	builder.WriteString("redundancy=")
	builder.WriteString(fmt.Sprintf("%v", _m.Redundancy))
	builder.WriteString(", ")
	builder.WriteString("is_winner=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsWinner))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(_m.Result)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Players is a parsable slice of Player.
type Players []*Player
