// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/xungwoo/stareplays/ent/analyzerracematchup"
	"github.com/xungwoo/stareplays/ent/appsetting"
	"github.com/xungwoo/stareplays/ent/game"
	"github.com/xungwoo/stareplays/ent/gameanalysis"
	"github.com/xungwoo/stareplays/ent/player"
	"github.com/xungwoo/stareplays/ent/ranking3v3"
	"github.com/xungwoo/stareplays/ent/replayfile"
	"github.com/xungwoo/stareplays/ent/schema"
	"github.com/xungwoo/stareplays/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	analyzerracematchupFields := schema.AnalyzerRaceMatchup{}.Fields()
	_ = analyzerracematchupFields
	// analyzerracematchupDescTeamSize is the schema descriptor for team_size field.
	analyzerracematchupDescTeamSize := analyzerracematchupFields[0].Descriptor()
	// analyzerracematchup.DefaultTeamSize holds the default value on creation for the team_size field.
	analyzerracematchup.DefaultTeamSize = analyzerracematchupDescTeamSize.Default.(int)
	// analyzerracematchupDescTeamA is the schema descriptor for team_a field.
	analyzerracematchupDescTeamA := analyzerracematchupFields[1].Descriptor()
	// analyzerracematchup.TeamAValidator is a validator for the "team_a" field. It is called by the builders before save.
	analyzerracematchup.TeamAValidator = analyzerracematchupDescTeamA.Validators[0].(func(string) error)
	// analyzerracematchupDescTeamB is the schema descriptor for team_b field.
	analyzerracematchupDescTeamB := analyzerracematchupFields[2].Descriptor()
	// analyzerracematchup.TeamBValidator is a validator for the "team_b" field. It is called by the builders before save.
	analyzerracematchup.TeamBValidator = analyzerracematchupDescTeamB.Validators[0].(func(string) error)
	// analyzerracematchupDescMatchupKey is the schema descriptor for matchup_key field.
	analyzerracematchupDescMatchupKey := analyzerracematchupFields[3].Descriptor()
	// analyzerracematchup.MatchupKeyValidator is a validator for the "matchup_key" field. It is called by the builders before save.
	analyzerracematchup.MatchupKeyValidator = analyzerracematchupDescMatchupKey.Validators[0].(func(string) error)
	// analyzerracematchupDescGames is the schema descriptor for games field.
	analyzerracematchupDescGames := analyzerracematchupFields[4].Descriptor()
	// analyzerracematchup.DefaultGames holds the default value on creation for the games field.
	analyzerracematchup.DefaultGames = analyzerracematchupDescGames.Default.(int)
	// analyzerracematchupDescTeamAWins is the schema descriptor for team_a_wins field.
	analyzerracematchupDescTeamAWins := analyzerracematchupFields[5].Descriptor()
	// analyzerracematchup.DefaultTeamAWins holds the default value on creation for the team_a_wins field.
	analyzerracematchup.DefaultTeamAWins = analyzerracematchupDescTeamAWins.Default.(int)
	// analyzerracematchupDescTeamBWins is the schema descriptor for team_b_wins field.
	analyzerracematchupDescTeamBWins := analyzerracematchupFields[6].Descriptor()
	// analyzerracematchup.DefaultTeamBWins holds the default value on creation for the team_b_wins field.
	analyzerracematchup.DefaultTeamBWins = analyzerracematchupDescTeamBWins.Default.(int)
	// analyzerracematchupDescTeamAWinRate is the schema descriptor for team_a_win_rate field.
	analyzerracematchupDescTeamAWinRate := analyzerracematchupFields[7].Descriptor()
	// analyzerracematchup.DefaultTeamAWinRate holds the default value on creation for the team_a_win_rate field.
	analyzerracematchup.DefaultTeamAWinRate = analyzerracematchupDescTeamAWinRate.Default.(float64)
	// analyzerracematchupDescTeamBWinRate is the schema descriptor for team_b_win_rate field.
	analyzerracematchupDescTeamBWinRate := analyzerracematchupFields[8].Descriptor()
	// analyzerracematchup.DefaultTeamBWinRate holds the default value on creation for the team_b_win_rate field.
	analyzerracematchup.DefaultTeamBWinRate = analyzerracematchupDescTeamBWinRate.Default.(float64)
	// analyzerracematchupDescComputedAt is the schema descriptor for computed_at field.
	analyzerracematchupDescComputedAt := analyzerracematchupFields[9].Descriptor()
	// analyzerracematchup.DefaultComputedAt holds the default value on creation for the computed_at field.
	analyzerracematchup.DefaultComputedAt = analyzerracematchupDescComputedAt.Default.(func() time.Time)
	// analyzerracematchupDescCreatedAt is the schema descriptor for created_at field.
	analyzerracematchupDescCreatedAt := analyzerracematchupFields[10].Descriptor()
	// analyzerracematchup.DefaultCreatedAt holds the default value on creation for the created_at field.
	analyzerracematchup.DefaultCreatedAt = analyzerracematchupDescCreatedAt.Default.(func() time.Time)
	// analyzerracematchupDescUpdatedAt is the schema descriptor for updated_at field.
	analyzerracematchupDescUpdatedAt := analyzerracematchupFields[11].Descriptor()
	// analyzerracematchup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	analyzerracematchup.DefaultUpdatedAt = analyzerracematchupDescUpdatedAt.Default.(func() time.Time)
	// analyzerracematchup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	analyzerracematchup.UpdateDefaultUpdatedAt = analyzerracematchupDescUpdatedAt.UpdateDefault.(func() time.Time)
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescKey is the schema descriptor for key field.
	appsettingDescKey := appsettingFields[0].Descriptor()
	// appsetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	appsetting.KeyValidator = appsettingDescKey.Validators[0].(func(string) error)
	// appsettingDescCreatedAt is the schema descriptor for created_at field.
	appsettingDescCreatedAt := appsettingFields[2].Descriptor()
	// appsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsetting.DefaultCreatedAt = appsettingDescCreatedAt.Default.(func() time.Time)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingFields[3].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescHost is the schema descriptor for host field.
	gameDescHost := gameFields[0].Descriptor()
	// game.HostValidator is a validator for the "host" field. It is called by the builders before save.
	game.HostValidator = gameDescHost.Validators[0].(func(string) error)
	// gameDescPlayerCount is the schema descriptor for player_count field.
	gameDescPlayerCount := gameFields[9].Descriptor()
	// game.DefaultPlayerCount holds the default value on creation for the player_count field.
	game.DefaultPlayerCount = gameDescPlayerCount.Default.(int)
	// gameDescUploadCount is the schema descriptor for upload_count field.
	gameDescUploadCount := gameFields[10].Descriptor()
	// game.DefaultUploadCount holds the default value on creation for the upload_count field.
	game.DefaultUploadCount = gameDescUploadCount.Default.(int)
	// gameDescWinnerTeam is the schema descriptor for winner_team field.
	gameDescWinnerTeam := gameFields[11].Descriptor()
	// game.DefaultWinnerTeam holds the default value on creation for the winner_team field.
	game.DefaultWinnerTeam = gameDescWinnerTeam.Default.(uint8)
	// gameDescIsRandomSelected is the schema descriptor for is_random_selected field.
	gameDescIsRandomSelected := gameFields[12].Descriptor()
	// game.DefaultIsRandomSelected holds the default value on creation for the is_random_selected field.
	game.DefaultIsRandomSelected = gameDescIsRandomSelected.Default.(bool)
	// gameDescCreatedAt is the schema descriptor for created_at field.
	gameDescCreatedAt := gameFields[15].Descriptor()
	// game.DefaultCreatedAt holds the default value on creation for the created_at field.
	game.DefaultCreatedAt = gameDescCreatedAt.Default.(func() time.Time)
	// gameDescUpdatedAt is the schema descriptor for updated_at field.
	gameDescUpdatedAt := gameFields[16].Descriptor()
	// game.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	game.DefaultUpdatedAt = gameDescUpdatedAt.Default.(func() time.Time)
	// game.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	game.UpdateDefaultUpdatedAt = gameDescUpdatedAt.UpdateDefault.(func() time.Time)
	gameanalysisFields := schema.GameAnalysis{}.Fields()
	_ = gameanalysisFields
	// gameanalysisDescGameID is the schema descriptor for game_id field.
	gameanalysisDescGameID := gameanalysisFields[0].Descriptor()
	// gameanalysis.GameIDValidator is a validator for the "game_id" field. It is called by the builders before save.
	gameanalysis.GameIDValidator = gameanalysisDescGameID.Validators[0].(func(int) error)
	// gameanalysisDescFileHash is the schema descriptor for file_hash field.
	gameanalysisDescFileHash := gameanalysisFields[1].Descriptor()
	// gameanalysis.FileHashValidator is a validator for the "file_hash" field. It is called by the builders before save.
	gameanalysis.FileHashValidator = gameanalysisDescFileHash.Validators[0].(func(string) error)
	// gameanalysisDescBucketKey is the schema descriptor for bucket_key field.
	gameanalysisDescBucketKey := gameanalysisFields[2].Descriptor()
	// gameanalysis.BucketKeyValidator is a validator for the "bucket_key" field. It is called by the builders before save.
	gameanalysis.BucketKeyValidator = gameanalysisDescBucketKey.Validators[0].(func(string) error)
	// gameanalysisDescAnalyzerVersion is the schema descriptor for analyzer_version field.
	gameanalysisDescAnalyzerVersion := gameanalysisFields[3].Descriptor()
	// gameanalysis.DefaultAnalyzerVersion holds the default value on creation for the analyzer_version field.
	gameanalysis.DefaultAnalyzerVersion = gameanalysisDescAnalyzerVersion.Default.(string)
	// gameanalysis.AnalyzerVersionValidator is a validator for the "analyzer_version" field. It is called by the builders before save.
	gameanalysis.AnalyzerVersionValidator = gameanalysisDescAnalyzerVersion.Validators[0].(func(string) error)
	// gameanalysisDescStatus is the schema descriptor for status field.
	gameanalysisDescStatus := gameanalysisFields[4].Descriptor()
	// gameanalysis.DefaultStatus holds the default value on creation for the status field.
	gameanalysis.DefaultStatus = gameanalysisDescStatus.Default.(string)
	// gameanalysisDescAttemptCount is the schema descriptor for attempt_count field.
	gameanalysisDescAttemptCount := gameanalysisFields[5].Descriptor()
	// gameanalysis.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	gameanalysis.DefaultAttemptCount = gameanalysisDescAttemptCount.Default.(int)
	// gameanalysisDescPriority is the schema descriptor for priority field.
	gameanalysisDescPriority := gameanalysisFields[6].Descriptor()
	// gameanalysis.DefaultPriority holds the default value on creation for the priority field.
	gameanalysis.DefaultPriority = gameanalysisDescPriority.Default.(int)
	// gameanalysisDescRequestedAt is the schema descriptor for requested_at field.
	gameanalysisDescRequestedAt := gameanalysisFields[7].Descriptor()
	// gameanalysis.DefaultRequestedAt holds the default value on creation for the requested_at field.
	gameanalysis.DefaultRequestedAt = gameanalysisDescRequestedAt.Default.(func() time.Time)
	// gameanalysisDescNextRetryAt is the schema descriptor for next_retry_at field.
	gameanalysisDescNextRetryAt := gameanalysisFields[10].Descriptor()
	// gameanalysis.DefaultNextRetryAt holds the default value on creation for the next_retry_at field.
	gameanalysis.DefaultNextRetryAt = gameanalysisDescNextRetryAt.Default.(func() time.Time)
	// gameanalysisDescCreatedAt is the schema descriptor for created_at field.
	gameanalysisDescCreatedAt := gameanalysisFields[19].Descriptor()
	// gameanalysis.DefaultCreatedAt holds the default value on creation for the created_at field.
	gameanalysis.DefaultCreatedAt = gameanalysisDescCreatedAt.Default.(func() time.Time)
	// gameanalysisDescUpdatedAt is the schema descriptor for updated_at field.
	gameanalysisDescUpdatedAt := gameanalysisFields[20].Descriptor()
	// gameanalysis.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	gameanalysis.DefaultUpdatedAt = gameanalysisDescUpdatedAt.Default.(func() time.Time)
	// gameanalysis.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	gameanalysis.UpdateDefaultUpdatedAt = gameanalysisDescUpdatedAt.UpdateDefault.(func() time.Time)
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescName is the schema descriptor for name field.
	playerDescName := playerFields[0].Descriptor()
	// player.NameValidator is a validator for the "name" field. It is called by the builders before save.
	player.NameValidator = playerDescName.Validators[0].(func(string) error)
	// playerDescRace is the schema descriptor for race field.
	playerDescRace := playerFields[1].Descriptor()
	// player.RaceValidator is a validator for the "race" field. It is called by the builders before save.
	player.RaceValidator = playerDescRace.Validators[0].(func(string) error)
	// playerDescIsWinner is the schema descriptor for is_winner field.
	playerDescIsWinner := playerFields[13].Descriptor()
	// player.DefaultIsWinner holds the default value on creation for the is_winner field.
	player.DefaultIsWinner = playerDescIsWinner.Default.(bool)
	// playerDescResult is the schema descriptor for result field.
	playerDescResult := playerFields[14].Descriptor()
	// player.DefaultResult holds the default value on creation for the result field.
	player.DefaultResult = playerDescResult.Default.(string)
	// playerDescCreatedAt is the schema descriptor for created_at field.
	playerDescCreatedAt := playerFields[15].Descriptor()
	// player.DefaultCreatedAt holds the default value on creation for the created_at field.
	player.DefaultCreatedAt = playerDescCreatedAt.Default.(func() time.Time)
	ranking3v3Fields := schema.Ranking3v3{}.Fields()
	_ = ranking3v3Fields
	// ranking3v3DescName is the schema descriptor for name field.
	ranking3v3DescName := ranking3v3Fields[0].Descriptor()
	// ranking3v3.NameValidator is a validator for the "name" field. It is called by the builders before save.
	ranking3v3.NameValidator = ranking3v3DescName.Validators[0].(func(string) error)
	// ranking3v3DescRank is the schema descriptor for rank field.
	ranking3v3DescRank := ranking3v3Fields[1].Descriptor()
	// ranking3v3.DefaultRank holds the default value on creation for the rank field.
	ranking3v3.DefaultRank = ranking3v3DescRank.Default.(int)
	// ranking3v3DescGames is the schema descriptor for games field.
	ranking3v3DescGames := ranking3v3Fields[2].Descriptor()
	// ranking3v3.DefaultGames holds the default value on creation for the games field.
	ranking3v3.DefaultGames = ranking3v3DescGames.Default.(int)
	// ranking3v3DescWins is the schema descriptor for wins field.
	ranking3v3DescWins := ranking3v3Fields[3].Descriptor()
	// ranking3v3.DefaultWins holds the default value on creation for the wins field.
	ranking3v3.DefaultWins = ranking3v3DescWins.Default.(int)
	// ranking3v3DescLosses is the schema descriptor for losses field.
	ranking3v3DescLosses := ranking3v3Fields[4].Descriptor()
	// ranking3v3.DefaultLosses holds the default value on creation for the losses field.
	ranking3v3.DefaultLosses = ranking3v3DescLosses.Default.(int)
	// ranking3v3DescDraws is the schema descriptor for draws field.
	ranking3v3DescDraws := ranking3v3Fields[5].Descriptor()
	// ranking3v3.DefaultDraws holds the default value on creation for the draws field.
	ranking3v3.DefaultDraws = ranking3v3DescDraws.Default.(int)
	// ranking3v3DescWinRate is the schema descriptor for win_rate field.
	ranking3v3DescWinRate := ranking3v3Fields[6].Descriptor()
	// ranking3v3.DefaultWinRate holds the default value on creation for the win_rate field.
	ranking3v3.DefaultWinRate = ranking3v3DescWinRate.Default.(float64)
	// ranking3v3DescAvgApm is the schema descriptor for avg_apm field.
	ranking3v3DescAvgApm := ranking3v3Fields[7].Descriptor()
	// ranking3v3.DefaultAvgApm holds the default value on creation for the avg_apm field.
	ranking3v3.DefaultAvgApm = ranking3v3DescAvgApm.Default.(float64)
	// ranking3v3DescAvgEapm is the schema descriptor for avg_eapm field.
	ranking3v3DescAvgEapm := ranking3v3Fields[8].Descriptor()
	// ranking3v3.DefaultAvgEapm holds the default value on creation for the avg_eapm field.
	ranking3v3.DefaultAvgEapm = ranking3v3DescAvgEapm.Default.(float64)
	// ranking3v3DescMinGames is the schema descriptor for min_games field.
	ranking3v3DescMinGames := ranking3v3Fields[9].Descriptor()
	// ranking3v3.DefaultMinGames holds the default value on creation for the min_games field.
	ranking3v3.DefaultMinGames = ranking3v3DescMinGames.Default.(int)
	// ranking3v3DescComputedAt is the schema descriptor for computed_at field.
	ranking3v3DescComputedAt := ranking3v3Fields[10].Descriptor()
	// ranking3v3.DefaultComputedAt holds the default value on creation for the computed_at field.
	ranking3v3.DefaultComputedAt = ranking3v3DescComputedAt.Default.(func() time.Time)
	// ranking3v3DescCreatedAt is the schema descriptor for created_at field.
	ranking3v3DescCreatedAt := ranking3v3Fields[11].Descriptor()
	// ranking3v3.DefaultCreatedAt holds the default value on creation for the created_at field.
	ranking3v3.DefaultCreatedAt = ranking3v3DescCreatedAt.Default.(func() time.Time)
	// ranking3v3DescUpdatedAt is the schema descriptor for updated_at field.
	ranking3v3DescUpdatedAt := ranking3v3Fields[12].Descriptor()
	// ranking3v3.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ranking3v3.DefaultUpdatedAt = ranking3v3DescUpdatedAt.Default.(func() time.Time)
	// ranking3v3.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ranking3v3.UpdateDefaultUpdatedAt = ranking3v3DescUpdatedAt.UpdateDefault.(func() time.Time)
	replayfileFields := schema.ReplayFile{}.Fields()
	_ = replayfileFields
	// replayfileDescFileHash is the schema descriptor for file_hash field.
	replayfileDescFileHash := replayfileFields[0].Descriptor()
	// replayfile.FileHashValidator is a validator for the "file_hash" field. It is called by the builders before save.
	replayfile.FileHashValidator = replayfileDescFileHash.Validators[0].(func(string) error)
	// replayfileDescFilename is the schema descriptor for filename field.
	replayfileDescFilename := replayfileFields[1].Descriptor()
	// replayfile.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	replayfile.FilenameValidator = replayfileDescFilename.Validators[0].(func(string) error)
	// replayfileDescCreatedAt is the schema descriptor for created_at field.
	replayfileDescCreatedAt := replayfileFields[2].Descriptor()
	// replayfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	replayfile.DefaultCreatedAt = replayfileDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescTotalGames is the schema descriptor for total_games field.
	userDescTotalGames := userFields[1].Descriptor()
	// user.DefaultTotalGames holds the default value on creation for the total_games field.
	user.DefaultTotalGames = userDescTotalGames.Default.(int)
	// userDescWins is the schema descriptor for wins field.
	userDescWins := userFields[2].Descriptor()
	// user.DefaultWins holds the default value on creation for the wins field.
	user.DefaultWins = userDescWins.Default.(int)
	// userDescLosses is the schema descriptor for losses field.
	userDescLosses := userFields[3].Descriptor()
	// user.DefaultLosses holds the default value on creation for the losses field.
	user.DefaultLosses = userDescLosses.Default.(int)
	// userDescDraws is the schema descriptor for draws field.
	userDescDraws := userFields[4].Descriptor()
	// user.DefaultDraws holds the default value on creation for the draws field.
	user.DefaultDraws = userDescDraws.Default.(int)
	// userDescAverageApm is the schema descriptor for average_apm field.
	userDescAverageApm := userFields[5].Descriptor()
	// user.DefaultAverageApm holds the default value on creation for the average_apm field.
	user.DefaultAverageApm = userDescAverageApm.Default.(float64)
	// userDescAverageEapm is the schema descriptor for average_eapm field.
	userDescAverageEapm := userFields[6].Descriptor()
	// user.DefaultAverageEapm holds the default value on creation for the average_eapm field.
	user.DefaultAverageEapm = userDescAverageEapm.Default.(float64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
