// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareplays/ent/predicate"
	"github.com/xungwoo/stareplays/ent/replayfile"
	"github.com/xungwoo/stareplays/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTotalGames sets the "total_games" field.
func (_u *UserUpdate) SetTotalGames(v int) *UserUpdate {
	_u.mutation.ResetTotalGames()
	_u.mutation.SetTotalGames(v)
	return _u
}

// SetNillableTotalGames sets the "total_games" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTotalGames(v *int) *UserUpdate {
	if v != nil {
		_u.SetTotalGames(*v)
	}
	return _u
}

// AddTotalGames adds value to the "total_games" field.
func (_u *UserUpdate) AddTotalGames(v int) *UserUpdate {
	_u.mutation.AddTotalGames(v)
	return _u
}

// SetWins sets the "wins" field.
func (_u *UserUpdate) SetWins(v int) *UserUpdate {
	_u.mutation.ResetWins()
	_u.mutation.SetWins(v)
	return _u
}

// SetNillableWins sets the "wins" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWins(v *int) *UserUpdate {
	if v != nil {
		_u.SetWins(*v)
	}
	return _u
}

// AddWins adds value to the "wins" field.
func (_u *UserUpdate) AddWins(v int) *UserUpdate {
	_u.mutation.AddWins(v)
	return _u
}

// SetLosses sets the "losses" field.
func (_u *UserUpdate) SetLosses(v int) *UserUpdate {
	_u.mutation.ResetLosses()
	_u.mutation.SetLosses(v)
	return _u
}

// SetNillableLosses sets the "losses" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLosses(v *int) *UserUpdate {
	if v != nil {
		_u.SetLosses(*v)
	}
	return _u
}

// AddLosses adds value to the "losses" field.
func (_u *UserUpdate) AddLosses(v int) *UserUpdate {
	_u.mutation.AddLosses(v)
	return _u
}

// SetDraws sets the "draws" field.
func (_u *UserUpdate) SetDraws(v int) *UserUpdate {
	_u.mutation.ResetDraws()
	_u.mutation.SetDraws(v)
	return _u
}

// SetNillableDraws sets the "draws" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDraws(v *int) *UserUpdate {
	if v != nil {
		_u.SetDraws(*v)
	}
	return _u
}

// AddDraws adds value to the "draws" field.
func (_u *UserUpdate) AddDraws(v int) *UserUpdate {
	_u.mutation.AddDraws(v)
	return _u
}

// SetAverageApm sets the "average_apm" field.
func (_u *UserUpdate) SetAverageApm(v float64) *UserUpdate {
	_u.mutation.ResetAverageApm()
	_u.mutation.SetAverageApm(v)
	return _u
}

// SetNillableAverageApm sets the "average_apm" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAverageApm(v *float64) *UserUpdate {
	if v != nil {
		_u.SetAverageApm(*v)
	}
	return _u
}

// AddAverageApm adds value to the "average_apm" field.
func (_u *UserUpdate) AddAverageApm(v float64) *UserUpdate {
	_u.mutation.AddAverageApm(v)
	return _u
}

// SetAverageEapm sets the "average_eapm" field.
func (_u *UserUpdate) SetAverageEapm(v float64) *UserUpdate {
	_u.mutation.ResetAverageEapm()
	_u.mutation.SetAverageEapm(v)
	return _u
}

// SetNillableAverageEapm sets the "average_eapm" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAverageEapm(v *float64) *UserUpdate {
	if v != nil {
		_u.SetAverageEapm(*v)
	}
	return _u
}

// AddAverageEapm adds value to the "average_eapm" field.
func (_u *UserUpdate) AddAverageEapm(v float64) *UserUpdate {
	_u.mutation.AddAverageEapm(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUploadedReplayFileIDs adds the "uploaded_replay_files" edge to the ReplayFile entity by IDs.
func (_u *UserUpdate) AddUploadedReplayFileIDs(ids ...int) *UserUpdate {
	_u.mutation.AddUploadedReplayFileIDs(ids...)
	return _u
}

// AddUploadedReplayFiles adds the "uploaded_replay_files" edges to the ReplayFile entity.
func (_u *UserUpdate) AddUploadedReplayFiles(v ...*ReplayFile) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUploadedReplayFileIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearUploadedReplayFiles clears all "uploaded_replay_files" edges to the ReplayFile entity.
func (_u *UserUpdate) ClearUploadedReplayFiles() *UserUpdate {
	_u.mutation.ClearUploadedReplayFiles()
	return _u
}

// RemoveUploadedReplayFileIDs removes the "uploaded_replay_files" edge to ReplayFile entities by IDs.
func (_u *UserUpdate) RemoveUploadedReplayFileIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveUploadedReplayFileIDs(ids...)
	return _u
}

// RemoveUploadedReplayFiles removes "uploaded_replay_files" edges to ReplayFile entities.
func (_u *UserUpdate) RemoveUploadedReplayFiles(v ...*ReplayFile) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUploadedReplayFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalGames(); ok {
		_spec.SetField(user.FieldTotalGames, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalGames(); ok {
		_spec.AddField(user.FieldTotalGames, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Wins(); ok {
		_spec.SetField(user.FieldWins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWins(); ok {
		_spec.AddField(user.FieldWins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Losses(); ok {
		_spec.SetField(user.FieldLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLosses(); ok {
		_spec.AddField(user.FieldLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Draws(); ok {
		_spec.SetField(user.FieldDraws, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDraws(); ok {
		_spec.AddField(user.FieldDraws, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AverageApm(); ok {
		_spec.SetField(user.FieldAverageApm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageApm(); ok {
		_spec.AddField(user.FieldAverageApm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AverageEapm(); ok {
		_spec.SetField(user.FieldAverageEapm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageEapm(); ok {
		_spec.AddField(user.FieldAverageEapm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUploadedReplayFilesIDs(); len(nodes) > 0 && !_u.mutation.UploadedReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadedReplayFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTotalGames sets the "total_games" field.
func (_u *UserUpdateOne) SetTotalGames(v int) *UserUpdateOne {
	_u.mutation.ResetTotalGames()
	_u.mutation.SetTotalGames(v)
	return _u
}

// SetNillableTotalGames sets the "total_games" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTotalGames(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetTotalGames(*v)
	}
	return _u
}

// AddTotalGames adds value to the "total_games" field.
func (_u *UserUpdateOne) AddTotalGames(v int) *UserUpdateOne {
	_u.mutation.AddTotalGames(v)
	return _u
}

// SetWins sets the "wins" field.
func (_u *UserUpdateOne) SetWins(v int) *UserUpdateOne {
	_u.mutation.ResetWins()
	_u.mutation.SetWins(v)
	return _u
}

// SetNillableWins sets the "wins" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWins(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetWins(*v)
	}
	return _u
}

// AddWins adds value to the "wins" field.
func (_u *UserUpdateOne) AddWins(v int) *UserUpdateOne {
	_u.mutation.AddWins(v)
	return _u
}

// SetLosses sets the "losses" field.
func (_u *UserUpdateOne) SetLosses(v int) *UserUpdateOne {
	_u.mutation.ResetLosses()
	_u.mutation.SetLosses(v)
	return _u
}

// SetNillableLosses sets the "losses" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLosses(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetLosses(*v)
	}
	return _u
}

// AddLosses adds value to the "losses" field.
func (_u *UserUpdateOne) AddLosses(v int) *UserUpdateOne {
	_u.mutation.AddLosses(v)
	return _u
}

// SetDraws sets the "draws" field.
func (_u *UserUpdateOne) SetDraws(v int) *UserUpdateOne {
	_u.mutation.ResetDraws()
	_u.mutation.SetDraws(v)
	return _u
}

// SetNillableDraws sets the "draws" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDraws(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetDraws(*v)
	}
	return _u
}

// AddDraws adds value to the "draws" field.
func (_u *UserUpdateOne) AddDraws(v int) *UserUpdateOne {
	_u.mutation.AddDraws(v)
	return _u
}

// SetAverageApm sets the "average_apm" field.
func (_u *UserUpdateOne) SetAverageApm(v float64) *UserUpdateOne {
	_u.mutation.ResetAverageApm()
	_u.mutation.SetAverageApm(v)
	return _u
}

// SetNillableAverageApm sets the "average_apm" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAverageApm(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetAverageApm(*v)
	}
	return _u
}

// AddAverageApm adds value to the "average_apm" field.
func (_u *UserUpdateOne) AddAverageApm(v float64) *UserUpdateOne {
	_u.mutation.AddAverageApm(v)
	return _u
}

// SetAverageEapm sets the "average_eapm" field.
func (_u *UserUpdateOne) SetAverageEapm(v float64) *UserUpdateOne {
	_u.mutation.ResetAverageEapm()
	_u.mutation.SetAverageEapm(v)
	return _u
}

// SetNillableAverageEapm sets the "average_eapm" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAverageEapm(v *float64) *UserUpdateOne {
	if v != nil {
		_u.SetAverageEapm(*v)
	}
	return _u
}

// AddAverageEapm adds value to the "average_eapm" field.
func (_u *UserUpdateOne) AddAverageEapm(v float64) *UserUpdateOne {
	_u.mutation.AddAverageEapm(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUploadedReplayFileIDs adds the "uploaded_replay_files" edge to the ReplayFile entity by IDs.
func (_u *UserUpdateOne) AddUploadedReplayFileIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddUploadedReplayFileIDs(ids...)
	return _u
}

// AddUploadedReplayFiles adds the "uploaded_replay_files" edges to the ReplayFile entity.
func (_u *UserUpdateOne) AddUploadedReplayFiles(v ...*ReplayFile) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUploadedReplayFileIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearUploadedReplayFiles clears all "uploaded_replay_files" edges to the ReplayFile entity.
func (_u *UserUpdateOne) ClearUploadedReplayFiles() *UserUpdateOne {
	_u.mutation.ClearUploadedReplayFiles()
	return _u
}

// RemoveUploadedReplayFileIDs removes the "uploaded_replay_files" edge to ReplayFile entities by IDs.
func (_u *UserUpdateOne) RemoveUploadedReplayFileIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveUploadedReplayFileIDs(ids...)
	return _u
}

// RemoveUploadedReplayFiles removes "uploaded_replay_files" edges to ReplayFile entities.
func (_u *UserUpdateOne) RemoveUploadedReplayFiles(v ...*ReplayFile) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUploadedReplayFileIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalGames(); ok {
		_spec.SetField(user.FieldTotalGames, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalGames(); ok {
		_spec.AddField(user.FieldTotalGames, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Wins(); ok {
		_spec.SetField(user.FieldWins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWins(); ok {
		_spec.AddField(user.FieldWins, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Losses(); ok {
		_spec.SetField(user.FieldLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLosses(); ok {
		_spec.AddField(user.FieldLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Draws(); ok {
		_spec.SetField(user.FieldDraws, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDraws(); ok {
		_spec.AddField(user.FieldDraws, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AverageApm(); ok {
		_spec.SetField(user.FieldAverageApm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageApm(); ok {
		_spec.AddField(user.FieldAverageApm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AverageEapm(); ok {
		_spec.SetField(user.FieldAverageEapm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAverageEapm(); ok {
		_spec.AddField(user.FieldAverageEapm, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UploadedReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUploadedReplayFilesIDs(); len(nodes) > 0 && !_u.mutation.UploadedReplayFilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadedReplayFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
