// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnalyzerRaceMatchupsColumns holds the columns for the "analyzer_race_matchups" table.
	AnalyzerRaceMatchupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "team_size", Type: field.TypeInt, Default: 0},
		{Name: "team_a", Type: field.TypeString},
		{Name: "team_b", Type: field.TypeString},
		{Name: "matchup_key", Type: field.TypeString},
		{Name: "games", Type: field.TypeInt, Default: 0},
		{Name: "team_a_wins", Type: field.TypeInt, Default: 0},
		{Name: "team_b_wins", Type: field.TypeInt, Default: 0},
		{Name: "team_a_win_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "team_b_win_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "computed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AnalyzerRaceMatchupsTable holds the schema information for the "analyzer_race_matchups" table.
	AnalyzerRaceMatchupsTable = &schema.Table{
		Name:       "analyzer_race_matchups",
		Columns:    AnalyzerRaceMatchupsColumns,
		PrimaryKey: []*schema.Column{AnalyzerRaceMatchupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "analyzerracematchup_team_size_team_a_team_b",
				Unique:  true,
				Columns: []*schema.Column{AnalyzerRaceMatchupsColumns[1], AnalyzerRaceMatchupsColumns[2], AnalyzerRaceMatchupsColumns[3]},
			},
			{
				Name:    "analyzerracematchup_team_size_games",
				Unique:  false,
				Columns: []*schema.Column{AnalyzerRaceMatchupsColumns[1], AnalyzerRaceMatchupsColumns[5]},
			},
			{
				Name:    "analyzerracematchup_team_size_team_a_win_rate",
				Unique:  false,
				Columns: []*schema.Column{AnalyzerRaceMatchupsColumns[1], AnalyzerRaceMatchupsColumns[8]},
			},
			{
				Name:    "analyzerracematchup_team_size_matchup_key",
				Unique:  false,
				Columns: []*schema.Column{AnalyzerRaceMatchupsColumns[1], AnalyzerRaceMatchupsColumns[4]},
			},
		},
	}
	// AppSettingsColumns holds the columns for the "app_settings" table.
	AppSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AppSettingsTable holds the schema information for the "app_settings" table.
	AppSettingsTable = &schema.Table{
		Name:       "app_settings",
		Columns:    AppSettingsColumns,
		PrimaryKey: []*schema.Column{AppSettingsColumns[0]},
	}
	// GamesColumns holds the columns for the "games" table.
	GamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "host", Type: field.TypeString},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "map_name", Type: field.TypeString, Nullable: true},
		{Name: "map_width", Type: field.TypeUint16, Nullable: true},
		{Name: "map_height", Type: field.TypeUint16, Nullable: true},
		{Name: "game_length", Type: field.TypeInt, Nullable: true},
		{Name: "game_type", Type: field.TypeString, Nullable: true},
		{Name: "game_speed", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "player_count", Type: field.TypeInt, Default: 0},
		{Name: "upload_count", Type: field.TypeInt, Default: 1},
		{Name: "winner_team", Type: field.TypeUint8, Default: 0},
		{Name: "season_label", Type: field.TypeString, Nullable: true},
		{Name: "season_no", Type: field.TypeInt, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GamesTable holds the schema information for the "games" table.
	GamesTable = &schema.Table{
		Name:       "games",
		Columns:    GamesColumns,
		PrimaryKey: []*schema.Column{GamesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "game_host_start_time",
				Unique:  true,
				Columns: []*schema.Column{GamesColumns[1], GamesColumns[2]},
			},
			{
				Name:    "game_player_count",
				Unique:  false,
				Columns: []*schema.Column{GamesColumns[10]},
			},
			{
				Name:    "game_season_label_start_time_created_at",
				Unique:  false,
				Columns: []*schema.Column{GamesColumns[13], GamesColumns[2], GamesColumns[15]},
			},
		},
	}
	// GameAnalysesColumns holds the columns for the "game_analyses" table.
	GameAnalysesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "file_hash", Type: field.TypeString},
		{Name: "bucket_key", Type: field.TypeString},
		{Name: "analyzer_version", Type: field.TypeString, Default: "v1"},
		{Name: "status", Type: field.TypeString, Default: "queued"},
		{Name: "attempt_count", Type: field.TypeInt, Default: 0},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "requested_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_retry_at", Type: field.TypeTime},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "quality_report_json", Type: field.TypeJSON, Nullable: true},
		{Name: "summary_json", Type: field.TypeJSON, Nullable: true},
		{Name: "analysis_phase_json", Type: field.TypeJSON, Nullable: true},
		{Name: "analysis_events_json", Type: field.TypeJSON, Nullable: true},
		{Name: "analysis_timeseries_json", Type: field.TypeJSON, Nullable: true},
		{Name: "artifact_result_dir", Type: field.TypeString, Nullable: true},
		{Name: "artifact_manifest_json", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "game_id", Type: field.TypeInt, Unique: true},
	}
	// GameAnalysesTable holds the schema information for the "game_analyses" table.
	GameAnalysesTable = &schema.Table{
		Name:       "game_analyses",
		Columns:    GameAnalysesColumns,
		PrimaryKey: []*schema.Column{GameAnalysesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "game_analyses_games_analysis",
				Columns:    []*schema.Column{GameAnalysesColumns[21]},
				RefColumns: []*schema.Column{GamesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "gameanalysis_game_id",
				Unique:  true,
				Columns: []*schema.Column{GameAnalysesColumns[21]},
			},
			{
				Name:    "gameanalysis_status_next_retry_at_priority_requested_at",
				Unique:  false,
				Columns: []*schema.Column{GameAnalysesColumns[4], GameAnalysesColumns[10], GameAnalysesColumns[6], GameAnalysesColumns[7]},
			},
		},
	}
	// GameDetailsColumns holds the columns for the "game_details" table.
	GameDetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "apm_timeline", Type: field.TypeJSON, Nullable: true},
		{Name: "build_orders", Type: field.TypeJSON, Nullable: true},
		{Name: "compressed_build_orders", Type: field.TypeJSON, Nullable: true},
		{Name: "chat_messages", Type: field.TypeJSON, Nullable: true},
		{Name: "game_game_detail", Type: field.TypeInt, Unique: true},
	}
	// GameDetailsTable holds the schema information for the "game_details" table.
	GameDetailsTable = &schema.Table{
		Name:       "game_details",
		Columns:    GameDetailsColumns,
		PrimaryKey: []*schema.Column{GameDetailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "game_details_games_game_detail",
				Columns:    []*schema.Column{GameDetailsColumns[5]},
				RefColumns: []*schema.Column{GamesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PlayersColumns holds the columns for the "players" table.
	PlayersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "race", Type: field.TypeString},
		{Name: "team", Type: field.TypeUint8},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "player_id", Type: field.TypeUint8},
		{Name: "apm", Type: field.TypeInt32, Nullable: true},
		{Name: "eapm", Type: field.TypeInt32, Nullable: true},
		{Name: "cmd_count", Type: field.TypeUint32, Nullable: true},
		{Name: "effective_cmd_count", Type: field.TypeUint32, Nullable: true},
		{Name: "start_location_x", Type: field.TypeUint16, Nullable: true},
		{Name: "start_location_y", Type: field.TypeUint16, Nullable: true},
		{Name: "start_direction", Type: field.TypeInt32, Nullable: true},
		{Name: "redundancy", Type: field.TypeInt, Nullable: true},
		{Name: "is_winner", Type: field.TypeBool, Default: false},
		{Name: "is_random_selected", Type: field.TypeBool, Default: false},
		{Name: "result", Type: field.TypeString, Default: "unknown"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "game_players", Type: field.TypeInt},
	}
	// PlayersTable holds the schema information for the "players" table.
	PlayersTable = &schema.Table{
		Name:       "players",
		Columns:    PlayersColumns,
		PrimaryKey: []*schema.Column{PlayersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "players_games_players",
				Columns:    []*schema.Column{PlayersColumns[18]},
				RefColumns: []*schema.Column{GamesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "player_name",
				Unique:  false,
				Columns: []*schema.Column{PlayersColumns[1]},
			},
			{
				Name:    "player_game_players",
				Unique:  false,
				Columns: []*schema.Column{PlayersColumns[18]},
			},
			{
				Name:    "player_player_id_game_players",
				Unique:  true,
				Columns: []*schema.Column{PlayersColumns[5], PlayersColumns[18]},
			},
		},
	}
	// Ranking3v3Columns holds the columns for the "ranking_3v3" table.
	Ranking3v3Columns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "rank", Type: field.TypeInt, Default: 0},
		{Name: "games", Type: field.TypeInt, Default: 0},
		{Name: "wins", Type: field.TypeInt, Default: 0},
		{Name: "losses", Type: field.TypeInt, Default: 0},
		{Name: "draws", Type: field.TypeInt, Default: 0},
		{Name: "win_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "avg_apm", Type: field.TypeFloat64, Default: 0},
		{Name: "avg_eapm", Type: field.TypeFloat64, Default: 0},
		{Name: "min_games", Type: field.TypeInt, Default: 20},
		{Name: "computed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// Ranking3v3Table holds the schema information for the "ranking_3v3" table.
	Ranking3v3Table = &schema.Table{
		Name:       "ranking_3v3",
		Columns:    Ranking3v3Columns,
		PrimaryKey: []*schema.Column{Ranking3v3Columns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ranking3v3_name",
				Unique:  true,
				Columns: []*schema.Column{Ranking3v3Columns[1]},
			},
			{
				Name:    "ranking3v3_rank",
				Unique:  false,
				Columns: []*schema.Column{Ranking3v3Columns[2]},
			},
			{
				Name:    "ranking3v3_games",
				Unique:  false,
				Columns: []*schema.Column{Ranking3v3Columns[3]},
			},
			{
				Name:    "ranking3v3_win_rate",
				Unique:  false,
				Columns: []*schema.Column{Ranking3v3Columns[7]},
			},
			{
				Name:    "ranking3v3_avg_apm",
				Unique:  false,
				Columns: []*schema.Column{Ranking3v3Columns[8]},
			},
			{
				Name:    "ranking3v3_avg_eapm",
				Unique:  false,
				Columns: []*schema.Column{Ranking3v3Columns[9]},
			},
		},
	}
	// ReplayFilesColumns holds the columns for the "replay_files" table.
	ReplayFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "file_hash", Type: field.TypeString},
		{Name: "filename", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "game_replay_files", Type: field.TypeInt},
		{Name: "user_uploaded_replay_files", Type: field.TypeInt},
	}
	// ReplayFilesTable holds the schema information for the "replay_files" table.
	ReplayFilesTable = &schema.Table{
		Name:       "replay_files",
		Columns:    ReplayFilesColumns,
		PrimaryKey: []*schema.Column{ReplayFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "replay_files_games_replay_files",
				Columns:    []*schema.Column{ReplayFilesColumns[4]},
				RefColumns: []*schema.Column{GamesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "replay_files_users_uploaded_replay_files",
				Columns:    []*schema.Column{ReplayFilesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "replayfile_file_hash",
				Unique:  false,
				Columns: []*schema.Column{ReplayFilesColumns[1]},
			},
			{
				Name:    "replayfile_game_replay_files_user_uploaded_replay_files",
				Unique:  true,
				Columns: []*schema.Column{ReplayFilesColumns[4], ReplayFilesColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "total_games", Type: field.TypeInt, Default: 0},
		{Name: "wins", Type: field.TypeInt, Default: 0},
		{Name: "losses", Type: field.TypeInt, Default: 0},
		{Name: "draws", Type: field.TypeInt, Default: 0},
		{Name: "average_apm", Type: field.TypeFloat64, Default: 0},
		{Name: "average_eapm", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnalyzerRaceMatchupsTable,
		AppSettingsTable,
		GamesTable,
		GameAnalysesTable,
		GameDetailsTable,
		PlayersTable,
		Ranking3v3Table,
		ReplayFilesTable,
		UsersTable,
	}
)

func init() {
	AnalyzerRaceMatchupsTable.Annotation = &entsql.Annotation{
		Table: "analyzer_race_matchups",
	}
	GameAnalysesTable.ForeignKeys[0].RefTable = GamesTable
	GameDetailsTable.ForeignKeys[0].RefTable = GamesTable
	PlayersTable.ForeignKeys[0].RefTable = GamesTable
	Ranking3v3Table.Annotation = &entsql.Annotation{
		Table: "ranking_3v3",
	}
	ReplayFilesTable.ForeignKeys[0].RefTable = GamesTable
	ReplayFilesTable.ForeignKeys[1].RefTable = UsersTable
}
