// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareps/ent/game"
	"github.com/xungwoo/stareps/ent/player"
)

// PlayerCreate is the builder for creating a Player entity.
type PlayerCreate struct {
	config
	mutation *PlayerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PlayerCreate) SetName(v string) *PlayerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRace sets the "race" field.
func (_c *PlayerCreate) SetRace(v string) *PlayerCreate {
	_c.mutation.SetRace(v)
	return _c
}

// SetTeam sets the "team" field.
func (_c *PlayerCreate) SetTeam(v uint8) *PlayerCreate {
	_c.mutation.SetTeam(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *PlayerCreate) SetColor(v string) *PlayerCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableColor(v *string) *PlayerCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetPlayerID sets the "player_id" field.
func (_c *PlayerCreate) SetPlayerID(v uint8) *PlayerCreate {
	_c.mutation.SetPlayerID(v)
	return _c
}

// SetApm sets the "apm" field.
func (_c *PlayerCreate) SetApm(v int32) *PlayerCreate {
	_c.mutation.SetApm(v)
	return _c
}

// SetNillableApm sets the "apm" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableApm(v *int32) *PlayerCreate {
	if v != nil {
		_c.SetApm(*v)
	}
	return _c
}

// SetEapm sets the "eapm" field.
func (_c *PlayerCreate) SetEapm(v int32) *PlayerCreate {
	_c.mutation.SetEapm(v)
	return _c
}

// SetNillableEapm sets the "eapm" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableEapm(v *int32) *PlayerCreate {
	if v != nil {
		_c.SetEapm(*v)
	}
	return _c
}

// SetCmdCount sets the "cmd_count" field.
func (_c *PlayerCreate) SetCmdCount(v uint32) *PlayerCreate {
	_c.mutation.SetCmdCount(v)
	return _c
}

// SetNillableCmdCount sets the "cmd_count" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCmdCount(v *uint32) *PlayerCreate {
	if v != nil {
		_c.SetCmdCount(*v)
	}
	return _c
}

// SetEffectiveCmdCount sets the "effective_cmd_count" field.
func (_c *PlayerCreate) SetEffectiveCmdCount(v uint32) *PlayerCreate {
	_c.mutation.SetEffectiveCmdCount(v)
	return _c
}

// SetNillableEffectiveCmdCount sets the "effective_cmd_count" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableEffectiveCmdCount(v *uint32) *PlayerCreate {
	if v != nil {
		_c.SetEffectiveCmdCount(*v)
	}
	return _c
}

// SetStartLocationX sets the "start_location_x" field.
func (_c *PlayerCreate) SetStartLocationX(v uint16) *PlayerCreate {
	_c.mutation.SetStartLocationX(v)
	return _c
}

// SetNillableStartLocationX sets the "start_location_x" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableStartLocationX(v *uint16) *PlayerCreate {
	if v != nil {
		_c.SetStartLocationX(*v)
	}
	return _c
}

// SetStartLocationY sets the "start_location_y" field.
func (_c *PlayerCreate) SetStartLocationY(v uint16) *PlayerCreate {
	_c.mutation.SetStartLocationY(v)
	return _c
}

// SetNillableStartLocationY sets the "start_location_y" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableStartLocationY(v *uint16) *PlayerCreate {
	if v != nil {
		_c.SetStartLocationY(*v)
	}
	return _c
}

// SetStartDirection sets the "start_direction" field.
func (_c *PlayerCreate) SetStartDirection(v int32) *PlayerCreate {
	_c.mutation.SetStartDirection(v)
	return _c
}

// SetNillableStartDirection sets the "start_direction" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableStartDirection(v *int32) *PlayerCreate {
	if v != nil {
		_c.SetStartDirection(*v)
	}
	return _c
}

// SetRedundancy sets the "redundancy" field.
func (_c *PlayerCreate) SetRedundancy(v int) *PlayerCreate {
	_c.mutation.SetRedundancy(v)
	return _c
}

// SetNillableRedundancy sets the "redundancy" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableRedundancy(v *int) *PlayerCreate {
	if v != nil {
		_c.SetRedundancy(*v)
	}
	return _c
}

// SetIsWinner sets the "is_winner" field.
func (_c *PlayerCreate) SetIsWinner(v bool) *PlayerCreate {
	_c.mutation.SetIsWinner(v)
	return _c
}

// SetNillableIsWinner sets the "is_winner" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableIsWinner(v *bool) *PlayerCreate {
	if v != nil {
		_c.SetIsWinner(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *PlayerCreate) SetResult(v string) *PlayerCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableResult(v *string) *PlayerCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlayerCreate) SetCreatedAt(v time.Time) *PlayerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableCreatedAt(v *time.Time) *PlayerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_c *PlayerCreate) SetGameID(id int) *PlayerCreate {
	_c.mutation.SetGameID(id)
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *PlayerCreate) SetGame(v *Game) *PlayerCreate {
	return _c.SetGameID(v.ID)
}

// Mutation returns the PlayerMutation object of the builder.
func (_c *PlayerCreate) Mutation() *PlayerMutation {
	return _c.mutation
}

// Save creates the Player in the database.
func (_c *PlayerCreate) Save(ctx context.Context) (*Player, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayerCreate) SaveX(ctx context.Context) *Player {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayerCreate) defaults() {
	if _, ok := _c.mutation.IsWinner(); !ok {
		v := player.DefaultIsWinner
		_c.mutation.SetIsWinner(v)
	}
	if _, ok := _c.mutation.Result(); !ok {
		v := player.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := player.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayerCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Player.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := player.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Player.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Race(); !ok {
		return &ValidationError{Name: "race", err: errors.New(`ent: missing required field "Player.race"`)}
	}
	if v, ok := _c.mutation.Race(); ok {
		if err := player.RaceValidator(v); err != nil {
			return &ValidationError{Name: "race", err: fmt.Errorf(`ent: validator failed for field "Player.race": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Team(); !ok {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required field "Player.team"`)}
	}
	if _, ok := _c.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player_id", err: errors.New(`ent: missing required field "Player.player_id"`)}
	}
	if _, ok := _c.mutation.IsWinner(); !ok {
		return &ValidationError{Name: "is_winner", err: errors.New(`ent: missing required field "Player.is_winner"`)}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "Player.result"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Player.created_at"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "Player.game"`)}
	}
	return nil
}

func (_c *PlayerCreate) sqlSave(ctx context.Context) (*Player, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayerCreate) createSpec() (*Player, *sqlgraph.CreateSpec) {
	var (
		_node = &Player{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(player.Table, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(player.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Race(); ok {
		_spec.SetField(player.FieldRace, field.TypeString, value)
		_node.Race = value
	}
	if value, ok := _c.mutation.Team(); ok {
		_spec.SetField(player.FieldTeam, field.TypeUint8, value)
		_node.Team = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(player.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := _c.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeUint8, value)
		_node.PlayerID = value
	}
	if value, ok := _c.mutation.Apm(); ok {
		_spec.SetField(player.FieldApm, field.TypeInt32, value)
		_node.Apm = value
	}
	if value, ok := _c.mutation.Eapm(); ok {
		_spec.SetField(player.FieldEapm, field.TypeInt32, value)
		_node.Eapm = value
	}
	if value, ok := _c.mutation.CmdCount(); ok {
		_spec.SetField(player.FieldCmdCount, field.TypeUint32, value)
		_node.CmdCount = value
	}
	if value, ok := _c.mutation.EffectiveCmdCount(); ok {
		_spec.SetField(player.FieldEffectiveCmdCount, field.TypeUint32, value)
		_node.EffectiveCmdCount = value
	}
	if value, ok := _c.mutation.StartLocationX(); ok {
		_spec.SetField(player.FieldStartLocationX, field.TypeUint16, value)
		_node.StartLocationX = value
	}
	if value, ok := _c.mutation.StartLocationY(); ok {
		_spec.SetField(player.FieldStartLocationY, field.TypeUint16, value)
		_node.StartLocationY = value
	}
	if value, ok := _c.mutation.StartDirection(); ok {
		_spec.SetField(player.FieldStartDirection, field.TypeInt32, value)
		_node.StartDirection = value
	}
	if value, ok := _c.mutation.Redundancy(); ok {
		_spec.SetField(player.FieldRedundancy, field.TypeInt, value)
		_node.Redundancy = value
	}
	if value, ok := _c.mutation.IsWinner(); ok {
		_spec.SetField(player.FieldIsWinner, field.TypeBool, value)
		_node.IsWinner = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(player.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(player.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   player.GameTable,
			Columns: []string{player.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.game_players = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlayerCreateBulk is the builder for creating many Player entities in bulk.
type PlayerCreateBulk struct {
	config
	err      error
	builders []*PlayerCreate
}

// Save creates the Player entities in the database.
func (_c *PlayerCreateBulk) Save(ctx context.Context) ([]*Player, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Player, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayerCreateBulk) SaveX(ctx context.Context) []*Player {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
