// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/xungwoo/stareplays/ent/ranking3v3"
)

// Ranking3v3 is the model entity for the Ranking3v3 schema.
type Ranking3v3 struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Rank holds the value of the "rank" field.
	Rank int `json:"rank,omitempty"`
	// Games holds the value of the "games" field.
	Games int `json:"games,omitempty"`
	// Wins holds the value of the "wins" field.
	Wins int `json:"wins,omitempty"`
	// Losses holds the value of the "losses" field.
	Losses int `json:"losses,omitempty"`
	// Draws holds the value of the "draws" field.
	Draws int `json:"draws,omitempty"`
	// WinRate holds the value of the "win_rate" field.
	WinRate float64 `json:"win_rate,omitempty"`
	// AvgApm holds the value of the "avg_apm" field.
	AvgApm float64 `json:"avg_apm,omitempty"`
	// AvgEapm holds the value of the "avg_eapm" field.
	AvgEapm float64 `json:"avg_eapm,omitempty"`
	// minimum games threshold used for this snapshot
	MinGames int `json:"min_games,omitempty"`
	// ComputedAt holds the value of the "computed_at" field.
	ComputedAt time.Time `json:"computed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ranking3v3) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ranking3v3.FieldWinRate, ranking3v3.FieldAvgApm, ranking3v3.FieldAvgEapm:
			values[i] = new(sql.NullFloat64)
		case ranking3v3.FieldID, ranking3v3.FieldRank, ranking3v3.FieldGames, ranking3v3.FieldWins, ranking3v3.FieldLosses, ranking3v3.FieldDraws, ranking3v3.FieldMinGames:
			values[i] = new(sql.NullInt64)
		case ranking3v3.FieldName:
			values[i] = new(sql.NullString)
		case ranking3v3.FieldComputedAt, ranking3v3.FieldCreatedAt, ranking3v3.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ranking3v3 fields.
func (_m *Ranking3v3) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ranking3v3.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ranking3v3.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ranking3v3.FieldRank:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rank", values[i])
			} else if value.Valid {
				_m.Rank = int(value.Int64)
			}
		case ranking3v3.FieldGames:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field games", values[i])
			} else if value.Valid {
				_m.Games = int(value.Int64)
			}
		case ranking3v3.FieldWins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field wins", values[i])
			} else if value.Valid {
				_m.Wins = int(value.Int64)
			}
		case ranking3v3.FieldLosses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field losses", values[i])
			} else if value.Valid {
				_m.Losses = int(value.Int64)
			}
		case ranking3v3.FieldDraws:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draws", values[i])
			} else if value.Valid {
				_m.Draws = int(value.Int64)
			}
		case ranking3v3.FieldWinRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field win_rate", values[i])
			} else if value.Valid {
				_m.WinRate = value.Float64
			}
		case ranking3v3.FieldAvgApm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_apm", values[i])
			} else if value.Valid {
				_m.AvgApm = value.Float64
			}
		case ranking3v3.FieldAvgEapm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_eapm", values[i])
			} else if value.Valid {
				_m.AvgEapm = value.Float64
			}
		case ranking3v3.FieldMinGames:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_games", values[i])
			} else if value.Valid {
				_m.MinGames = int(value.Int64)
			}
		case ranking3v3.FieldComputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field computed_at", values[i])
			} else if value.Valid {
				_m.ComputedAt = value.Time
			}
		case ranking3v3.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ranking3v3.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ranking3v3.
// This includes values selected through modifiers, order, etc.
func (_m *Ranking3v3) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Ranking3v3.
// Note that you need to call Ranking3v3.Unwrap() before calling this method if this Ranking3v3
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ranking3v3) Update() *Ranking3v3UpdateOne {
	return NewRanking3v3Client(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ranking3v3 entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ranking3v3) Unwrap() *Ranking3v3 {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ranking3v3 is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ranking3v3) String() string {
	var builder strings.Builder
	builder.WriteString("Ranking3v3(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("rank=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rank))
	builder.WriteString(", ")
	builder.WriteString("games=")
	builder.WriteString(fmt.Sprintf("%v", _m.Games))
	builder.WriteString(", ")
	builder.WriteString("wins=")
	builder.WriteString(fmt.Sprintf("%v", _m.Wins))
	builder.WriteString(", ")
	builder.WriteString("losses=")
	builder.WriteString(fmt.Sprintf("%v", _m.Losses))
	builder.WriteString(", ")
	builder.WriteString("draws=")
	builder.WriteString(fmt.Sprintf("%v", _m.Draws))
	builder.WriteString(", ")
	builder.WriteString("win_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.WinRate))
	builder.WriteString(", ")
	builder.WriteString("avg_apm=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgApm))
	builder.WriteString(", ")
	builder.WriteString("avg_eapm=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgEapm))
	builder.WriteString(", ")
	builder.WriteString("min_games=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinGames))
	builder.WriteString(", ")
	builder.WriteString("computed_at=")
	builder.WriteString(_m.ComputedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Ranking3v3s is a parsable slice of Ranking3v3.
type Ranking3v3s []*Ranking3v3
