// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xungwoo/stareps/ent/replayfile"
	"github.com/xungwoo/stareps/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTotalGames sets the "total_games" field.
func (_c *UserCreate) SetTotalGames(v int) *UserCreate {
	_c.mutation.SetTotalGames(v)
	return _c
}

// SetNillableTotalGames sets the "total_games" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotalGames(v *int) *UserCreate {
	if v != nil {
		_c.SetTotalGames(*v)
	}
	return _c
}

// SetWins sets the "wins" field.
func (_c *UserCreate) SetWins(v int) *UserCreate {
	_c.mutation.SetWins(v)
	return _c
}

// SetNillableWins sets the "wins" field if the given value is not nil.
func (_c *UserCreate) SetNillableWins(v *int) *UserCreate {
	if v != nil {
		_c.SetWins(*v)
	}
	return _c
}

// SetLosses sets the "losses" field.
func (_c *UserCreate) SetLosses(v int) *UserCreate {
	_c.mutation.SetLosses(v)
	return _c
}

// SetNillableLosses sets the "losses" field if the given value is not nil.
func (_c *UserCreate) SetNillableLosses(v *int) *UserCreate {
	if v != nil {
		_c.SetLosses(*v)
	}
	return _c
}

// SetDraws sets the "draws" field.
func (_c *UserCreate) SetDraws(v int) *UserCreate {
	_c.mutation.SetDraws(v)
	return _c
}

// SetNillableDraws sets the "draws" field if the given value is not nil.
func (_c *UserCreate) SetNillableDraws(v *int) *UserCreate {
	if v != nil {
		_c.SetDraws(*v)
	}
	return _c
}

// SetAverageApm sets the "average_apm" field.
func (_c *UserCreate) SetAverageApm(v float64) *UserCreate {
	_c.mutation.SetAverageApm(v)
	return _c
}

// SetNillableAverageApm sets the "average_apm" field if the given value is not nil.
func (_c *UserCreate) SetNillableAverageApm(v *float64) *UserCreate {
	if v != nil {
		_c.SetAverageApm(*v)
	}
	return _c
}

// SetAverageEapm sets the "average_eapm" field.
func (_c *UserCreate) SetAverageEapm(v float64) *UserCreate {
	_c.mutation.SetAverageEapm(v)
	return _c
}

// SetNillableAverageEapm sets the "average_eapm" field if the given value is not nil.
func (_c *UserCreate) SetNillableAverageEapm(v *float64) *UserCreate {
	if v != nil {
		_c.SetAverageEapm(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUploadedReplayFileIDs adds the "uploaded_replay_files" edge to the ReplayFile entity by IDs.
func (_c *UserCreate) AddUploadedReplayFileIDs(ids ...int) *UserCreate {
	_c.mutation.AddUploadedReplayFileIDs(ids...)
	return _c
}

// AddUploadedReplayFiles adds the "uploaded_replay_files" edges to the ReplayFile entity.
func (_c *UserCreate) AddUploadedReplayFiles(v ...*ReplayFile) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUploadedReplayFileIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.TotalGames(); !ok {
		v := user.DefaultTotalGames
		_c.mutation.SetTotalGames(v)
	}
	if _, ok := _c.mutation.Wins(); !ok {
		v := user.DefaultWins
		_c.mutation.SetWins(v)
	}
	if _, ok := _c.mutation.Losses(); !ok {
		v := user.DefaultLosses
		_c.mutation.SetLosses(v)
	}
	if _, ok := _c.mutation.Draws(); !ok {
		v := user.DefaultDraws
		_c.mutation.SetDraws(v)
	}
	if _, ok := _c.mutation.AverageApm(); !ok {
		v := user.DefaultAverageApm
		_c.mutation.SetAverageApm(v)
	}
	if _, ok := _c.mutation.AverageEapm(); !ok {
		v := user.DefaultAverageEapm
		_c.mutation.SetAverageEapm(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalGames(); !ok {
		return &ValidationError{Name: "total_games", err: errors.New(`ent: missing required field "User.total_games"`)}
	}
	if _, ok := _c.mutation.Wins(); !ok {
		return &ValidationError{Name: "wins", err: errors.New(`ent: missing required field "User.wins"`)}
	}
	if _, ok := _c.mutation.Losses(); !ok {
		return &ValidationError{Name: "losses", err: errors.New(`ent: missing required field "User.losses"`)}
	}
	if _, ok := _c.mutation.Draws(); !ok {
		return &ValidationError{Name: "draws", err: errors.New(`ent: missing required field "User.draws"`)}
	}
	if _, ok := _c.mutation.AverageApm(); !ok {
		return &ValidationError{Name: "average_apm", err: errors.New(`ent: missing required field "User.average_apm"`)}
	}
	if _, ok := _c.mutation.AverageEapm(); !ok {
		return &ValidationError{Name: "average_eapm", err: errors.New(`ent: missing required field "User.average_eapm"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TotalGames(); ok {
		_spec.SetField(user.FieldTotalGames, field.TypeInt, value)
		_node.TotalGames = value
	}
	if value, ok := _c.mutation.Wins(); ok {
		_spec.SetField(user.FieldWins, field.TypeInt, value)
		_node.Wins = value
	}
	if value, ok := _c.mutation.Losses(); ok {
		_spec.SetField(user.FieldLosses, field.TypeInt, value)
		_node.Losses = value
	}
	if value, ok := _c.mutation.Draws(); ok {
		_spec.SetField(user.FieldDraws, field.TypeInt, value)
		_node.Draws = value
	}
	if value, ok := _c.mutation.AverageApm(); ok {
		_spec.SetField(user.FieldAverageApm, field.TypeFloat64, value)
		_node.AverageApm = value
	}
	if value, ok := _c.mutation.AverageEapm(); ok {
		_spec.SetField(user.FieldAverageEapm, field.TypeFloat64, value)
		_node.AverageEapm = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UploadedReplayFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UploadedReplayFilesTable,
			Columns: []string{user.UploadedReplayFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(replayfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
