// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/xungwoo/stareps/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TotalGames holds the value of the "total_games" field.
	TotalGames int `json:"total_games,omitempty"`
	// Wins holds the value of the "wins" field.
	Wins int `json:"wins,omitempty"`
	// Losses holds the value of the "losses" field.
	Losses int `json:"losses,omitempty"`
	// Draws holds the value of the "draws" field.
	Draws int `json:"draws,omitempty"`
	// AverageApm holds the value of the "average_apm" field.
	AverageApm float64 `json:"average_apm,omitempty"`
	// AverageEapm holds the value of the "average_eapm" field.
	AverageEapm float64 `json:"average_eapm,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// UploadedReplayFiles holds the value of the uploaded_replay_files edge.
	UploadedReplayFiles []*ReplayFile `json:"uploaded_replay_files,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UploadedReplayFilesOrErr returns the UploadedReplayFiles value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UploadedReplayFilesOrErr() ([]*ReplayFile, error) {
	if e.loadedTypes[0] {
		return e.UploadedReplayFiles, nil
	}
	return nil, &NotLoadedError{edge: "uploaded_replay_files"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldAverageApm, user.FieldAverageEapm:
			values[i] = new(sql.NullFloat64)
		case user.FieldID, user.FieldTotalGames, user.FieldWins, user.FieldLosses, user.FieldDraws:
			values[i] = new(sql.NullInt64)
		case user.FieldName:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldTotalGames:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_games", values[i])
			} else if value.Valid {
				_m.TotalGames = int(value.Int64)
			}
		case user.FieldWins:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field wins", values[i])
			} else if value.Valid {
				_m.Wins = int(value.Int64)
			}
		case user.FieldLosses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field losses", values[i])
			} else if value.Valid {
				_m.Losses = int(value.Int64)
			}
		case user.FieldDraws:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field draws", values[i])
			} else if value.Valid {
				_m.Draws = int(value.Int64)
			}
		case user.FieldAverageApm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field average_apm", values[i])
			} else if value.Valid {
				_m.AverageApm = value.Float64
			}
		case user.FieldAverageEapm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field average_eapm", values[i])
			} else if value.Valid {
				_m.AverageEapm = value.Float64
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUploadedReplayFiles queries the "uploaded_replay_files" edge of the User entity.
func (_m *User) QueryUploadedReplayFiles() *ReplayFileQuery {
	return NewUserClient(_m.config).QueryUploadedReplayFiles(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("total_games=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalGames))
	builder.WriteString(", ")
	builder.WriteString("wins=")
	builder.WriteString(fmt.Sprintf("%v", _m.Wins))
	builder.WriteString(", ")
	builder.WriteString("losses=")
	builder.WriteString(fmt.Sprintf("%v", _m.Losses))
	builder.WriteString(", ")
	builder.WriteString("draws=")
	builder.WriteString(fmt.Sprintf("%v", _m.Draws))
	builder.WriteString(", ")
	builder.WriteString("average_apm=")
	builder.WriteString(fmt.Sprintf("%v", _m.AverageApm))
	builder.WriteString(", ")
	builder.WriteString("average_eapm=")
	builder.WriteString(fmt.Sprintf("%v", _m.AverageEapm))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
