// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldMapName holds the string denoting the map_name field in the database.
	FieldMapName = "map_name"
	// FieldMapWidth holds the string denoting the map_width field in the database.
	FieldMapWidth = "map_width"
	// FieldMapHeight holds the string denoting the map_height field in the database.
	FieldMapHeight = "map_height"
	// FieldGameLength holds the string denoting the game_length field in the database.
	FieldGameLength = "game_length"
	// FieldGameType holds the string denoting the game_type field in the database.
	FieldGameType = "game_type"
	// FieldGameSpeed holds the string denoting the game_speed field in the database.
	FieldGameSpeed = "game_speed"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldPlayerCount holds the string denoting the player_count field in the database.
	FieldPlayerCount = "player_count"
	// FieldUploadCount holds the string denoting the upload_count field in the database.
	FieldUploadCount = "upload_count"
	// FieldWinnerTeam holds the string denoting the winner_team field in the database.
	FieldWinnerTeam = "winner_team"
	// FieldSeasonLabel holds the string denoting the season_label field in the database.
	FieldSeasonLabel = "season_label"
	// FieldSeasonNo holds the string denoting the season_no field in the database.
	FieldSeasonNo = "season_no"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlayers holds the string denoting the players edge name in mutations.
	EdgePlayers = "players"
	// EdgeReplayFiles holds the string denoting the replay_files edge name in mutations.
	EdgeReplayFiles = "replay_files"
	// EdgeGameDetail holds the string denoting the game_detail edge name in mutations.
	EdgeGameDetail = "game_detail"
	// EdgeAnalysis holds the string denoting the analysis edge name in mutations.
	EdgeAnalysis = "analysis"
	// Table holds the table name of the game in the database.
	Table = "games"
	// PlayersTable is the table that holds the players relation/edge.
	PlayersTable = "players"
	// PlayersInverseTable is the table name for the Player entity.
	// It exists in this package in order to avoid circular dependency with the "player" package.
	PlayersInverseTable = "players"
	// PlayersColumn is the table column denoting the players relation/edge.
	PlayersColumn = "game_players"
	// ReplayFilesTable is the table that holds the replay_files relation/edge.
	ReplayFilesTable = "replay_files"
	// ReplayFilesInverseTable is the table name for the ReplayFile entity.
	// It exists in this package in order to avoid circular dependency with the "replayfile" package.
	ReplayFilesInverseTable = "replay_files"
	// ReplayFilesColumn is the table column denoting the replay_files relation/edge.
	ReplayFilesColumn = "game_replay_files"
	// GameDetailTable is the table that holds the game_detail relation/edge.
	GameDetailTable = "game_details"
	// GameDetailInverseTable is the table name for the GameDetail entity.
	// It exists in this package in order to avoid circular dependency with the "gamedetail" package.
	GameDetailInverseTable = "game_details"
	// GameDetailColumn is the table column denoting the game_detail relation/edge.
	GameDetailColumn = "game_game_detail"
	// AnalysisTable is the table that holds the analysis relation/edge.
	AnalysisTable = "game_analyses"
	// AnalysisInverseTable is the table name for the GameAnalysis entity.
	// It exists in this package in order to avoid circular dependency with the "gameanalysis" package.
	AnalysisInverseTable = "game_analyses"
	// AnalysisColumn is the table column denoting the analysis relation/edge.
	AnalysisColumn = "game_id"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldHost,
	FieldStartTime,
	FieldMapName,
	FieldMapWidth,
	FieldMapHeight,
	FieldGameLength,
	FieldGameType,
	FieldGameSpeed,
	FieldTitle,
	FieldPlayerCount,
	FieldUploadCount,
	FieldWinnerTeam,
	FieldSeasonLabel,
	FieldSeasonNo,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// HostValidator is a validator for the "host" field. It is called by the builders before save.
	HostValidator func(string) error
	// DefaultPlayerCount holds the default value on creation for the "player_count" field.
	DefaultPlayerCount int
	// DefaultUploadCount holds the default value on creation for the "upload_count" field.
	DefaultUploadCount int
	// DefaultWinnerTeam holds the default value on creation for the "winner_team" field.
	DefaultWinnerTeam uint8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByMapName orders the results by the map_name field.
func ByMapName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMapName, opts...).ToFunc()
}

// ByMapWidth orders the results by the map_width field.
func ByMapWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMapWidth, opts...).ToFunc()
}

// ByMapHeight orders the results by the map_height field.
func ByMapHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMapHeight, opts...).ToFunc()
}

// ByGameLength orders the results by the game_length field.
func ByGameLength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameLength, opts...).ToFunc()
}

// ByGameType orders the results by the game_type field.
func ByGameType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameType, opts...).ToFunc()
}

// ByGameSpeed orders the results by the game_speed field.
func ByGameSpeed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameSpeed, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByPlayerCount orders the results by the player_count field.
func ByPlayerCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerCount, opts...).ToFunc()
}

// ByUploadCount orders the results by the upload_count field.
func ByUploadCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadCount, opts...).ToFunc()
}

// ByWinnerTeam orders the results by the winner_team field.
func ByWinnerTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWinnerTeam, opts...).ToFunc()
}

// BySeasonLabel orders the results by the season_label field.
func BySeasonLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonLabel, opts...).ToFunc()
}

// BySeasonNo orders the results by the season_no field.
func BySeasonNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonNo, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlayersCount orders the results by players count.
func ByPlayersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlayersStep(), opts...)
	}
}

// ByPlayers orders the results by players terms.
func ByPlayers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReplayFilesCount orders the results by replay_files count.
func ByReplayFilesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReplayFilesStep(), opts...)
	}
}

// ByReplayFiles orders the results by replay_files terms.
func ByReplayFiles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReplayFilesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGameDetailField orders the results by game_detail field.
func ByGameDetailField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGameDetailStep(), sql.OrderByField(field, opts...))
	}
}

// ByAnalysisField orders the results by analysis field.
func ByAnalysisField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnalysisStep(), sql.OrderByField(field, opts...))
	}
}
func newPlayersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlayersTable, PlayersColumn),
	)
}
func newReplayFilesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReplayFilesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReplayFilesTable, ReplayFilesColumn),
	)
}
func newGameDetailStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GameDetailInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, GameDetailTable, GameDetailColumn),
	)
}
func newAnalysisStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnalysisInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, AnalysisTable, AnalysisColumn),
	)
}
