// Code generated by ent, DO NOT EDIT.

package gameanalysis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the gameanalysis type in the database.
	Label = "game_analysis"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// FieldFileHash holds the string denoting the file_hash field in the database.
	FieldFileHash = "file_hash"
	// FieldBucketKey holds the string denoting the bucket_key field in the database.
	FieldBucketKey = "bucket_key"
	// FieldAnalyzerVersion holds the string denoting the analyzer_version field in the database.
	FieldAnalyzerVersion = "analyzer_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldRequestedAt holds the string denoting the requested_at field in the database.
	FieldRequestedAt = "requested_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldNextRetryAt holds the string denoting the next_retry_at field in the database.
	FieldNextRetryAt = "next_retry_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldQualityReportJSON holds the string denoting the quality_report_json field in the database.
	FieldQualityReportJSON = "quality_report_json"
	// FieldSummaryJSON holds the string denoting the summary_json field in the database.
	FieldSummaryJSON = "summary_json"
	// FieldAnalysisPhaseJSON holds the string denoting the analysis_phase_json field in the database.
	FieldAnalysisPhaseJSON = "analysis_phase_json"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeGame holds the string denoting the game edge name in mutations.
	EdgeGame = "game"
	// Table holds the table name of the gameanalysis in the database.
	Table = "game_analyses"
	// GameTable is the table that holds the game relation/edge.
	GameTable = "game_analyses"
	// GameInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GameInverseTable = "games"
	// GameColumn is the table column denoting the game relation/edge.
	GameColumn = "game_id"
)

// Columns holds all SQL columns for gameanalysis fields.
var Columns = []string{
	FieldID,
	FieldGameID,
	FieldFileHash,
	FieldBucketKey,
	FieldAnalyzerVersion,
	FieldStatus,
	FieldAttemptCount,
	FieldPriority,
	FieldRequestedAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldNextRetryAt,
	FieldLastError,
	FieldQualityReportJSON,
	FieldSummaryJSON,
	FieldAnalysisPhaseJSON,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GameIDValidator is a validator for the "game_id" field. It is called by the builders before save.
	GameIDValidator func(int) error
	// FileHashValidator is a validator for the "file_hash" field. It is called by the builders before save.
	FileHashValidator func(string) error
	// BucketKeyValidator is a validator for the "bucket_key" field. It is called by the builders before save.
	BucketKeyValidator func(string) error
	// DefaultAnalyzerVersion holds the default value on creation for the "analyzer_version" field.
	DefaultAnalyzerVersion string
	// AnalyzerVersionValidator is a validator for the "analyzer_version" field. It is called by the builders before save.
	AnalyzerVersionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultRequestedAt holds the default value on creation for the "requested_at" field.
	DefaultRequestedAt func() time.Time
	// DefaultNextRetryAt holds the default value on creation for the "next_retry_at" field.
	DefaultNextRetryAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GameAnalysis queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGameID orders the results by the game_id field.
func ByGameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameID, opts...).ToFunc()
}

// ByFileHash orders the results by the file_hash field.
func ByFileHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileHash, opts...).ToFunc()
}

// ByBucketKey orders the results by the bucket_key field.
func ByBucketKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketKey, opts...).ToFunc()
}

// ByAnalyzerVersion orders the results by the analyzer_version field.
func ByAnalyzerVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalyzerVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByRequestedAt orders the results by the requested_at field.
func ByRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the next_retry_at field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGameField orders the results by game field.
func ByGameField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGameStep(), sql.OrderByField(field, opts...))
	}
}
func newGameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, GameTable, GameColumn),
	)
}
