// Code generated by ent, DO NOT EDIT.

package gameanalysis

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/xungwoo/stareplays/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldID, id))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldGameID, v))
}

// FileHash applies equality check predicate on the "file_hash" field. It's identical to FileHashEQ.
func FileHash(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldFileHash, v))
}

// BucketKey applies equality check predicate on the "bucket_key" field. It's identical to BucketKeyEQ.
func BucketKey(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldBucketKey, v))
}

// AnalyzerVersion applies equality check predicate on the "analyzer_version" field. It's identical to AnalyzerVersionEQ.
func AnalyzerVersion(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldAnalyzerVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldStatus, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldAttemptCount, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldPriority, v))
}

// RequestedAt applies equality check predicate on the "requested_at" field. It's identical to RequestedAtEQ.
func RequestedAt(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldRequestedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldFinishedAt, v))
}

// NextRetryAt applies equality check predicate on the "next_retry_at" field. It's identical to NextRetryAtEQ.
func NextRetryAt(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldNextRetryAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldUpdatedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldGameID, vs...))
}

// FileHashEQ applies the EQ predicate on the "file_hash" field.
func FileHashEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldFileHash, v))
}

// FileHashNEQ applies the NEQ predicate on the "file_hash" field.
func FileHashNEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldFileHash, v))
}

// FileHashIn applies the In predicate on the "file_hash" field.
func FileHashIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldFileHash, vs...))
}

// FileHashNotIn applies the NotIn predicate on the "file_hash" field.
func FileHashNotIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldFileHash, vs...))
}

// FileHashGT applies the GT predicate on the "file_hash" field.
func FileHashGT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldFileHash, v))
}

// FileHashGTE applies the GTE predicate on the "file_hash" field.
func FileHashGTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldFileHash, v))
}

// FileHashLT applies the LT predicate on the "file_hash" field.
func FileHashLT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldFileHash, v))
}

// FileHashLTE applies the LTE predicate on the "file_hash" field.
func FileHashLTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldFileHash, v))
}

// FileHashContains applies the Contains predicate on the "file_hash" field.
func FileHashContains(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContains(FieldFileHash, v))
}

// FileHashHasPrefix applies the HasPrefix predicate on the "file_hash" field.
func FileHashHasPrefix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasPrefix(FieldFileHash, v))
}

// FileHashHasSuffix applies the HasSuffix predicate on the "file_hash" field.
func FileHashHasSuffix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasSuffix(FieldFileHash, v))
}

// FileHashEqualFold applies the EqualFold predicate on the "file_hash" field.
func FileHashEqualFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEqualFold(FieldFileHash, v))
}

// FileHashContainsFold applies the ContainsFold predicate on the "file_hash" field.
func FileHashContainsFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContainsFold(FieldFileHash, v))
}

// BucketKeyEQ applies the EQ predicate on the "bucket_key" field.
func BucketKeyEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldBucketKey, v))
}

// BucketKeyNEQ applies the NEQ predicate on the "bucket_key" field.
func BucketKeyNEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldBucketKey, v))
}

// BucketKeyIn applies the In predicate on the "bucket_key" field.
func BucketKeyIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldBucketKey, vs...))
}

// BucketKeyNotIn applies the NotIn predicate on the "bucket_key" field.
func BucketKeyNotIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldBucketKey, vs...))
}

// BucketKeyGT applies the GT predicate on the "bucket_key" field.
func BucketKeyGT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldBucketKey, v))
}

// BucketKeyGTE applies the GTE predicate on the "bucket_key" field.
func BucketKeyGTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldBucketKey, v))
}

// BucketKeyLT applies the LT predicate on the "bucket_key" field.
func BucketKeyLT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldBucketKey, v))
}

// BucketKeyLTE applies the LTE predicate on the "bucket_key" field.
func BucketKeyLTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldBucketKey, v))
}

// BucketKeyContains applies the Contains predicate on the "bucket_key" field.
func BucketKeyContains(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContains(FieldBucketKey, v))
}

// BucketKeyHasPrefix applies the HasPrefix predicate on the "bucket_key" field.
func BucketKeyHasPrefix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasPrefix(FieldBucketKey, v))
}

// BucketKeyHasSuffix applies the HasSuffix predicate on the "bucket_key" field.
func BucketKeyHasSuffix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasSuffix(FieldBucketKey, v))
}

// BucketKeyEqualFold applies the EqualFold predicate on the "bucket_key" field.
func BucketKeyEqualFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEqualFold(FieldBucketKey, v))
}

// BucketKeyContainsFold applies the ContainsFold predicate on the "bucket_key" field.
func BucketKeyContainsFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContainsFold(FieldBucketKey, v))
}

// AnalyzerVersionEQ applies the EQ predicate on the "analyzer_version" field.
func AnalyzerVersionEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldAnalyzerVersion, v))
}

// AnalyzerVersionNEQ applies the NEQ predicate on the "analyzer_version" field.
func AnalyzerVersionNEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldAnalyzerVersion, v))
}

// AnalyzerVersionIn applies the In predicate on the "analyzer_version" field.
func AnalyzerVersionIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldAnalyzerVersion, vs...))
}

// AnalyzerVersionNotIn applies the NotIn predicate on the "analyzer_version" field.
func AnalyzerVersionNotIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldAnalyzerVersion, vs...))
}

// AnalyzerVersionGT applies the GT predicate on the "analyzer_version" field.
func AnalyzerVersionGT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldAnalyzerVersion, v))
}

// AnalyzerVersionGTE applies the GTE predicate on the "analyzer_version" field.
func AnalyzerVersionGTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldAnalyzerVersion, v))
}

// AnalyzerVersionLT applies the LT predicate on the "analyzer_version" field.
func AnalyzerVersionLT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldAnalyzerVersion, v))
}

// AnalyzerVersionLTE applies the LTE predicate on the "analyzer_version" field.
func AnalyzerVersionLTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldAnalyzerVersion, v))
}

// AnalyzerVersionContains applies the Contains predicate on the "analyzer_version" field.
func AnalyzerVersionContains(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContains(FieldAnalyzerVersion, v))
}

// AnalyzerVersionHasPrefix applies the HasPrefix predicate on the "analyzer_version" field.
func AnalyzerVersionHasPrefix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasPrefix(FieldAnalyzerVersion, v))
}

// AnalyzerVersionHasSuffix applies the HasSuffix predicate on the "analyzer_version" field.
func AnalyzerVersionHasSuffix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasSuffix(FieldAnalyzerVersion, v))
}

// AnalyzerVersionEqualFold applies the EqualFold predicate on the "analyzer_version" field.
func AnalyzerVersionEqualFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEqualFold(FieldAnalyzerVersion, v))
}

// AnalyzerVersionContainsFold applies the ContainsFold predicate on the "analyzer_version" field.
func AnalyzerVersionContainsFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContainsFold(FieldAnalyzerVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContainsFold(FieldStatus, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldAttemptCount, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldPriority, v))
}

// RequestedAtEQ applies the EQ predicate on the "requested_at" field.
func RequestedAtEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldRequestedAt, v))
}

// RequestedAtNEQ applies the NEQ predicate on the "requested_at" field.
func RequestedAtNEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldRequestedAt, v))
}

// RequestedAtIn applies the In predicate on the "requested_at" field.
func RequestedAtIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldRequestedAt, vs...))
}

// RequestedAtNotIn applies the NotIn predicate on the "requested_at" field.
func RequestedAtNotIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldRequestedAt, vs...))
}

// RequestedAtGT applies the GT predicate on the "requested_at" field.
func RequestedAtGT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldRequestedAt, v))
}

// RequestedAtGTE applies the GTE predicate on the "requested_at" field.
func RequestedAtGTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldRequestedAt, v))
}

// RequestedAtLT applies the LT predicate on the "requested_at" field.
func RequestedAtLT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldRequestedAt, v))
}

// RequestedAtLTE applies the LTE predicate on the "requested_at" field.
func RequestedAtLTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldRequestedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotNull(FieldFinishedAt))
}

// NextRetryAtEQ applies the EQ predicate on the "next_retry_at" field.
func NextRetryAtEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldNextRetryAt, v))
}

// NextRetryAtNEQ applies the NEQ predicate on the "next_retry_at" field.
func NextRetryAtNEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldNextRetryAt, v))
}

// NextRetryAtIn applies the In predicate on the "next_retry_at" field.
func NextRetryAtIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldNextRetryAt, vs...))
}

// NextRetryAtNotIn applies the NotIn predicate on the "next_retry_at" field.
func NextRetryAtNotIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldNextRetryAt, vs...))
}

// NextRetryAtGT applies the GT predicate on the "next_retry_at" field.
func NextRetryAtGT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldNextRetryAt, v))
}

// NextRetryAtGTE applies the GTE predicate on the "next_retry_at" field.
func NextRetryAtGTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldNextRetryAt, v))
}

// NextRetryAtLT applies the LT predicate on the "next_retry_at" field.
func NextRetryAtLT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldNextRetryAt, v))
}

// NextRetryAtLTE applies the LTE predicate on the "next_retry_at" field.
func NextRetryAtLTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldNextRetryAt, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldContainsFold(FieldLastError, v))
}

// QualityReportJSONIsNil applies the IsNil predicate on the "quality_report_json" field.
func QualityReportJSONIsNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIsNull(FieldQualityReportJSON))
}

// QualityReportJSONNotNil applies the NotNil predicate on the "quality_report_json" field.
func QualityReportJSONNotNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotNull(FieldQualityReportJSON))
}

// SummaryJSONIsNil applies the IsNil predicate on the "summary_json" field.
func SummaryJSONIsNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIsNull(FieldSummaryJSON))
}

// SummaryJSONNotNil applies the NotNil predicate on the "summary_json" field.
func SummaryJSONNotNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotNull(FieldSummaryJSON))
}

// AnalysisPhaseJSONIsNil applies the IsNil predicate on the "analysis_phase_json" field.
func AnalysisPhaseJSONIsNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIsNull(FieldAnalysisPhaseJSON))
}

// AnalysisPhaseJSONNotNil applies the NotNil predicate on the "analysis_phase_json" field.
func AnalysisPhaseJSONNotNil() predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotNull(FieldAnalysisPhaseJSON))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.GameAnalysis {
	return predicate.GameAnalysis(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.GameAnalysis {
	return predicate.GameAnalysis(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameAnalysis) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameAnalysis) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameAnalysis) predicate.GameAnalysis {
	return predicate.GameAnalysis(sql.NotPredicates(p))
}
