// Code generated by ent, DO NOT EDIT.

package replayfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/xungwoo/stareps/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLTE(FieldID, id))
}

// FileHash applies equality check predicate on the "file_hash" field. It's identical to FileHashEQ.
func FileHash(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldFileHash, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldFilename, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldCreatedAt, v))
}

// FileHashEQ applies the EQ predicate on the "file_hash" field.
func FileHashEQ(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldFileHash, v))
}

// FileHashNEQ applies the NEQ predicate on the "file_hash" field.
func FileHashNEQ(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNEQ(FieldFileHash, v))
}

// FileHashIn applies the In predicate on the "file_hash" field.
func FileHashIn(vs ...string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldIn(FieldFileHash, vs...))
}

// FileHashNotIn applies the NotIn predicate on the "file_hash" field.
func FileHashNotIn(vs ...string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNotIn(FieldFileHash, vs...))
}

// FileHashGT applies the GT predicate on the "file_hash" field.
func FileHashGT(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGT(FieldFileHash, v))
}

// FileHashGTE applies the GTE predicate on the "file_hash" field.
func FileHashGTE(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGTE(FieldFileHash, v))
}

// FileHashLT applies the LT predicate on the "file_hash" field.
func FileHashLT(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLT(FieldFileHash, v))
}

// FileHashLTE applies the LTE predicate on the "file_hash" field.
func FileHashLTE(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLTE(FieldFileHash, v))
}

// FileHashContains applies the Contains predicate on the "file_hash" field.
func FileHashContains(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldContains(FieldFileHash, v))
}

// FileHashHasPrefix applies the HasPrefix predicate on the "file_hash" field.
func FileHashHasPrefix(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldHasPrefix(FieldFileHash, v))
}

// FileHashHasSuffix applies the HasSuffix predicate on the "file_hash" field.
func FileHashHasSuffix(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldHasSuffix(FieldFileHash, v))
}

// FileHashEqualFold applies the EqualFold predicate on the "file_hash" field.
func FileHashEqualFold(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEqualFold(FieldFileHash, v))
}

// FileHashContainsFold applies the ContainsFold predicate on the "file_hash" field.
func FileHashContainsFold(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldContainsFold(FieldFileHash, v))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldContainsFold(FieldFilename, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReplayFile {
	return predicate.ReplayFile(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.ReplayFile {
	return predicate.ReplayFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.ReplayFile {
	return predicate.ReplayFile(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploader applies the HasEdge predicate on the "uploader" edge.
func HasUploader() predicate.ReplayFile {
	return predicate.ReplayFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UploaderTable, UploaderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploaderWith applies the HasEdge predicate on the "uploader" edge with a given conditions (other predicates).
func HasUploaderWith(preds ...predicate.User) predicate.ReplayFile {
	return predicate.ReplayFile(func(s *sql.Selector) {
		step := newUploaderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReplayFile) predicate.ReplayFile {
	return predicate.ReplayFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReplayFile) predicate.ReplayFile {
	return predicate.ReplayFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReplayFile) predicate.ReplayFile {
	return predicate.ReplayFile(sql.NotPredicates(p))
}
