// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTotalGames holds the string denoting the total_games field in the database.
	FieldTotalGames = "total_games"
	// FieldWins holds the string denoting the wins field in the database.
	FieldWins = "wins"
	// FieldLosses holds the string denoting the losses field in the database.
	FieldLosses = "losses"
	// FieldDraws holds the string denoting the draws field in the database.
	FieldDraws = "draws"
	// FieldAverageApm holds the string denoting the average_apm field in the database.
	FieldAverageApm = "average_apm"
	// FieldAverageEapm holds the string denoting the average_eapm field in the database.
	FieldAverageEapm = "average_eapm"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUploadedReplayFiles holds the string denoting the uploaded_replay_files edge name in mutations.
	EdgeUploadedReplayFiles = "uploaded_replay_files"
	// Table holds the table name of the user in the database.
	Table = "users"
	// UploadedReplayFilesTable is the table that holds the uploaded_replay_files relation/edge.
	UploadedReplayFilesTable = "replay_files"
	// UploadedReplayFilesInverseTable is the table name for the ReplayFile entity.
	// It exists in this package in order to avoid circular dependency with the "replayfile" package.
	UploadedReplayFilesInverseTable = "replay_files"
	// UploadedReplayFilesColumn is the table column denoting the uploaded_replay_files relation/edge.
	UploadedReplayFilesColumn = "user_uploaded_replay_files"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTotalGames,
	FieldWins,
	FieldLosses,
	FieldDraws,
	FieldAverageApm,
	FieldAverageEapm,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultTotalGames holds the default value on creation for the "total_games" field.
	DefaultTotalGames int
	// DefaultWins holds the default value on creation for the "wins" field.
	DefaultWins int
	// DefaultLosses holds the default value on creation for the "losses" field.
	DefaultLosses int
	// DefaultDraws holds the default value on creation for the "draws" field.
	DefaultDraws int
	// DefaultAverageApm holds the default value on creation for the "average_apm" field.
	DefaultAverageApm float64
	// DefaultAverageEapm holds the default value on creation for the "average_eapm" field.
	DefaultAverageEapm float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTotalGames orders the results by the total_games field.
func ByTotalGames(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalGames, opts...).ToFunc()
}

// ByWins orders the results by the wins field.
func ByWins(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWins, opts...).ToFunc()
}

// ByLosses orders the results by the losses field.
func ByLosses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLosses, opts...).ToFunc()
}

// ByDraws orders the results by the draws field.
func ByDraws(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraws, opts...).ToFunc()
}

// ByAverageApm orders the results by the average_apm field.
func ByAverageApm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageApm, opts...).ToFunc()
}

// ByAverageEapm orders the results by the average_eapm field.
func ByAverageEapm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAverageEapm, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUploadedReplayFilesCount orders the results by uploaded_replay_files count.
func ByUploadedReplayFilesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUploadedReplayFilesStep(), opts...)
	}
}

// ByUploadedReplayFiles orders the results by uploaded_replay_files terms.
func ByUploadedReplayFiles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploadedReplayFilesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUploadedReplayFilesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploadedReplayFilesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UploadedReplayFilesTable, UploadedReplayFilesColumn),
	)
}
