// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// GameDetail is the predicate function for gamedetail builders.
type GameDetail func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// ReplayFile is the predicate function for replayfile builders.
type ReplayFile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
